### ISSUE TITLE
Uninitialized slider widget behaves unexpectedly.

### ISSUE THREAD

**Issue by beru** [cnjinhao/nana#10]
I thought slider's knob stays on the position when I clicked it. But it stopped on a different position (left side). After some testing, I noticed uninitialized slider doesn't behave as I thought. If I called vmax & value methods of slider widget, It behaves normally.

I still haven't looked up into the source code of the widget to figure out the cause. Probablly it would be of no harm to initialize some member variables in a constructor.

Additionally, this is a subtle thing but slider's knob moves one pixel left after I clicked a slider.

Please run below sample code and click various positions of sl3 slider and make sure if the problem reproduces at your side.

```

#include <nana/gui.hpp>
#include <nana/gui/widgets/slider.hpp>

int main()
{
	using namespace nana;
	form fm(API::make_center(500, 500));

	slider sl1(fm, rectangle(10, 10, 300, 10));
	slider sl2(fm, rectangle(10, 50, 300, 10));
	slider sl3(fm, rectangle(10, 90, 300, 10));

	sl1.vmax(1000);
	sl1.value(100);

	sl2.vmax(2000);
	sl2.value(2000);

	//drawing{ fm }.draw([](paint::graphics& graph){
	//	graph.string({ 10, 10 }, L"Hello, world!", colors::red);
	//});
	//fm.events().click(API::exit);
	fm.show();

	exec();
}


```

**Comment by cnjinhao** [comment]
Thank you for reporting this issue, it is an issue of precision.

**Comment by beru** [comment]
Thank you for the fix. I've cloned the hotfix-branch and confirmed that the issue is cleared.
