### ISSUE TITLE
Wrong source file discovery in CMakeLists

### ISSUE THREAD

**Issue by redagito** [cnjinhao/nana#100]
The CMakeLists.txt file uses the following lines to collect all relevant source files
> set(NANA_SOURCE_DIR ${CMAKE_SOURCE_DIR}/source)
> set(NANA_INCLUDE_DIR ${CMAKE_SOURCE_DIR}/include)

Which causes major problems when using Nana as a sub project in cmake.
The lines should be changed to
> set(NANA_SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/source)
> set(NANA_INCLUDE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/include)

**Comment by cnjinhao** [comment]
Thank you for fixing this issue.
