### ISSUE TITLE
Issues about config.hpp

### ISSUE THREAD

**Issue by cnjinhao** [cnjinhao/nana#101]
Hi, guys
@ierofant , @roberthauck , @qPCR4vir please update the cmake file for config.hpp if you have spare time. Thank you.

The config.hpp has been separated into two parts. (develop branch)

Some symbols, such as adaption of target OS, workarounds compiler errors and lack of std C++ supports, are defined in c++defines.hpp. This part should not be modified by developer, these symbols is detected automatically.

Some symbols for external libraries are defined in config.hpp. Developers can modify the symbols defined in config.hpp to enable/disable features.

BTW, another question. What versions of libstdc++ and libc++ support std::make_unique? I only know GCC 4.9 supports std::make_unique, but I have now idea what version of libstdc++ is.

**Comment by qPCR4vir** [comment]
Hallo Jinhao,
I'm very sorry I have no too much time now. I have try this things already and I have some ideas.
I think you are right, we need to better define all the purposes of the configuration and separate it.
I think we need to separate: OS/platform, compiler, stdlib (all three in c++defines.hpp, but independently ) and optional libraries (in config.hpp). So:

What versions of libstdc++ support std::make_unique? 4.9 or more.
https://gcc.gnu.org/gcc-4.9/changes.html

and libc++?  all versions?

This is very interesting:
https://github.com/boostorg/config/blob/develop/include/boost/config/stdlib/libstdcpp3.hpp

and see this answer and the comments:
http://stackoverflow.com/a/11925468/1458030

Maybe for now we can simple said we don't support libstdc++ older than 4.9? And then work on the issue in an special branch?

**Comment by cnjinhao** [comment]
Thank you for your reply, the version of libstdc++ older than 4.9 is still supported, because of a workaround of make_unique. The major problem is to enable make_unique workaround on clang if it uses libstdc++ older than GCC 4.9's, therefore, it is necessary to check libstdc++ version(__GLIBCXX__) rather than GCC version(__GNUC__)

**Comment by qPCR4vir** [comment]
Hi,
we could create a table-like macro to match `__GLIBCXX__` date to the version, but I think that a better  approach is to test directly the feature we need and set our "nana" or "std" macro.
It is possible to do that with a simple test program in cmake:
https://github.com/eggs-cpp/sd-6/blob/master/tests/cpp/lib/make_unique.201304.cpp
 or directly by using:
https://github.com/eggs-cpp/sd-6/blob/master/EggsSD6.cmake
 but it force to use cmake.

So, see hier:
https://github.com/qPCR4vir/nana/issues/7
we can test `__cpp_lib_make_unique`

please see line 769 in:
https://github.com/gcc-mirror/gcc/blob/master/libstdc%2B%2B-v3/include/bits/unique_ptr.h

also here is an interesting example: (see line 286)
https://gist.github.com/socantre/8609076
 
We need to try to use this:
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/p0096r0.html
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/n4440.html
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3745
