### ISSUE TITLE
CMake policy warning: policy not set

### ISSUE THREAD

**Issue by redagito** [cnjinhao/nana#108]
I am again trying to use Nana as a submodule for a project and encountered the following warning when generating the project with CMake.

I am using CMake 3.2.0 on Windows 7 and using the "develop" branch

> CMake Warning (dev) at external/nana/CMakeLists.txt:8 (if):
>   Policy CMP0054 is not set: Only interpret if() arguments as variables or
>   keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
>   details.  Use the cmake_policy command to set the policy and suppress this
>   warning.
> 
>   Quoted variables like "MSVC" will no longer be dereferenced when the policy
>   is set to NEW.  Since the policy is not set the OLD behavior will be used.
> This warning is for project developers.  Use -Wno-dev to suppress it.

Is it possible to set this policy as it adds to the overall noise of warnings which might actually break something someday

**Comment by cnjinhao** [comment]
Thanks for your feedback, I just set the CMP0054 to old behaviour.
