### ISSUE TITLE
Form widget does not respond to Alt + F4 key.

### ISSUE THREAD

**Issue by beru** [cnjinhao/nana#11]
Other Windows applications as I know of so far handle Alt + F4 key.
So I thought It would be fine if nana library could handle the key down as a user's operation to close the form. And... sorry, I don't remeber if applications on X Window behaves the same.

**Comment by cnjinhao** [comment]
Thank you for reporting this issue. A fix has been checked into the hotfixes-1.0 branch. The Alt+F4 can't be handled on X Window, when Alt+F4 is pressed, it emits unload event to the form. Unlike on Windows, it can be handled by WM_SYSKEYDOWN/UP. Therefore, if library could handle it, it only works on Windows.

**Comment by beru** [comment]
Thank you for the fix. I've cloned the branch and confirmed.
On Linux (Fedora21), the programs I build with nana responds to ALT+F4 key and ALT+SPACE keys.
I wonder if Windows Manager (GNOME) handles them...
