### ISSUE TITLE
Pressing ALT + SPACE key does not show shortcut menu.

### ISSUE THREAD

**Issue by beru** [cnjinhao/nana#12]
When I press Alt + Space key with typical Windows application,
it displays active window's system menu.

Please search "ALT+SPACE" in below page.
https://msdn.microsoft.com/en-us/library/ms971323.aspx

I confirmed that putting another
```
				def_window_proc = true;
```
before the break of case WM_SYSCHAR: in nana::detail::Bedrock_WIN32_WindowProc function can solve the issue.

**Comment by cnjinhao** [comment]
Thank you for resolving this issue.
