### ISSUE TITLE
debugging - throw_not_utf8 and place

### ISSUE THREAD

**Issue by qPCR4vir** [cnjinhao/nana#120]
Hi !
I'm adapting my app from v1.1 to v1.3
I know I have problems with non ASCII characters that I need to make utf8 now.
But anyway, I'm using the "opportunity" to improve the error handling of my app. 
I'm catching exceptions and adding nice messages.

It is more difficult that I wanted.
Here are some of my problems:

- some widgets will throw if some text is not utf8. It may be OK, but it may be situations in which we don't have full control of the text (may come from a file, WWW etc) and one may want to force printing the text, even if it will have some crap... at least to debug! For example: introduce some state flag that tell nana not to `throw_not_utf8`, but print a cerr error and continue with the crappy text. (it will change only the code of `throw_not_utf8 `)

- a related problem: the `msgbox `will refuse and will throw! if you try to report that text. `msgbox `is therefore a good candidate to force (using some explicit arg ) non utf8, crappy print.

- this is a huge problem if you try to show a `msgbox` in the `catch `of an exception - which is very natural - and it terminate the program and you don't have any idea why.

- difficults come from the fact than before drawing and redrawing was basically a safe function, but now may not because of `throw_not_utf8 `.

- going to a catch, c++ will destroy c++ objects, making nana destroy some widgets from inside of some destructor. It can call collocate, which can throw. You prevent this with this code, but somehow `is_destroying` is not always working, and it is difficult to debug why. When it throw here the program is killed.

```cpp
		//Listen to destroy of a window
		//It will delete the element and recollocate when the window destroyed.
		event_handle _m_make_destroy(window wd)
		{
			return API::events(wd).destroy.connect([this, wd](const arg_destroy&)
			{
				for (auto i = elements.begin(), end = elements.end(); i != end; ++i)
				{
					if (!API::is_destroying(API::get_parent_window(wd)))
						place_ptr_->collocate();
				}
			});
		}
```

BDW - I don't understand what is with the iterator` i` that is not used, maybe you wanted `i->collocate();`? ...

**Comment by qPCR4vir** [comment]
The program is now ruining, but again, when I try to fill a `listbox `with data from a file it throw: it can't handle the non ASCII °  that some times is used for °C. 
It could be very good if we can tell nana that in some situations if the text is not utf8 it have to be translated from some locale to utf8

**Comment by qPCR4vir** [comment]
a related problems: the `msgbox `is not showing if it is called before the main windows `show()` and nana::exec(). 
How I can use a `msgbox `in that situation?

**Comment by cnjinhao** [comment]
1, Check whether a text read from file is encoded as UTF-8.
```cpp
if(!nana::is_utf8(text_from_file.c_str(), text_from_file.size()))
    auto utf8_str = nana::charset(text_from_file).to_bytes(nana::unicode::utf8);
```

2,3, msgbox is an issue. 

4, maybe removing throw_not_utf8 from drawing functions is a solution..?

5, this function is incomplete, it should be
```cpp
event_handle _m_make_destroy(window wd)
{
	return API::events(wd).destroy.connect([this, wd](const arg_destroy&)
	{
		for (auto i = elements.begin(), end = elements.end(); i != end; ++i)
		{
			if (i->handle == wd)
			{
				elements.erase(i);

				if (!API::is_destroying(API::get_parent_window(wd)))
					place_ptr_->collocate();
				break;
			}
		}
	});
}
```

6, I verified that the msgbox can be shown before showing main form on Windows 10.
```cpp
int __stdcall WinMain(HINSTANCE, HINSTANCE, char*, int)
{
	using namespace nana;

	form fm;

	msgbox mb(fm, "hello"); //or msgbox mb("hello");
	mb.show();

	fm.show();
	exec();

	return 0;
}
```

**Comment by qPCR4vir** [comment]
Hi, Thank !
1- Ok, I will implement that. But before I need a lite investigation... I don't know what are the problematic files. I have many hundreds of then.
I'm experimenting with the following:

```cpp

	struct utf8_Error : std::runtime_error
	{
		static bool use_throw; ///< def { true }; use carefully - it is a global variable !! \todo initialize from a #define ?

		utf8_Error(const std::string& what_arg)
			:std::runtime_error{ std::string("\nRun-time utf8 Error: ") + what_arg }
		{}

		utf8_Error(const char * what_arg)
			:utf8_Error{ std::string(what_arg) }
		{}


		void emit()
		{
			if (use_throw)
				throw utf8_Error(*this);
			std::cerr << what();
		}
	};

	//bool utf8_Error::use_throw{true}; 
	bool utf8_Error::use_throw{ false };

	void throw_not_utf8(const std::string& text)
	{
		if (!is_utf8(text.c_str(), text.length()))
			return utf8_Error(std::string("The text is not encoded in UTF8: ") + text).emit();

			//throw std::invalid_argument(  std::string("The text is not encoded in UTF8: ")+text  ) ;
	}

	void throw_not_utf8(const char* text, unsigned len)
	{
		if (!is_utf8(text, len))
			return utf8_Error(std::string("The text is not encoded in UTF8: ") + std::string(text, len) ).emit();

		//throw std::invalid_argument("The text is not encoded in UTF8");
	}

	void throw_not_utf8(const char* text)
	{
		if (!is_utf8(text, std::strlen(text)))
			return utf8_Error(std::string("The text is not encoded in UTF8: ") + text).emit();

		//throw std::invalid_argument("The text is not encoded in UTF8");
		
	}

```
For debugging it is working very well. When it is  - true it throws and terminates (with a msgbox where I commented out I the utf8 test). 
Now I see very well were are the problematic files: only 2 !
You my be right, and this enforce correctness - but the rest of nana is very flexible, and nana don't crash in many cases when the user do ... well something not very good. But now is crashing or throwing for things that may be difficult to control. 
I will try to experiment with the following: if some global flag is set it will not throw, but will silently use `charset `to convert the text in the best possible way, and will show the better possible variant of the crappy text. It can be a new function `review_utf8`, that when called with a `const `will simple call `throw_not_utf8 `and when called with nonconst will transform the text argument if need as you showed. ... eh, well for string..

2,3 I commented that, but may be better to use here the `review_utf8 `idea.

4, maybe. call it during creation only, not during drawing?? Not sure. For a button and a like - yes, but now I can see in my console that it throw **only** when the item is show. It is "lazy". My list had thousands of items. It can make even more slow the creation? Not a trivial decision. 
5, I will test
6, hmmm, I will need to investigate my problem better.

I will made a PR - please take only what you see OK.

**Comment by qPCR4vir** [comment]
It was `text_extent_size`...

**Comment by cnjinhao** [comment]
`review_utf8` is a good idea, no throw(or throws when debug mode) , replaces `throw_not_utf8`. 

```cpp
T review_utf8_const(const std::string& str)  //T is a type which holds a new string or refers to an existing string.
{
	if (is_utf8(str))
		return T(str);	//no copy, the return value refers to the str.

	std::string tsf_str;
	for_each_utf8(ch)
	{
		if_ch_is_utf8_char
		{
			tsf_str.append(ch);
		}
		else
		{
			tsf_str += '*'; //use a symbol(a unicode char) to stand for the non-utf8 character.
		}
	}

	return T(tsf_str); //
}

std::string review_utf8(std::string&& str); //

//For example
widget& widget::caption(std::string utf8)
{
	_m_caption(to_nstring(review_utf8(std::move(utf8))));
	return *this;
}

button.caption("abcNN123"); //N stands for a non-utf8 encoded character.
//the button prints "abc**123" to inform user the string is not encoded as UTF-8
```

**Comment by qPCR4vir** [comment]
At the end I hope that c++ will add a class std::text (see for example [P0244R0 : Text_view](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0244r0.html) implemented [here](https://github.com/tahonermann/text_view) an discussed [here](https://groups.google.com/a/isocpp.org/forum/#!searchin/std-proposals/Text_view$20/std-proposals/Tu84_TQOlhc/lV0MdIq1HQAJ) but that will implement all the members of `string `that make sense, like `substr`, `find`, etc.) that will use some `std::basic_string` as an internal representation and that will solve all of this problems, and that nana or any other UI will safely and portable use it, so that I don't think we need to find here a perfect solution. ([here](https://groups.google.com/a/isocpp.org/forum/#!searchin/std-proposals/Text/std-proposals/ET5TazMU3r8/2UUQlFIcCQAJ) is  one of the problems ). In fact, your `nana::charset` do an important part of that. 

But all of then are mainly about manipulating and converting from known and error free encoded string. And how to set the behavior by error? (Is this called a police? .. ah, yes, just see: [Add a policy class template parameter to basic_text_view and itext_iterator to enable custom error handling](https://github.com/tahonermann/text_view/issues/14))  

The functions that take data (one by one code unit, possible multiple bytes) from an "original" possible user-supplied `std::string` - and that we assumed is utf8, utf16 or utf32 - and convert it to an unicode code point are:
`unsigned long utf8char(const unsigned char*& p, const unsigned char* end)`,
`unsigned long utf16char(const unsigned char* & bytes, const unsigned char* end, bool le_or_be)` and
`unsigned long utf32char(const unsigned char* & bytes, const unsigned char* end, bool le_or_be)`

Now... What will be nana reaction if it find an erroneous code (a byte with a forbidden value like 0x81 in the first byte of an utf8 character)? Currently it simple truncate the string, ignoring this character and all the rest of the string. This is a valid and safe default behavior (though it need to be documented). But this is also hard-coded and there is no way to change this behavior or to even flag/detect it. This causes that the only thing we can do around is to do a pre check with a function like `is_utf8 `or `throw_not_utf8`. One step in adding flexibility if what you proposed in that version of `review_utf8` : after detecting a bad code unit - replace the bad code point with the code point for *. More in this direction will be to customize that character or code point, permitting the user to set for example a quadrat (what fonts used to signal not supported code point). Another police could be what I'm successfully testing now and that may be what best pass in may case: to simple copy that byte to the code point, by returning `return *(p++); ` for `(*p < 0xC0)` just like for `<0x80 `  - because in Unicode the code point values for the characters interesting for me have the same code in latin1 code page. (like ° and µ, etc.) 


Related things:

We see in Windows Kits\8.1\Include\um\WinNls.h
```cpp
//
//  Code Page Default Values.
//
#define CP_ACP                    0           // default to ANSI code page
#define CP_OEMCP                  1           // default to OEM  code page
#define CP_MACCP                  2           // default to MAC  code page
#define CP_THREAD_ACP             3           // current thread's ANSI code page
#define CP_SYMBOL                 42          // SYMBOL translations

#define CP_UTF7                   65000       // UTF-7 translation
#define CP_UTF8                   65001       // UTF-8 translation
```

(BTW, [std::string_view](http://en.cppreference.com/w/cpp/string/basic_string_view) is already `std `and may significantly improve clarity and efficiency sometimes)  

[interestintg](https://blog.jetbrains.com/idea/2013/03/use-the-utf-8-luke-file-encodings-in-intellij-idea/)
[more](htmlpurifier.org/docs/enduser-utf8.html)
[std::wstring_convert](http://en.cppreference.com/w/cpp/locale/wstring_convert)
