### ISSUE TITLE
Listbox enable_single crash

### ISSUE THREAD

**Issue by Greentwip** [cnjinhao/nana#121]
Inside the method: 

`void trigger::mouse_down(graph_reference, const arg_mouse& arg) { ... } `

It is essential to check for the item pointer or the application will crash when selecting a category: 
`
if (!lister.single_selection()){  
...
} else {
    if (item_ptr) {
        sel = !item_proxy(essence_, index_pair(item_pos.cat, lister.absolute(item_pos))).selected();
    }
}
`
if the listbox was created with enable_single.

**Comment by cnjinhao** [comment]
Thank you for reporting and fixing this issue.
