### ISSUE TITLE
Default icon for form window

### ISSUE THREAD

**Issue by dawikur** [cnjinhao/nana#133]
Hi,

I have added default icon for windows app using cmake:
```cmake
set(resource_file
  ../res/app.ico
  app.rc
)

add_executable(${project_name} ${project_srcs} ${resource_file})

set_target_properties(${project_name} PROPERTIES
  RESOURCE "${resource_file}"
)
```

This works great for exe icon and console ico. Unfortunately window created using nana::form diesn't have my ico 

![icons](https://cloud.githubusercontent.com/assets/11866902/15358820/a1ee4fce-1d06-11e6-8840-47d4882174c0.png)

I was thinking that the default app ico will be propagated to form windows. Am I missing something? Or maybe there is no such functionality?

**Comment by cnjinhao** [comment]
~~~c++
form.image(image{"./your_exe_filename"});

//or
//call
API::window_icon_default(image{"./your_exe_filename"});
//before creation of forms, then all new forms will default load the icon.
~~~

**Comment by dawikur** [comment]
Thanks for quick response. I am sure that I have tried `window_icon_default` but probably after form initialization. Now it works perfectly :) Thanks!
