### ISSUE TITLE
Need help with Travis CI

### ISSUE THREAD

**Issue by cnjinhao** [cnjinhao/nana#136]
I use the @qPCR4vir  nana-demo's `dev_nana_in_examples` branch for building testing nana's `develop` branch, it reports the linker error about the std.filesystem(maybe boost.filesystem) when compiles `file_explorer`, so I decided to remove the `file_explorer` from "https://github.com/qPCR4vir/nana-demo/blob/dev_nana_in_examples/CMakeLists.txt" at line 180:
~~~~
set (demos calculator notepad widget_show widget_show2)
~~~~
then I restarted the Travis Job, it still reports the linker errors that caused by compiling `file_explorer`. I don't understand why the `file_explorer` still gets built, and why it still outputs
"... to build: ../nana-demo/file_explorer.cpp"

**Comment by qPCR4vir** [comment]
Hi !
I'm working on that.

**Comment by qPCR4vir** [comment]
I'm sorry... all of this need actualization / completion.
**nana-demo** have not yet per-se _travis_ activated (an important TODO!). 
The only travis- support  I see is in nana. And nana uses it own cmake list to build nana and the demos from the nana-demo repo. 

You need to exclude `file_explorer` from 
https://github.com/cnjinhao/nana/blob/develop/CMakeLists.txt#L248

**Comment by qPCR4vir** [comment]
I think the problem is that now travis uses gcc 5.4 and not more 5.2. And 5.4 have filesystem but need the link-flag -lstdc++fs. Also it is in another namespace? or it need explicitly to be added after all the object that use it...

**Comment by cnjinhao** [comment]
I have tried -lstdc++fs, but it still reports linker error. I guess it occurs by the filesystem_selector.php, it chooses the boost.filesystem.

Is it possible to make the DEMO get apart from nana's CMakeLists? 
Nana's hotfix and master branch use nana-demo's master branch.
Nana's develop branch uses nana-demo's develop branch.(nana-demo's develop and master branches are the same at most of the time).

**Comment by cnjinhao** [comment]
I removed 'file_explorer','widget_show','widget_show2' and 'folder_tree'. Now it get passed.

**Comment by qPCR4vir** [comment]
Hi... uf, done.
No, filesystem_selector was OK. I improved it and the verbose preprocessor.
The error was related to very very obscure problems in the syntax of cmake.
No need to removed the demos.

**Comment by cnjinhao** [comment]
Good job! it is OK now.
