### ISSUE TITLE
Minor listbox scrolling issue

### ISSUE THREAD

**Issue by ErrorFlynn** [cnjinhao/nana#143]
It seems that scrolling the listbox contents with the wheel always scrolls in 3 line increments. That can be an issue if scrolling downward (rolling the mouse wheel down) when there are less than 3 items to be scrolled into view at the bottom of the list. In that case, the listbox scrolls 3 lines even though only 1 or 2 items are left out of view, the whole contents being misaligned with the bottom as a result, looking as if there are 1 or 2 blank lines at the bottom. Moving the mouse to trigger certain events (like hovering over the scrollbar, or highlighting a different item) fixes the misalignment.

**Comment by cnjinhao** [comment]
Hi, thank you for reporting this issue, this issue has been fixed in develop branch. The scroll increment steps is initialized with system parameter, and the steps can be modified using listbox scheme.
