### ISSUE TITLE
menu.append() callback too critical

### ISSUE THREAD

**Issue by Tumiz** [cnjinhao/nana#144]
menu.append() requires that callback functions have no parameters except "menu::item_proxy& ip".
When form is needed, only lambda expression can be used.

**Comment by cnjinhao** [comment]
Hi, is there any problem?

**Comment by Tumiz** [comment]
It is difficult to transfer some data to callback functions. Callbacks with parameters are not allowed in Nana.
I found lambda expression is the only way to do it. But lambada cannt be used twice. For example we have some widgets of different kinds, but they have a same event. In nana, we must write the same lambda several times as the number of those widgets. While the same thing can be done easily by just writing a normal callback function only once. 
So I need that widgets can append callbacks with parameters. That will be useful at some time.

**Comment by cnjinhao** [comment]
Hi, you can capture this pointer, and find the data associated with the menu item. Or use std::bind to binds extra data.

**Comment by nabijaczleweli** [comment]
`std::bind()` is cancer

**Comment by sehe** [comment]
@nabijaczleweli  that may be true, but c++11 captures can equivalently be used to "bind" that extra data (instead of or in addition to `this`)

**Comment by leobackes** [comment]
Just to add my 2 cents on why this could be closed: a lambda can be used twice, it is just a matter of storing it:
`auto my_callback=[this](...){ do_some_magic(); }`
`menu.append("Option 1", my_callback);`
`menu.append("Option 2", my_callback);`
