### ISSUE TITLE
horizontal scroll in listbox in develop

### ISSUE THREAD

**Issue by qPCR4vir** [cnjinhao/nana#145]
Hi, 
the `hotfix `branch is OK, but in the `develop `branch the horizontal scrollbar appear only when the vertical scrollbar is visible. This is in the current (2016-07-13) 02acc4c216d05727422cb4813f0d47b9fc7de9a3, but it is not new, at last in (2016-06-28) b32afa282ce20f929afcf896a805d84a7edea76c it was already, maybe even before.

I can't fix that because I don't know who and when draw the scrollbar.

**Comment by cnjinhao** [comment]
Thanks for reporting this issue. The issue is introduced by the implementing listbox column ranged width.

**Comment by qPCR4vir** [comment]
Is Ok ! Thank
