### ISSUE TITLE
Adding a header to a listbox in the branch develop cause crashes on Linux (X11).

### ISSUE THREAD

**Issue by dankan1890** [cnjinhao/nana#147]
As the title suggests, under linux (ubuntu) if you add a header to a listbox the program crashes.
It just happens to me?

**Comment by cnjinhao** [comment]
Hi, 
Thanks for your feedback. I did a simple test, but I couldn't reproduce this issue. Would you please provide a simple code to reproduce it and the call stack?

**Comment by dankan1890** [comment]
```c++
#include <nana/gui/wvl.hpp>
#include <nana/gui/place.hpp>
#include <nana/gui/widgets/listbox.hpp>
int main()
{
	using namespace nana;
	form    fm;
	place pl(fm);
	listbox lbox(fm);
	lbox.append_header("Prova");
	pl.div("<listbox>");
	pl["listbox"] << lbox;
	pl.collocate();
	fm.show();
	exec();
}
```
and this is the error output:

> X Error of failed request: BadAlloc (insufficient resources for operation)
   Major opcode of failed request: 53 (X_CreatePixmap)
   Serial number of failed request: 82
   Current serial number in output stream: 223
terminate called without an active exception

However, after further testing, the problem occurs only when the place is used.

**Comment by dankan1890** [comment]
Further info, if I move the call to append_header after the place.collocate(), it works.

**Comment by cnjinhao** [comment]
Hi, thanks for your responding, a fix has been checked into the develop branch.

**Comment by dankan1890** [comment]
Now works. Thanks!
