### ISSUE TITLE
field_display not seem to work properly

### ISSUE THREAD

**Issue by dankan1890** [cnjinhao/nana#152]
From what I understand by reading the documentation, setting field_display to false should make invisible the field and don't occupy the space as before, instead it seems to work exactly as field_visible.

**Comment by cnjinhao** [comment]
Hi, I checked the issue, it works as expected. Please show me the steps to reproduce the issue.

**Comment by dankan1890** [comment]
Example code:
```c++
#include <nana/gui/wvl.hpp>
#include <nana/gui/widgets/button.hpp>
#include <nana/gui/place.hpp>
int main()
{
	using namespace nana;
	form    fm;
	place pl{ fm };
	button btn1{ fm, "Button 1" };
	button btn2{ fm, "Button 2" };
	button btn3{ fm, "Button 3" };
	button removebtn{ fm, "Remove Button 1" };
	pl.div("vert <<btn1><btn2><btn3>><<><button><>>");
	pl["btn1"] << btn1;
	pl["btn2"] << btn2;
	pl["btn3"] << btn3;
	pl["button"] << removebtn;
	pl.collocate();
	removebtn.events().click([&pl] {
		pl.field_display("btn1", false); 
	});
	fm.show();
	exec();
}
```
Start screenshot
![snap1](https://cloud.githubusercontent.com/assets/7107228/17691147/2817aafa-6393-11e6-97c7-c474c09bf58d.png)

After "Remove Button 1" click
![snap2](https://cloud.githubusercontent.com/assets/7107228/17691164/3f2a4e28-6393-11e6-8904-f44a4012b1ab.png)

What I expected
![snap3](https://cloud.githubusercontent.com/assets/7107228/17691184/60f57dde-6393-11e6-953a-82138a134dc8.png)

**Comment by cnjinhao** [comment]
```
    removebtn.events().click([&pl] {
        pl.field_display("btn1", false);   //the change of layout will take effect after collocate()
        pl.collocate(); //so don't forget this.
    });
```

**Comment by dankan1890** [comment]
Ah ok, thanks for the explanation!
