### ISSUE TITLE
erase diehard_t maybe a bug

### ISSUE THREAD

**Issue by Tumiz** [cnjinhao/nana#153]
In drawing.cpp, is it a bug?
It means only if window doesnt exist, that diehard_t can be erased!?
And I try to use this method, it does not work. Nothing happened.
`		void drawing::erase(diehard_t d) 
		{ 
 			if(API::empty_window(handle_)) 
				restrict::get_drawer(handle_).erase(d); 
		} 
`

**Comment by Tumiz** [comment]
after I modify those codes like below, and rebuild nana lib, then problem fixed.
`		void drawing::erase(diehard_t d)
		{
			if(API::empty_window(handle_)) return;
			restrict::get_drawer(handle_).erase(d);
		}`

**Comment by cnjinhao** [comment]
Thanks a lot for your fix.

**Comment by cnjinhao** [comment]
The fix has been checked into the hotfix branch
