### ISSUE TITLE
listbox multiple selection throw exception

### ISSUE THREAD

**Issue by RenaudAlpes** [cnjinhao/nana#154]
I have a simple list box, if I click on an item the line is selected, now I press shitft key for multiple selection (and keep pressing it after) and click below the list box (in the white area) the item is unselected (seleciton is empty), now if I click again on the listbox while mainting shift pressed an excepetion is thrown and a popup appears (nana::listbox invalid category index). It seems to be a bug, I have reproduced it with hotfix branches and develop on my pc under windows.

Here is the code I use:

   ``

    form fm(API::make_center(800, 500));
    listbox lsbox(fm, rectangle{ 10, 10, 800, 500 });
    lsbox.append_header("column 0");
    lsbox.append_header("column 1");
    lsbox.at(0).append({ std::string("Hello0"), std::string("World0") });
    lsbox.at(0).append({ std::string("Hello1"), std::string("World1") });
    lsbox.at(0).append({ std::string("Hello2"), std::string("World2") });
    lsbox.at(0).append({ std::string("Hello3"), std::string("World3") });
    
    fm.show();
    exec();`

**Comment by cnjinhao** [comment]
Thanks a lot for your feedback.

**Comment by RenaudAlpes** [comment]
Thanks a lot for the very fast fix. It works now no more exception.
