### ISSUE TITLE
Will there be a built-in webpage browser

### ISSUE THREAD

**Issue by avaicode** [cnjinhao/nana#155]
Sometimes HTML code can express more things than classic GUI.For example,it's very convenient to show scores of students just with HTML and CSS,which is pretty as well.
So,will there be a built-in webpage browser in nana?I am very looking forward to it.
(I am inspired by this repo [litehtml](https://github.com/litehtml/))

**Comment by cnjinhao** [comment]
Hi, there is not current plan to develop a html renderer. It's a huge project.
