### ISSUE TITLE
Shifting a splitter, the div_text's string is not updated.

### ISSUE THREAD

**Issue by dankan1890** [cnjinhao/nana#157]
In the case of a movement of a splitter, the div_text string should be updated accordingly.

**Comment by cnjinhao** [comment]
This is complicated, it is not easy to find the div-text of the corresponding splitter.

**Comment by qPCR4vir** [comment]
Hi Dankan...

What you set in the div str is the initial position of the split, not the current position -  a litter difference.
The div str dont tell you the actual geometry (positions, size - which are dynamically set), only set the rules. If you explicitly change the div str to set a new initial split position, you obviously will be able to retrieve it.

I suspect that what you may need (and I need too) is that the field reference we can retrieve with `field(name)` will have a member  `rectangle `from which you can extract dynamic information.

**Comment by cnjinhao** [comment]
@qPCR4vir is right, div-text is to define the rules of layout. But it would be great if the div-text can be updated when shifting a splitter. A proper solution is to add/modify the weight attribute of the fields on the both side of splitter.

**Comment by dankan1890** [comment]
The issue is that, at the time, you can also specify the field without a name (Ex: "<abc> | < <def> <ghi> >" which is basically a weight 50% - 25% - 25%), this it is difficult to manage without a name to search.
The div should have "rules" more strict, to be handled in the current manner, with the update on the fly to any change.
Or, you could opt for a div() function that "recreates" the text by taking the data from the root_division directly (iterating the various children).

**Comment by cnjinhao** [comment]
It works if one of splitter fields has a name or its child or its child's child has a name. If no field has a name, moving splitter doesn't update the div-text.

**Comment by dankan1890** [comment]
Nice, works, but there is an issue in function _m_number:
```cpp
if ('%' == *sp)
{
	if (number_t::kind::integer == number_.kind_of())
		number_.assign_percent(number_.integer());
	return sp - allstart + 1;
}
```
in the second if statement, the value previously saved of weight isn't converted back into percent, being a real number and not an integer.

**Comment by cnjinhao** [comment]
Thanks a lot, I will check it.

**Comment by dankan1890** [comment]
Thanks, now works perfectly.
