### ISSUE TITLE
Filebox example compile error

### ISSUE THREAD

**Issue by petterpripp** [cnjinhao/nana#163]
http://nanapro.org/en-us/documentation/utilities/filebox.htm

The example in link above do not compile. Example is outdated? 
Below is example that does compile.

```
#include <nana/gui.hpp>
#include <nana/gui/filebox.hpp>
#include <string>

int main()
{
    nana::filebox fb(true);
    fb.add_filter("Text File", "*.text;*.doc");
    fb.add_filter("All Files", "*.*");

    if(fb())	//When user clicked 'OK'
    {
        std::string file = fb.file();
    }
}
```

**Comment by cnjinhao** [comment]
Thanks for your feedback. That example is out of date, the `nana::string` is deprecated.
