### ISSUE TITLE
Native look-and-feel?

### ISSUE THREAD

**Issue by markand** [cnjinhao/nana#174]
Hi,

I like much your library but I was guessing if there are plans to use the native API to have a better look-and-feel on Windows, macOS, etc.

**Comment by cnjinhao** [comment]
Hi, there is not  a plan to support native look-and-feel. I can't find any system which provides functions to render a controls with its look-and-feel.

**Comment by RBM-GITHUB** [comment]
@cnjinhao Did you mean wxWidgets? wxWidgets is famous for letting the program use native controls and widgets.

**Comment by beru** [comment]
I guess there are ways but it takes a lot of efforts to implement them.
https://msdn.microsoft.com/en-us/library/windows/desktop/dd162480(v=vs.85).aspx
https://msdn.microsoft.com/en-us/library/windows/desktop/bb773190(v=vs.85).aspx

**Comment by RBM-GITHUB** [comment]
Have tried implementing an abstract set of graphical components? Sorry, not trying to sound rude, but I've not looked into your code...

Or, you could also ask or assign one of the people who are forking and watching your project? Your project has accumulated about 390 stars to this day, so why don't you take advantage of GitHub? (Well, I'm not capable so don't ask *me* lol)

**Comment by wjiali6** [comment]
It might be too complicated, because of nana's dynamic message subscription and dispatch mechanism, or somebody have already done this, wxWidgets, as you said.
