### ISSUE TITLE
collapse(0,1,3,1)

### ISSUE THREAD

**Issue by cathaychen** [cnjinhao/nana#175]
What does it mean?

**Comment by qPCR4vir** [comment]
In [place ](http://nanapro.org/en-us/documentation/utilities/place.htm) you can define a grid (a regular table with cells in which you can them place some windget), and you can collapse some cells with this command.  Here beggening with column 0 row 1 unify 3 columns and 1 row, as in ![grid colapsed](http://nanapro.org/images/help/place_collapse.png)
