### ISSUE TITLE
Monochrome BMP on Windows has wrong colors

### ISSUE THREAD

**Issue by rsyllwasschy** [cnjinhao/nana#179]
Using the following program, I can display a BMP file containing a QR code.
The image was created using the ZINT Barcode library.

If the Bitmap is monochrome, the colors are red/green instead of B/W.

Example image (converted to GIF):

Monochrome:
![out](https://cloud.githubusercontent.com/assets/25074833/21883415/4c26e73a-d8af-11e6-9137-feeaa1e73571.gif)

Same image, but forced to have more colors:
![out4](https://cloud.githubusercontent.com/assets/25074833/21883428/5a3ef5f6-d8af-11e6-8f8e-1f3fbddb6f07.gif)

#include <nana/gui/wvl.hpp>
#include <windows.h>

int main()
{
	using namespace nana;
	form fm{ API::make_center(800, 600) };

	drawing dw(fm);
	
	dw.draw([](paint::graphics& graph)
	{	nana::paint::image img("mono.bmp");	
		img.paste(nana::rectangle(img.size()), graph, nana::point());
	});
	dw.update();
	fm.show();
	::nana::exec();
}

**Comment by cnjinhao** [comment]
Hi, could you please send me the original monochrome bitmap file? I converted the GIF to BMP using mspaint with option monochrome, then it is displayed correctly.

**Comment by rsyllwasschy** [comment]
Yes, sure.

Mono.bmp is showing black as green and white as red.

I also used the conversion via MS Paint to produce Mono2.bmp
and verified that Mono2.bmp is rendered correctly.

I used ImageMagick convert (the windows executable is named “magick”) like this:

magick mono2.bmp mono3.bmp (Haven’t tried on Linux yet)

The result is again a false color rendering.

I guess some of the files are either lacking palette information or have wrong palette information.

Thanks for trying to fix this.

Regards,

-          Robin





Von: Jinhao [mailto:notifications@github.com]
Gesendet: Donnerstag, 12. Januar 2017 20:44
An: cnjinhao/nana
Cc: Syllwasschy, Robin; Author
Betreff: Re: [cnjinhao/nana] Monochrome BMP on Windows has wrong colors (#179)


Hi, could you please send me the original monochrome bitmap file? I converted the GIF to BMP using mspaint with option monochrome, then it is displayed correctly.

**Comment by rsyllwasschy** [comment]
The attachments get removed on github.

You can download them from here
http://www.xup.in/dl,20899314/mono.bmp/
http://www.xup.in/dl,61646181/mono2.bmp/
http://www.xup.in/dl,33281287/mono3.bmp/


Krita, Gimp and ImageMagick display are showing the file correctly in b/w
My guess is that mono.bmp and mono3.bmp do not have any palette information.

Regards,
Robin

Von: Jinhao [mailto:notifications@github.com]
Gesendet: Donnerstag, 12. Januar 2017 20:44
An: cnjinhao/nana
Cc: Syllwasschy, Robin; Author
Betreff: Re: [cnjinhao/nana] Monochrome BMP on Windows has wrong colors (#179)


Hi, could you please send me the original monochrome bitmap file? I converted the GIF to BMP using mspaint with option monochrome, then it is displayed correctly.

**Comment by rsyllwasschy** [comment]
Hi,

some more information:

It seems, MS Paint and nana both disregard the palette information on monochrome bitmaps.

MS Paint doesnt handle the palette correctly.
If I load the bmp into Gimp and look at the palette information, it consists of 2 color entries.
If I change the “white” entry (ffffff) to red (ff0000) and export the BMP, it will show as completely black in MS Paint.

Other raster programs (krita, gimp, Irfanview) show it correctly.

In nana, the image shows Black/gray

[cid:image001.png@01D26D7C.E000D950]

Regards,
Robin



Von: Jinhao [mailto:notifications@github.com]
Gesendet: Donnerstag, 12. Januar 2017 20:44
An: cnjinhao/nana
Cc: Syllwasschy, Robin; Author
Betreff: Re: [cnjinhao/nana] Monochrome BMP on Windows has wrong colors (#179)


Hi, could you please send me the original monochrome bitmap file? I converted the GIF to BMP using mspaint with option monochrome, then it is displayed correctly.

**Comment by cnjinhao** [comment]
Thank you for the information. I found that the issue is caused by incorrect processing of the palette. There are two kind of color tables. The length of a color table entry may be 2-byte or 4-byte length. Nana now treats all entries as 4-byte length. I will fix it a little later.
