### ISSUE TITLE
Throw exception "std::range_error" when using nana::menubar::push_back() to push a chinese string

### ISSUE THREAD

**Issue by bigmammoth** [cnjinhao/nana#182]
void make_menu()
{
	menu_bar.push_back("&Data Import");
	menu_bar.push_back("&Extrume");
	menu_bar.push_back("分析"); 
	menu_bar.push_back("&Help");
}

after running "menu_bar.push_back("分析"); " , the program stopped and throw an exception "std::range_error". 
It looks like that "wide_string from_bytes(const char *_First, const char *_Last)" has got an error after calling "_Pcvt->in()" .

Thanks for your help. Any suggestion will be very appreciated.

**Comment by bigmammoth** [comment]
The program running on windows10 X64 chinese version and complied by Visual Studio 2013

**Comment by cnjinhao** [comment]
It's an expected behavior that throws an `std::range_error`. The parameter whose type is `std::string` for most API only accepts a string in UTF-8 encoded. So use one of following proper way.

```c++
menu_bar.push_back(::nana::charset("分析").to_bytes(::nana::unicode::utf8));
menu_bar.push_back(nana::to_utf8(L"分析")); //VS2013, don't forget L
menu_bar.push_back(u8"分析"); //other C++11 compilers. e.g VS2015
```

The prototypes of to_utf8 are
```c++
const std::string& to_utf8(const std::string& u8text); //directly returns u8text, it must be a UTF-8 string.
std::string to_utf8(const std::wstring& wtext); //returns a string of wtext in UTF8 encoded.
```
"分析" is not a UTF-8 string in Windows, so L is required to call the `const-ref std::string` overloading of to_utf8.

**Comment by beru** [comment]
Maybe this compile option `/utf-8` can be used.
https://msdn.microsoft.com/ja-jp/library/mt708821.aspx

**Comment by bigmammoth** [comment]
Many thanks for your quick responses.
I did it as JinHao's advise, it works. Now my project can be moved on.
Thanks for beru's advise about the complie option, it provides me another knowledge point.
Unfortunately, the option /utf-8 doesn't work on vs2013, maybe it is for vs2015.

**Comment by beru** [comment]
@bigmammoth You are correct. I hope you'll be able to migrate newer versions of Visual Studio in future.
https://blogs.msdn.microsoft.com/vcblog/2016/02/22/new-options-for-managing-character-sets-in-the-microsoft-cc-compiler/
