### ISSUE TITLE
nana::scroll set incorrect value

### ISSUE THREAD

**Issue by Diltsman** [cnjinhao/nana#183]
Given this code:

    #include <nana/gui/widgets/scroll.hpp>
    #include <nana/gui/wvl.hpp>
    #include <Windows.h>
    
    int CALLBACK WinMain(
    	_In_ HINSTANCE hInstance,
    	_In_ HINSTANCE hPrevInstance,
    	_In_ LPSTR     lpCmdLine,
    	_In_ int       nCmdShow
    )
    {
    	using namespace nana;
    
    	std::vector<std::string> model;
    
    	form fm;
    	fm.show();
    	fm.collocate();
    
    	nana::scroll<false> scroll{ fm, true };
    
    	scroll.amount(0);
    	scroll.range(300);
    	scroll.value(0);
    
    	exec();
    }

`scroll.value` is set to either 4294966996 (32-bit Windows) or 18446744073709551316 (64-bit Windows).  The issue is in `void nana::drawerbase::scroll:trigger<false>::value(size_type s)`.

Trouble lines are:

    if (s + metrics_.range > metrics_.peak)
        s = metrics_.peak - metrics_.range;

**Comment by Diltsman** [comment]
Looking in to this a bit more, `void nana::drawerbase::scroll:trigger<false>::value(size_type s)` does not account for the case where `metrics_.range > metrics_.peak`; you will always get a bad value in these cases.

**Comment by cnjinhao** [comment]
Hi, thank you for your information and reporting this issue. A fix has been checked into hotfix branch.
Now, the fix make scroll return 0 when range > peak.
