### ISSUE TITLE
High DPI support

### ISSUE THREAD

**Issue by beru** [cnjinhao/nana#184]
I hope this library will support scaling feature so that its widgets and forms look alright on High DPI displays.

**Comment by cnjinhao** [comment]
I thought about this issue. I intend to add the support of the feature for `class place`, a new uint pt(point) and DPI-aware feature. Any advice and suggestion are greatly appreciated!

**Comment by beru** [comment]
I suppose rendering routines inside widget classes needs to be revised to support various target image sizes. And raster data (bitmap) needs to be interpolated according to scaling setting.

**Comment by beru** [comment]
For further discussion, please check #511
