### ISSUE TITLE
nana::input::integer keyboard input misbehaves

### ISSUE THREAD

**Issue by Diltsman** [cnjinhao/nana#185]
Given a `nana::inputbox::integer` with a range that is at least two digits (greater than 10), when the cursor is inside the spinbox and digits are typed, the digits are inserted right-to-left, rather than left-to-right as would be expected.

**Comment by cnjinhao** [comment]
Thank you for reporting this issue, I will review it.

**Comment by cnjinhao** [comment]
Fixed
