### ISSUE TITLE
clang/libc++ support

### ISSUE THREAD

**Issue by bodomartin** [cnjinhao/nana#188]
Hi,

does the library work with clang (3.9+, c++14 or c++17) and libc++ ? When I try to compile I get a number of errors like below (sorry for the formatting)

/usr/bin/../include/c++/v1/utility:245:51:

 error: missing 'typename' prior to dependent type name
      '__is_nothrow_swappable<_Tp>::value'
swap(_Tp (&__a)[_Np], _Tp (&__b)[_Np]) _NOEXCEPT_(__is_nothrow_swappable<_Tp>::value)
                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/bin/../include/c++/v1/__config:631:34: note: expanded from macro '_NOEXCEPT_'
#  define _NOEXCEPT_(x) noexcept(x)
                                 ^
In file included from /work/downloads/17/TEMP/nana/source/any.cpp:16:
/usr/bin/../include/c++/v1/utility:245:5: error: function cannot return function type 'typename
      enable_if<__is_swappable<_Tp>::value>::type (__is_nothrow_swappable<_Tp>::value)'
swap(_Tp (&__a)[_Np], _Tp (&__b)[_Np]) _NOEXCEPT_(__is_nothrow_swappable<_Tp>::value)
    ^
/usr/bin/../include/c++/v1/utility:338:20: error: missing 'typename' prior to dependent type name
      'is_nothrow_copy_assignable<first_type>::value'
        _NOEXCEPT_(is_nothrow_copy_assignable<first_type>::value &&
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/bin/../include/c++/v1/__config:631:34: note: expanded from macro '_NOEXCEPT_'
#  define _NOEXCEPT_(x) noexcept(x)
                                 ^
In file included from /work/downloads/17/TEMP/nana/source/any.cpp:16:
/usr/bin/../include/c++/v1/utility:339:61: error: parameter declarator cannot be qualified
                   is_nothrow_copy_assignable<second_type>::value)
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/usr/bin/../include/c++/v1/__config:631:34: note: expanded from macro '_NOEXCEPT_'
#  define _NOEXCEPT_(x) noexcept(x)
                                 ^
In file included from /work/downloads/17/TEMP/nana/source/any.cpp:16:
/usr/bin/../include/c++/v1/utility:337:20: error: function cannot return function type 'pair<_T1, _T2>
      &(is_nothrow_copy_assignable<first_type>::value &&)'
    pair& operator=(const pair& __p)

**Comment by pixelr** [comment]
@bodomartin I had same issue while building and posted on their forum long back. what I understood from the forum that only few version of Clang is supported. If you are able to find any please do let me know.

**Comment by pixelr** [comment]
Meanwhile, I installed g++6 and tried building. It failed with this_thread_id in source/system/platform.cpp. you will need minor modification in case of FreeBSD to get thread id.

`diff --git a/source/system/platform.cpp b/source/system/platform.cpp
index 092c53e..7c42aa4 100644
--- a/source/system/platform.cpp
+++ b/source/system/platform.cpp
@@ -23,6 +23,7 @@
 	#include <unistd.h>
 	#include <sys/time.h>
 	#include <sys/syscall.h>
+	#include <sys/thr.h>
 #endif
 
 namespace nana
@@ -57,7 +58,10 @@ namespace system
 #if defined(NANA_WINDOWS)
 		return ::GetCurrentThreadId();
 #elif defined(NANA_LINUX)
-		return ::syscall(__NR_gettid);
+		//return ::syscall(__NR_gettid);
+		long lcurtid;
+		thr_self( &lcurtid );
+		return static_cast<unsigned long>( lcurtid );
 #elif defined(NANA_MACOS)
 		return ::syscall(SYS_thread_selfid);
 #endif
`

**Comment by cnjinhao** [comment]
Hi, @bodomartin 
Nana now is passed using `clang` 5.0 both libc++/libstdc++. Please try the latest hotfix branch.
This bug is caused by the `clang` which defines low number for `__GNUC__` and `__GNUC_MINOR__`, Nana library detects whether the compiler supports the keyword `noexcept` through these 2 predefined marcos. Because of low number, `Nana` considered the compiler wouldn't support the `noexcept`, but `clang` actually supports it.

**Comment by coffee-lord** [comment]
@cnjinhao Have you considered leveraging CMake's [Compile Features](https://cmake.org/cmake/help/v3.8/manual/cmake-compile-features.7.html#optional-compile-features) module to do the feature detection for you? It [can test](https://cmake.org/cmake/help/v3.8/prop_gbl/CMAKE_CXX_KNOWN_FEATURES.html#prop_gbl:CMAKE_CXX_KNOWN_FEATURES) for `noexcept`

**Comment by cnjinhao** [comment]
@coffee-lord Please send a PR.
