### ISSUE TITLE
filebox throws exception when shown

### ISSUE THREAD

**Issue by Enhex** [cnjinhao/nana#191]
Trying to run the example code from:
http://nanapro.org/en-us/documentation/utilities/filebox.htm

I get unhandled exception:
`throw std::runtime_error("The revert is not allowed");`
from:
`window_manager.cpp`
caused by the example code line:
`if (fb())`

Using Windows 10 and Visual Studio 2017

Works fine with Visual Studio 2015

**Comment by cnjinhao** [comment]
Thanks for reporting issue. I will review the issue.

**Comment by Enhex** [comment]
Updated missing link to the example code

**Comment by qPCR4vir** [comment]
Hi, 
confirmed the bug and the fix seems to works.
I finally installed VS2017, see 

https://developercommunity.visualstudio.com/content/problem/31844/error-0x80004003-installing-microsoft-visual-studi.html

and now the example compile and runs ok.

**Comment by cnjinhao** [comment]
@qPCR4vir Thanks a lot for confirming this fix!

**Comment by qPCR4vir** [comment]
Every example compile OK with VC++v14.1 from VS2017 update preview. Run most of them - ok.

**Comment by Enhex** [comment]
Fix works for me too
