### ISSUE TITLE
Setting the window icon under Windows does not work.

### ISSUE THREAD

**Issue by haimat** [cnjinhao/nana#192]
I have trouble setting the window icon under Windows:

    // Called before any other nana-related function
    nana::API::window_icon_default(nana::paint::image("hunger.ico"));

There is definitely a file `hunger.ico` within the same folder as the executable, I double-checked that. That icon file is 32x32 in size (or 16x16). I also tried to retrieve the full path to the icon file, like so:

	wchar_t buffer[MAX_PATH];
	DWORD len = sizeof(buffer);
	GetModuleFileName(nullptr, buffer, len);
	std::wstring ws(buffer);
    // concatenate ws and "hunger.ico" here

But when I run the (console) application from within VS2015, the default window icon is used. Any ideas what I am missing here?

**Comment by cnjinhao** [comment]
Hi, @haimat 
Thanks for your feedback! There is an issue of using .ico file, I will fix it.
A workaround to set the icon: compile the icon into the exe as a resource, then call window_icon_default with the exe path.

**Comment by haimat** [comment]
Thanks. Any estimation when you will be able to fix that?
Also, is it possible to use another file format, like `.bmp`, or is the icon as exe resource the only workaround?

**Comment by qPCR4vir** [comment]
Hi, I added this "solution" to the original question: 
[Setting the window icon in a nana C++ GUI application](http://stackoverflow.com/questions/42965070/setting-the-window-icon-in-a-nana-c-gui-application)

Please, check if it is correct. I'm not sure:
 
I hope Jinhao will solve the problem to load the icon to a running program.

...but, I'm not sure, but if what you want is to have your .exe file even in the windows explorer ilustrated with your ico/bmp, you will need to include it into the .exe, and probably nana alone can't do that. I solved that "problem" by adding the icon as a resource to the VS project: in the Solution explorer right-click and Add... a Resource... picking an Icon, that can be New... wich launch an Icon editor from where you can import any image format to your icon. You will need the image file only at compile time, and at run time not.

**Comment by haimat** [comment]
Thanks guys, your workaround works for me.

**Comment by haimat** [comment]
Thankls @cnjinhao for your quick fix. I would like to test it, but I am using nana via `vcpkg`. Can I somehow get the latest dev version from here via that tool?

**Comment by cnjinhao** [comment]
Download the hotfix branch, replace the `include/source` folder where you installed with `vcpkg` with the `include/source` from the zip file, then recompile the lib.
