### ISSUE TITLE
Feature Request: Allow to highlight certain lines in a textbox

### ISSUE THREAD

**Issue by haimat** [cnjinhao/nana#194]
As of now the `textbox` widget allows to highlight all occurrences of specific words. It would be great to additionally also allow to highlight certain lines in the text box, regardless of the content/text in these lines.

**Comment by cnjinhao** [comment]
Hi, @haimat 
Thank you for your feedback, I will add this feature to the next release.

**Comment by haimat** [comment]
This is great, thanks a lot!  
Do you know how long it usually takes for a new `nana` release (like 1.5 now) to show up in `vcpkg`?
