### ISSUE TITLE
Unhandled exception with nana tabbas

### ISSUE THREAD

**Issue by haimat** [cnjinhao/nana#196]
I am following the "Widget show" example, in particular in the context of tab bars. So I have created the following class:

	class HungerGui : public nana::form
	{
	private:
		class AgentInfoTab : public nana::panel<false>
		{
		private:
			nana::place m_Place;
			nana::textbox m_TextBox;

		public:
			AgentInfoTab(nana::window wd) : nana::panel<false>(wd)
			{
				m_Place.bind(*this);
				m_Place.div("<textbox>");
				m_Place.field("textbox") << m_TextBox;
				m_Place.collocate();
			}
		};

		nana::tabbar<std::string> m_AgentTabs { *this };
	};

And in the constructor of that class `HungerGui`:

	// ...
	m_AgentTabs.create(*this, true);
	m_AgentTabs.push_back("Agent");
	m_AgentTabs.attach(0, *new AgentInfoTab(*this));

However, that leads to a `std::invalid_argument` exception in nana's file `place.hpp`, line 643.  
Is this a bug or am I doing something wrong?

**Comment by cnjinhao** [comment]
Hi, 
```
	class AgentInfoTab : public nana::panel<false>
	{
	private:
		nana::place m_Place;
		nana::textbox m_TextBox{*this}; //OK, the constructor of AgentInfoTab creates the panel widget.

	public:
		AgentInfoTab(nana::window wd) : nana::panel<false>(wd)
		{
			m_Place.bind(*this);
			m_Place.div("<textbox>");
			m_Place.field("textbox") << m_TextBox; //here
			m_Place.collocate();
		}
	};
```
When attachs a widget to a field, the widget must be created.

**Comment by haimat** [comment]
With `m_TextBox.create(*this);` as first line in the `AgentInfoTab` the exception is not thrown any longer.   
Thanks.
