### ISSUE TITLE
codecvt error with vs2017 community edition

### ISSUE THREAD

**Issue by wjiali6** [cnjinhao/nana#199]
according to your code in c++defines.hpp 
"only" vs2015 (_MSC_VER = 1900) got this codecvt break-any-code issue,but in my situation vs2017 (_MSC_VER > 1910 )still has it ,so it might be wiser to set this micro check to something like
	#if (_MSC_VER == 1900||_MSC_VER > 1900)  ,then, at lease , your demo code will be compiled correctly

**Comment by cnjinhao** [comment]
Thank you for reporting this issue, it has been fixed in develop branch.
