### ISSUE TITLE
Single selection listbox can display buggy selection box

### ISSUE THREAD

**Issue by ErrorFlynn** [cnjinhao/nana#204]
When holding down the left mouse button inside the bounds of a single selection listbox and then dragging the cursor past the right border of the widget, a selection box appears inside the widget that continues to be drawn once the mouse button is released. I'm using Nana 1.5 hotfix branch.

Edit: It's not necessary to press down the mouse button inside the listbox, you can do it outside the bounds of the widget, then drag the cursor inside, and then drag it past the right border. The selection box disappears if you drag the cursor past the left border. 

A multiple selection listbox also has abnormal behavior when you press down the left mouse button outside its bounds, then drag the cursor inside, and then drag it past the left or right borders.

This is not a particularly important issue, but I thought it was worth mentioning anyway.

**Comment by cnjinhao** [comment]
Thank you for reporting this bug! I'll check it.
