### ISSUE TITLE
Ctrl+A selects all items in single-selection listbox

### ISSUE THREAD

**Issue by ErrorFlynn** [cnjinhao/nana#205]
Hi, it's me again bringing you yet another listbox issue (I have a talent). As the title says, pressing Ctrl+A when a listbox has the keyboard focus selects all items, even if the listbox is single-selection. I imagine this isn't intended behavior.

**Comment by cnjinhao** [comment]
Thank you for reporting this issue, a fix has been checked into hotfix branch.
