### ISSUE TITLE
Temp directory path on Visual Studio

### ISSUE THREAD

**Issue by FirstTimeInForever** [cnjinhao/nana#209]
Why the `temp` directory is creating outside the project root? Why don't put it into the `build` directory? 
Thanks.

**Comment by cnjinhao** [comment]
Yet for no particular reason, that's just a configuration. When the library is included as one of sub modules in a "big" project, all the intermediate files of sub modules can be easy to delete in one "temp" folder.
You can change the configuration for your situation.

**Comment by FirstTimeInForever** [comment]
Ok. Thank you for the answer.
