### ISSUE TITLE
How to Create Borderless and Titleless Windows by nana?

### ISSUE THREAD

**Issue by sgf** [cnjinhao/nana#212]
nana 无边框 (自定义 不规则 边框) 怎么实现。

另外 是否有 StackPanel 之类的布局 系统呢。

另外默认的灰色窗口背景色。。。好像有点不靓丽。

**Comment by cnjinhao** [comment]
```C++
using namespace nana;
form fm{ API::make_center(300, 200), form::appear::bald<form::appear::taskbar>{} };
```
创建无标题栏，无边框的窗口。 至于不规则窗口只有自己调用系统API。

没有StackPanel。布局只有一个place类。参考
https://github.com/cnjinhao/nana/wiki/Div-Text
http://nanapro.org/en-us/documentation/utilities/place.htm

修改窗口背景色用
```C++
widget.bgcolor(static_cast<color_rgb>(0xrrggbb)); 
```

**Comment by sgf** [comment]
哦，谢谢啦，希望nana 越来越强！加油。
