### ISSUE TITLE
BUILD ERROR

### ISSUE THREAD

**Issue by ZHAIXINGZHAIYUE** [cnjinhao/nana#216]
g++ -o out/objs/gui/widgets/listbox.o -c ../../source/gui/widgets/listbox.cpp -I../../include -I/usr/include/freetype2 -I../../extrlib -g -fexceptions -std=c++11 -Wall -Wextra -Wunused-variable -Wfatal-errors
../../source/gui/widgets/listbox.cpp: In constructor ‘nana::drawerbase::listbox::cell::cell(std::__cxx11::string, const nana::drawerbase::listbox::cell::format&)’:
../../source/gui/widgets/listbox.cpp:94:21: error: ‘make_unique’ is not a member of ‘std’

linux minit 16.04
g++ --version 
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by ZHAIXINGZHAIYUE** [comment]
make c++11 to c++14 ,the problem above is solved.
there is annother error:
`/usr/bin/ld: ../build/bin/libnana.a(platform_abstraction.o): undefined reference to symbol 'FcConfigAppFontAddFile'`

**Comment by cnjinhao** [comment]
FontConfig is required to link against your binary.
make_unique is a part of C++14. If the compiler doesn't support C++14, it's OK, because library provides an implementation of make_unique. But your compiler supports it, the library provided implementation is disabled, so the make_unique would be undefined when '-std=c++11' is specified.

**Comment by ZHAIXINGZHAIYUE** [comment]
error agagin　when wxwcute compiled binary file：
｀Unable to update the static FcBlanks: 0x0600
Unable to update the static FcBlanks: 0x0601
Unable to update the static FcBlanks: 0x0602
Unable to update the static FcBlanks: 0x0603
Unable to update the static FcBlanks: 0x06dd
Unable to update the static FcBlanks: 0x070f
Unable to update the static FcBlanks: 0x2028
Unable to update the static FcBlanks: 0x2029
Unable to update the static FcBlanks: 0xfff9
Unable to update the static FcBlanks: 0xfffa
Unable to update the static FcBlanks: 0xfffb
｀
thank you.

**Comment by cnjinhao** [comment]
I've never seen the errors before. It seems not to be generated by compiler. I can't help you. Sorry.
