### ISSUE TITLE
placement系统增加直接修改某个field的功能可能会使用起来更顺手

### ISSUE THREAD

**Issue by wjiali6** [cnjinhao/nana#217]
placement系统增加直接修改某个field的功能可能会更好。
place类目前仅包含一种不是很灵活的设置placement的方法（比如用div完全替换现有的placement），本身用<>隔开不同field对于解析来说很方便但是在程序运行过程中动态调整placement似乎只能通过div重新设置一个placement，这导致如果要运行中动态调整程placement，序员需要写出解析先前的placement逻辑，如果提供一种方式直接修改某个field的方法，placement系统可能会变得使用起来更加灵活。 

_Sent from my Xiaomi MI 5s using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by cnjinhao** [comment]
我会考虑这个功能。另外 尽量用英文，可以让不懂中文的网友也能参与讨论。

**Comment by wjiali6** [comment]
好的
