### ISSUE TITLE
Copying data from a textbox

### ISSUE THREAD

**Issue by os12** [cnjinhao/nana#225]
I've written a toy program with Nana (on Windows) that shows output in a read-only `nana::textbox` widget. However, the widget does not allow selection, so I cannot grab the content via "select + copy".

Is this by design or due to an oversight? Is there something I can enable?

Thanks!

![sshot](https://user-images.githubusercontent.com/1539014/28103049-738d627e-6688-11e7-9405-b929bee507d6.png)

**Comment by cnjinhao** [comment]
`enable_caret()` enables caret when textbox is read-only.

**Comment by os12** [comment]
Thanks, that helps - I can select now.

Double-click does not work however. I'll see how hard that is to fix...
