### ISSUE TITLE
nana::inputbox does not work properly

### ISSUE THREAD

**Issue by JenioPY** [cnjinhao/nana#230]
Using code shown at [http://nanapro.org/en-us/documentation/utilities/inputbox.htm](), my results were quite different from what is shown on the example screen. To be precise the size of the widgets, especially buttons is rather not correct, I couldn't find a way to resolve this issue myself.

![image](https://user-images.githubusercontent.com/15171153/28339983-65e405d4-6c0e-11e7-8211-edd821156b95.png)

I used Visual Studio 2017 with 2017 toolset (v141) and 2015 toolset (v140).

**Comment by cnjinhao** [comment]
Hi, this bug is already fixed last weekend and a fix has been checked into hotfix branch. Thanks for reporting this issue.

**Comment by JenioPY** [comment]
Good to hear. Thanks for the response.
