### ISSUE TITLE
[Linux] boost::make_unique or std::make_unique ?

### ISSUE THREAD

**Issue by ebachard** [cnjinhao/nana#231]
Hi,

First, thanks a lot for providing such an awesome GUI library ! You did a great work, and I wish you the best.

FYI, I'm myself writing a portable application, and even if my software is well advanced, I continue to investigate, searching a portable GUI. I tested nana library sometimes ago (last year, around november), but I didn't choose it (using SDL2+imgui + cross compilation instead).  The recent changes and fix you did, convinced me to retry recently. If this can help you, I found some build issues, described below.

Using the current git repository, the build is broken on Linux Intel (x86_64) Deiban like (precisely : Mint18.1), and the log says:
    ../../source/gui/widgets/listbox.cpp: In constructor ‘nana::drawerbase::listbox::cell::cell(std::__cxx11::string, const nana::drawerbase::listbox::cell::format&)’:
    ../../source/gui/widgets/listbox.cpp:94:21: error: ‘make_unique’ is not a member of ‘std’
       custom_format(std::make_unique<format>( fmt ))
    
Workaround :
    #include <boost/make_unique.hpp>
    +
    s/std::make_unique/boost::make_unique/

=> see the attached diff, to see how I workarounded the Linux build.

Last but not least : I didn't understand how to test the examples ? 

I remind there was a lot of examples fo show the library features, but found nothing in the git repo. Did I miss something ? Thanks in advance :-)

[nana_1.5.3+.diff.txt](https://github.com/cnjinhao/nana/files/1162240/nana_1.5.3.diff.txt)

**Comment by cnjinhao** [comment]
Thank you for trying nana library, the `make_unique` issue was addressed in commit(bd5e9fdc4ab9d0f2c5ed594cbffa63ae06b9c4c9). The library has already provided a `make_unique` implementation and it will be available when use a C++11 compiler or C++14 compiler with -std=c++11. 

Without this fix, the problem can be resolved by using -std=c++14. I remember that g++ in Mint 18 supports C++14. an [explaination](http://nanapro.org/en-us/forum/index.php?u=/topic/173/ggv1-5-3-compile-problem-std-make-unique) about the issue. Thank you all the same for working on this issue.

The examples are given by [qPCR4vir's repo](https://github.com/qpcr4vir/nana-demo).
