### ISSUE TITLE
builtin support for custom application icons

### ISSUE THREAD

**Issue by wjiali6** [cnjinhao/nana#232]
Is there any built in support for customizing application icon(not window large small icons) on windows?
I have'nt found one and I did a workaround for this,override (undef and define again)IDI_APPLICATION to something like MAKEINTERRESOURCE(101) and add a rc file to my project, and add following line:
101 ICON  "icon.ico". This might be buggy but I didn't see there is any other way.

**Comment by cnjinhao** [comment]
This is a proper way to add an icon for your program. The method to custom icon depends on IDE.
