### ISSUE TITLE
runtime error with non populated combox

### ISSUE THREAD

**Issue by crillion** [cnjinhao/nana#236]
Hi, I have noticed that the presence of a (non populated) combox makes my program crash. I work with nana 1.5.4 and boost 1.64, on a windows 10/64 machine, and to compile I use mingw/w64 with gcc 7.1 Here the example program :

#include <nana/gui/widgets/combox.hpp>
#include <nana/gui/wvl.hpp>
#include <iostream>

class user_interface
{
public:			

	user_interface() :
		fm(nana::API::make_center(700, 550)),
		combox1(fm, nana::rectangle { 0, 0, 200, 50 }) // ok, combox is not populated, but can the crash be prevented anyway ?
	{
	}

private:

	nana::form fm;

	nana::combox combox1;
};

int main()
{
	user_interface interface; // the program crashes immediately
}

the compilation script for this example is the following :

g++ -pedantic -std=c++14 -Wall -Wextra -fdiagnostics-color -s program.cpp -lboost_filesystem-mgw71-mt-d-1_64 -lboost_system-mgw71-mt-d-1_64 -o test_combo_gpp.exe -I../../../../../external/nana/nana_1_5_4/nana/include -L../../../../../external/nana/nana_1_5_4/nana -lnana -I../../../../../external/boost/boost_1_64_0_build/include/boost-1_64 -L../../../../../external/boost/boost_1_64_0_build/lib -lboost_system-mgw71-mt-d-1_64 -LC:\programs\mingw-w64\x86_64-7.1.0-posix-seh-rt_v5-rev0\mingw64\lib -lgdi32 -lcomdlg32 -lstdc++fs -lKtmW32
`

**Comment by cnjinhao** [comment]
Thank you for reporting this issue, a fix has been checked into the hotfix branch.
