### ISSUE TITLE
Crash when selecting menu command using keyboard

### ISSUE THREAD

**Issue by Letschki** [cnjinhao/nana#237]
Hello,

I get a crash when selecting a menu item using the keyboard. The debugger shows the problem in
**menu_drawer::send_shortkey()**. The **menu_->owner** variable of the **menu_type** is not initialized.

If i select the menu item using the mouse everything works fine. 

Nana C++ version 1.5.4 with Visual Studio 2017.

**Comment by cnjinhao** [comment]
Thank you for reporting this issue, I will check it.

**Comment by Letschki** [comment]
Thank you for your fast reply. To be more specific the **menu_** member variable is not initialized.

menu.cpp (line 630):
...
```
else if (item_ptr->flags.enabled) 
   fn_close_tree_();
   if (item_ptr->event_handler)
   {
       item_proxy ip{ index, menu_->owner };
       item_ptr->event_handler.operator()(ip);
    }
    return 1;
}
```
...

**Comment by cnjinhao** [comment]
Fixed, Thank you for the information!
