### ISSUE TITLE
Missing fontconfig library dependency

### ISSUE THREAD

**Issue by AS383** [cnjinhao/nana#239]
When build Hello world example on ROSA Linux ld report an error: 
undefined reference to symbol 'FcConfigAppFontAddFile'. 
As I find by Google this function from fontconfig library. The hack I made to correct it is append list(APPEND NANA_LINKS -lfontconfig) to UNIX section of CMakeLists.txt.

**Comment by cnjinhao** [comment]
Thank you. A pull request is welcomed.

**Comment by cnjinhao** [comment]
The -lfontconfig shouldn't be added in the CMakefile of building Nana. Because it is linked against when compile your program.

**Comment by cnjinhao** [comment]
Fixed in the qpcr4vir's repo.
