### ISSUE TITLE
Linker Issues with extra libs (extrlib)

### ISSUE THREAD

**Issue by Letschki** [cnjinhao/nana#243]
Hallo,

(1) after updating Visual Studio 2017 to Version 15.3 i have an issue with the release build of my app:

   fatal error **C1047**: skipped german error message, here edited from the english docs:
   The object or library file '**extrlib\vc2017\libpng.MD.x64.lib**' was created with an older compiler than other objects; rebuild old objects and libraries
 
(2) Additionally i have an issue with the debug build that prevents the usage of the "Edit and Continue" feature:

The linker reports that **libjpeg.MDd.x64.lib(jerror.obj)** was compiled with the **/GL** switch and it re-linke the code with **/LTCG**.

Thanks in advance.

**Comment by cnjinhao** [comment]
The precompiled extra libs are builder with default compiler configuration. If you would link against these extra libs with specific configuration, I recommend you to download the libraries and build with specific configurations.
