### ISSUE TITLE
listbox item_proxy::select(true, true) -- incorrect scroll if "sorted content"

### ISSUE THREAD

**Issue by A2Razor** [cnjinhao/nana#245]
https://github.com/cnjinhao/nana/blob/4e425d1d8d036cf4354b918e43bfd188e82da0cc/source/gui/widgets/listbox.cpp#L2865

^ It seems that the target offset in scroll is based on the "_absolute position_" of the item, which is only correct if the control is **not** sorted.

-- This causes the listbox to jump to the wrong position rather than showing the selection, or jump all over the place if arrow-keys are used to navigate the control.

The following appears to correct this:
```
// fix make-visible scrolling when listbox contents are sorted
//auto off = this->distance(this->first(), pos) * ess_->item_height(); // <= absolute position
size_type off = widget_->at(pos).to_display().item * ess_->item_height(); // <= relative position
```

**Comment by cnjinhao** [comment]
Thanks a lot for reporting and fixing this bug. Your patch doesn't work if the scrolled item isn't in category 0.

**Comment by A2Razor** [comment]
> Thanks a lot for reporting and fixing this bug. Your patch doesn't work if the scrolled item isn't in category 0.

--Ah, guess I was fixed on my self use of the listbox (which didn't include a second category).  Didn't even think of that, but can see it'd be a problem not being offset from the correct category's start.

Will take a look at this again soon.
