### ISSUE TITLE
group has black background

### ISSUE THREAD

**Issue by dem-mb** [cnjinhao/nana#246]
Hi all,

in the nana hotfix branch between commit [930db94](https://github.com/cnjinhao/nana/commit/930db94fc26a37243dfbb249c190c40cd1e09089) and [4e18d81](https://github.com/cnjinhao/nana/commit/4e18d81f90b798dffe4e2621f382c6d28ec5cd22) the groupbox inner panel has changed to a default color of black.
Setting bgcolor and fgcolor does not change this.
Previous is was per default grey.

OS: Win7
Compiler: VS2013

Reproduction:

```
#include <tchar.h>
#include <nana\gui\wvl.hpp>
#include <nana\gui\widgets\form.hpp>
#include <nana\gui\widgets\group.hpp>

int _tmain(int argc, _TCHAR* argv[])
{
	using namespace nana;

	form frm;
	place& p = frm.get_place();
	
	std::unique_ptr<nana::group> grp = std::make_unique<nana::group>();
	grp->create(frm);
	grp->caption("abc");
	//grp->bgcolor(nana::colors::gray);
	//grp->fgcolor(nana::colors::gray);
	grp->div("<vert margin=5 items arrange=[22,repeated]>");
	grp->collocate();

	p.div("<grp>");
	p.field("grp") << *grp;
	p.collocate();

	frm.show();
	exec();

	return 0;
}

```

Please investigate.
Thank you.
mb

**Comment by cnjinhao** [comment]
Thanks for reporting this issue! Fixed

**Comment by dem-mb** [comment]
Works. 
Thank you!
