### ISSUE TITLE
listbox::column_at(index, false) -- exception thrown on accessing "invisible column" by absolute position

### ISSUE THREAD

**Issue by A2Razor** [cnjinhao/nana#248]
https://github.com/cnjinhao/nana/blob/64899a3d6a1b2776271f666b03a6bd177d430a57/source/gui/widgets/listbox.cpp#L404-L429

I'm assuming that this should be legal (accessing an invisible column by absolute position), as visibility only applies to relative (ordered) index.
[eg, for clearing the invisible-state of a column, or for testing visible() without storing the return of column_at]

-- Looks like this may just be a condition-ordering problem.
```
diff -ur 1.5.4--base/listbox.cpp proposed/listbox.cpp
--- 1.5.4--base/listbox.cpp	2017-08-25 16:11:27.737066700 -0700
+++ proposed/listbox.cpp	2017-08-29 13:04:49.014647600 -0700
@@ -408,11 +408,11 @@
 					size_type order = 0; //order for display position
 					for (auto & m : cont_)
 					{
-						if (!m.visible_state)
-							continue;
-
 						if (disp_order)
 						{
+							if (!m.visible_state)
+								continue; // skip invisible column if relative position
+
 							if (0 == pos)
 								return m.index;
 							--pos;
```

**Comment by cnjinhao** [comment]
Hi, @A2Razor 
Thanks for reporting the issue. The es_header::cast should throw an exception if convert an absolute position which item is invisible to display position. IMO the bug is caused by `es_header::at()`

https://github.com/cnjinhao/nana/blob/64899a3d6a1b2776271f666b03a6bd177d430a57/source/gui/widgets/listbox.cpp#L431-L440
```C++
column& at(size_type pos, bool disp_order = false)
{
	check_range(pos, cont_.size());

	if (!disp_order)
	{
		for(auto & m : cont_)
		{
			if(m.index == pos)
				return m;
		}
	}
					
	return cont_[pos];
}
```

**Comment by A2Razor** [comment]
@cnjinhao -- added your changes and **reverted mine** (the conditional position-swap).  Can confirm that everything is also working this way in my project.  (showing & hiding columns without exception)

Looks indeed fixed!


I'll leave the issue open till you've had time to make a commit, incase people have the same problem.

**Comment by cnjinhao** [comment]
I will make a commit, thank you a lot!
