### ISSUE TITLE
Form layout question: nana::place

### ISSUE THREAD

**Issue by os12** [cnjinhao/nana#249]
Hi there, I've put together a "calculator" form that contains an input text box, a whole bunch of output text boxes and a status bar. 

Here is the code using `div()`:
```
    layout.div(
        "<vert"
        "<input>"
        "<weight=20 <unsigned32label weight=70><unsigned32><signed32label weight=70><signed32>>"
        "<weight=20 <hex32label weight=70><hex32>>"
        "<weight=20 <hex64label weight=70><hex64>>"
        "<weight=20 <reallabel weight=70><real>>"
        "<weight=20 <realexplabel weight=70><realexp>>"
        "<<biglabel weight=70><big>>"
        "<status weight=20>>");
```
![sshot](https://user-images.githubusercontent.com/1539014/30033053-c882146a-914d-11e7-8178-cac2fb679d4b.jpg)

I am trying to figure out how to put vertical gaps between the rows and horizontal gaps between the labels and text boxes. Obviously I tried adding `gap=10` to "vert" and the individual rows, but that does not work.

What am I missing?

Thanks in advance!

**Comment by cnjinhao** [comment]
Hi, insert a "<weight=5>" between those "<weight=20...>" to vertical gaps. So do the horizontal gaps.
Another way is use margin. 
"<weight=25 margin=[0,0,5,0] <hex64label weight=70><weight=5><hex64>>"

**Comment by os12** [comment]
Oh, right, a small "padding" widget. Thanks a lot!
