### ISSUE TITLE
Dynamic linking doesn't work

### ISSUE THREAD

**Issue by Sixmorphugus** [cnjinhao/nana#250]
Hi,
I'm trying to use nana to make an editor interface, but I can't seem to dynamically link nana. Whenever I try to generate dynamic nana files, however, all I get is a lone `nana_d.dll` file with no .lib to go with it. This means nothing in the library can be used.

I've looked through the project and I can't find any use of, for example, the `__declspec` macro anywhere. Does nana not support dynamic usage? It seems I have a choice between a large `nana_d.lib` file or a useless `nana_d.dll` file, plus there's the fact that with static linking I'd have to swap out other external dependencies.

**Comment by cnjinhao** [comment]
Sorry, only static linkage is supported.

**Comment by Sixmorphugus** [comment]
Are there any plans to support dynamic linking in the future?

**Comment by frostbane** [comment]
@cnjinhao  I am currently working on the dynamic build, I will be testing it in my linux this weekend

**Comment by cnjinhao** [comment]
@frostbane good job! IMO, the key of the dynamic linking is to share the singleton data between modules(DLL or so).

**Comment by frostbane** [comment]
#265 
added modifications on the `CMakeLists.txt`
checked in windoze and debian

**Comment by imagebreaker** [comment]
@cnjinhao That may be a complex job to share data between modules across dll/so boundary.

**Comment by frostbane** [comment]
yup sharing singleton and static data will be a pain
