### ISSUE TITLE
Filebox: filesystem error when folder permissions are missing

### ISSUE THREAD

**Issue by mpecmpec** [cnjinhao/nana#251]
I am on Ubuntu and when I open a nana filebox window and click on a folder my user doesn't have permissions to view the program crashes with this message:

```
terminate called after throwing an instance of 'std::experimental::filesystem::v1::__cxx11::filesystem_error'
  what():  filesystem error: directory iterator cannot open directory: Permission denied [/lost+found]
Aborted (core dumped)

```
This also happens immediately when I click on the little triangle next to "filesystem" because apparently this first tries to open the unaccessible /lost+found folder.

**Comment by cnjinhao** [comment]
Thank you for reporting this issue. I will check it.
