### ISSUE TITLE
Calling nana::paint::graphics::resize causes a read access violation in nana::paint::graphics::make

### ISSUE THREAD

**Issue by beru** [cnjinhao/nana#253]
It seems like using std::move(*this) invalidates impl_ pointer, so dereferencing it causes the problem.
I've encountered the problem with Visual Studio 2017 (Version 15.3.3) and still haven't tested with other tools.

https://github.com/cnjinhao/nana/commit/6e86b6ae6c916951149ec564988a373b1c4fc232#diff-e46bacf66392743e6c4235fe9f221b04R365

**Comment by cnjinhao** [comment]
Thank you for reporting this issue!
