### ISSUE TITLE
textbox.linewrap segmentfault

### ISSUE THREAD

**Issue by dft2000** [cnjinhao/nana#254]
有数据时:
执行函数：pre_calc_line
到这一句报错，
auto & mtr = linemtr_[line];
mtr.take_lines = line_sections.size();
mtr.line_sections.swap(line_sections);
此处mtr  并非有效的数据，下面继续执行抛出段错误
数据为空时：
_mtr.line_sections.clear();_
到这一句报错
debug mtr  nodataset
Example:
Simple Notepad

编译环境是tdm-gcc492,IDE code::blocks

**Comment by cnjinhao** [comment]
Thanks for reporting the issue! Fixed
