### ISSUE TITLE
textbox::set_accept is misbehaving with DEL key

### ISSUE THREAD

**Issue by Itaros** [cnjinhao/nana#259]
Passed wchar_t argument is 46 which is the same for '.'. Allowing 46 to pass to enable DEL renders it possible to print dots in the field as well.

Version: Nana-1.5.4

```
textbox fAmountInput;
fAmountInput.create(fForm);
fAmountInput.multi_lines(false);
fAmountInput.set_accept([](wchar_t text){
    //Why dot character and DEL have the same code???
    return text == '\b' || text == 46 || iswdigit(static_cast<wint_t>(text));
});
```

At first I wanted to ask on the forum if this behavior is intentional and if there are other tools available to address that properly instead, but registration says that my email is invalid. Come on.

**Comment by cnjinhao** [comment]
Thanks for reporting this issue! Fixed.
