### ISSUE TITLE
nana::msgbox does not take wide char string

### ISSUE THREAD

**Issue by tim37021** [cnjinhao/nana#260]
There are some inconsistency in the API call.

    msgbox msg("訊息");
    msg << L"儲存至test.png";
    msg.show();

"The text is not encoded in UTF8: 訊息"

However, I cannot pass L"訊息" to the constructor.

**Comment by cnjinhao** [comment]
`msgbox msg(to_utf8(L"訊息"));`
or
`msgbox msg(u8"訊息");`

**Comment by tim37021** [comment]
yes, but other widgets like button do not need thee explicit conversion.

**Comment by cnjinhao** [comment]
u8 prefix is preferred.  wstring version overloading is not necessary, it's just for convenience on Windows.
