### ISSUE TITLE
Access violation when exiting by shorcut

### ISSUE THREAD

**Issue by flriancu** [cnjinhao/nana#261]
Hello,

I have the following code:

<pre>
#include "nana/gui.hpp"
#include "nana/gui/widgets/menubar.hpp"

using namespace nana;

class DerivedForm : public form
{
private:
	menubar menubar{ *this };

public:
	DerivedForm() : form(API::make_center(1280, 720))
	{
		makeMenus();
	}

private:
	void makeMenus()
	{
		menubar.push_back("&File");
		{
			auto func_exit = [this](menu::item_proxy&)
			{
				close();
			};
			menubar.at(0).append("E&xit", func_exit);
		}
	}
};

int main(void)
{
	DerivedForm fm;

	fm.show();
	exec();

	return 0;
}
</pre>

Version: 1.5.5
Toolchain: VS 2013 with update 5
OS: Windows 10 build 15063
Tested: on x64 and x86, in Debug and Release modes.
Description: the code fails when I press **Alt + f, x** (when I exit by keyboard), when the `close()` function is accessed. The breakpoint indicates it has to do with the `exec()` function. It does not fail when I press "exit" by mouse.

Am I doing something wrong?

**Comment by cnjinhao** [comment]
Thank you for reporting this issue!
