### ISSUE TITLE
3rd party extensions (libpng, libzlib, libjpeg) in VC2017 built with older compiler

### ISSUE THREAD

**Issue by lkalam** [cnjinhao/nana#264]
The latest Visual Studio 2017 is now complaining that the static libraries that you have provided were created with an older compiler than other objects and need to be rebuilt. 

This started after VS2017 15.2.something if I am not mistaken.

Could you please update your Visual Studio 2017 to the latest compiler and build them again?

Thank you!

**Comment by cnjinhao** [comment]
Fixed! Only x64 libs are provided.
https://sourceforge.net/projects/nanapro/files/extrlib/VC2017v15.3/
