### ISSUE TITLE
bug: menu and tooltip in some corner in secound display.

### ISSUE THREAD

**Issue by qPCR4vir** [cnjinhao/nana#27]
Hi,
When I attach a second display  to my laptop and make it the principal display all work OK. 
But if the attached display is secondary when my nana program is there, the tooltip and menus open in different wrong place.
Other programs run OK.
I was thinking this is a new problem, but not. All my old executable have the same problems, just that I always used the attached display as principal.
I use Windows 7 pro x64

**Comment by cnjinhao** [comment]
Please let me know the steps to reproduce this issue. Does that mean the tooltip may display out of screen?

**Comment by qPCR4vir** [comment]
Hi, 
no, not out of the screen, but near the border, far from the menu.
Compile your notepad example, or anything with a menu. 
![menu display error](https://cloud.githubusercontent.com/assets/1911982/6888633/6d474542-d684-11e4-8d50-2154a8e8d532.png)

The laptop (1) have a big monitor (2) attached, and this big monitor is secondary. When I set the big monitor as principal all works OK.

**Comment by qPCR4vir** [comment]
(the figure is an approximate fake because I can not shoot  the menu)

**Comment by cnjinhao** [comment]
This issue was fixed, the fix has been checked into the hotfixes branch. Thank you!

**Comment by qPCR4vir** [comment]
I had the problems. But following your changes I finded one more fix #33
