### ISSUE TITLE
ASCII code is wrong when pressing keys

### ISSUE THREAD

**Issue by flriancu** [cnjinhao/nana#274]
Hello,

I have the following `f.events().key_press(func_keys);` where f is `nana::form`.
The callback is `auto func_keys = [this](const arg_keyboard& arg) { ... };`

When I display `arg.key`, it does not give the correct ASCII code for all keys. For example:
`-` gives 189 (should be 45)
`=` gives 187 (should be 61)
etc.

I have version 1.5.5.
Am I doing something wrong?

**Comment by cnjinhao** [comment]
`key_press`&`key_release` don't translate the keys into characters, please use `key_char` instead

**Comment by flriancu** [comment]
Sorry for misunderstanding. You can close this issue. :)
