### ISSUE TITLE
only static widgets can put to place?

### ISSUE THREAD

**Issue by cwyyprog** [cnjinhao/nana#275]
the code below not works as expected, after the add file button get clicked and choosen a file, the label do not shows. 
```cpp
int main()
{
	using namespace nana;
	form fm;
	//It's unnecessary to specify a rectangle if useing
	//layout management.
	label lb1{ fm, u8"l1" }, lb2{ fm,u8"l2" }, lb3{ fm, u8"l2" }, lb4{ fm, u8"l3" };
	lb1.text_align(nana::align::center, nana::align_v::center);
	lb2.text_align(nana::align::center, nana::align_v::center);
	lb3.text_align(nana::align::center, nana::align_v::top);
	lb4.text_align(nana::align::center, nana::align_v::center);
	place layout(fm);
	button bt2{ fm ,u8"add file" };
	layout.div("<l4_1 vert gap=2>");
	std::set<std::string> attachments;
	layout["l4_1"] << bt2;
	bt2.events().click([&] {
		nana::filebox fb(true);
		if (fb()) {
			//attachments.insert(fb.file());
			nana::label tmp{ fm, fb.file() };
                       //static nana::label tmp{ fm, fb.file() };   // this line works,  but can only add one file
			layout["l4_1"] << tmp;
			layout.collocate();
		}
	});
	layout.collocate();
	fm.show();
	exec();
}
```
I thought the code above should work due to the right value reference of cpp 11, is this a bug, or i was wrong on the usage of right value reference?

**Comment by qPCR4vir** [comment]
Hi,
I don't like very much your use of a local object `tmp` that will be destroyed immediately. I would better find a way to keep it alive all the time it is espected to be on the screen (defining it in main, for example). Nana is not exactly like Qt that create objects with new and keep the pointer with the parent object... I think. We have more c++ -like rules about that.

**Comment by qPCR4vir** [comment]
That said, I'd like to help you more specifically. What do you mean with 

> wrong on the usage of right value reference ?

just I think that whatever kind of reference the `<< tmp` keep into the place, it is going to be a dangling one, because `tmp `go out of scope. Temporary objects are kept alive by references when they are returned from a function, not when they are passed as an argument to a function, and saved as a reference somewhere else. Dangling references are still a problem in any c++.

**Comment by cwyyprog** [comment]
I know the tmp will be out of scope after the if block, but nana overides the operator method <<  to  put widgets into fields of a place, naturally it should works as same as std::cout.  The std::cout only use the value of tmp, no matter how the tmp value changes after <<.

**Comment by cnjinhao** [comment]
`std::cout` dumps a copy of content of a object, `place` refers to a specified widget. They have different sematics. Though the `field` of `place` overrides the operator<<, it doesn't mean that it has to work as same as `std::cout`. For example, operator<<(ostream& os, T t) doesn't work as same as  int<<int.

**Comment by cwyyprog** [comment]
so when dealing with dynamic contents, it's the callers' reponsibilty to allocate/free a widgets in head.

**Comment by cwyyprog** [comment]
I'am trying to use smart ptrs to help manages dynamic widgets now.

**Comment by qPCR4vir** [comment]
Example:
https://github.com/qPCR4vir/nana-demo/blob/master/Examples/group.cpp#L45

**Comment by qPCR4vir** [comment]
The point is that **_normaly_** '`place`' don't owns the widgets (not even a copy of then), it only dinamically layouts the widgets of the parent windows following the rules of the div-str. But if you are willing to experiment with advanced functions, then you can tell the 'place' to own the widget using an 'agent': https://github.com/cnjinhao/nana/blob/master/include/nana/gui/place.hpp#L56

But if what you really want is to put a very simple label owned by the `place`, then `place `support that directly:

	bt2.events().click([&] {
		nana::filebox fb(true);
		if (fb()) {
			layout["l4_1"] << fb.file();
			layout.collocate();
		}
	});

See: https://github.com/cnjinhao/nana/blob/master/include/nana/gui/place.hpp#L92
