### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by KingDuckZ** [cnjinhao/nana#277]
I'm just trying the "hello world" tutorial, but I'm getting a few errors. The first one is that the c++14 standard is not inherited by my cmake project when I link to nana. To fix that I removed the explicit -std options from the cmake file as well as the CXX_STANDARD property (I don't know if there's a way to make that a public property so it would get inherited) and replaced it with:

    target_compile_features(${PROJECT_NAME}
        PUBLIC cxx_nullptr
        PUBLIC cxx_range_for
        PUBLIC cxx_lambdas
        PUBLIC cxx_decltype_auto
        PUBLIC cxx_defaulted_functions
        PUBLIC cxx_deleted_functions
        PUBLIC cxx_auto_type
        PUBLIC cxx_decltype_incomplete_return_types
        PUBLIC cxx_defaulted_move_initializers
        PUBLIC cxx_noexcept
        PUBLIC cxx_rvalue_references
    )

this got me past the first problem and I'm wondering if this couldn't help with issue #269 as well?

The second problem is a linker error:

/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: lib/nana/libnana.a(platform_abstraction.cpp.o): undefined reference to symbol 'FcConfigAppFontAddFile'
/usr/lib64/libfontconfig.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

which I'm looking into right now.

**Comment by Mizux** [comment]
Seems to be defined by FontConfig
src: https://gitlab.freedesktop.org/fontconfig/fontconfig/blob/master/fontconfig/fontconfig.h#L448

Which version do you use ?

**Comment by qPCR4vir** [comment]
I'm preparing a PR for that and more: https://github.com/qPCR4vir/nana/commit/de2ec3928da7cbe9589db36f7406cd1fda7baa67

Cold you test my new version of [CMakeLists.txt](https://github.com/qPCR4vir/nana/blob/CMake/CMakeLists.txt) ?

**Comment by qPCR4vir** [comment]
hi @KingDuckZ ,
It is my bad and a shame that I didn't saw this PR and your explanation a year ago. More exactly, I probably read it but I was unprepared for it and just ignore it. Sorry. By trying to fix by myself the problems I kome back here to see that you have alrready pointed to most of what I was using and a few more.
I think now left only to use the Boosr::boost thing, but a got some problem and I have read that some time Boost go to fast for cmake and one need to use the other aproach.
I hope you will keep helping.
Thank!

**Comment by qPCR4vir** [comment]
The cmake build system need to be improved further, but the related PR was merged and most problems from this issue were solved I think (not sure about the font problem), and can be closed.
