### ISSUE TITLE
preformance issue with textbox

### ISSUE THREAD

**Issue by wjiali6** [cnjinhao/nana#280]
Profiling shows that there are mulptiple preformance issues with textbox implementation, some seem due to completely useless (seems) ,a lot of them calls one specific function
void pre_calc_line(std::size_t pos, unsigned) override
from text_editor.cpp line 671
(.......\cnjinhao\nana\source\gui\widgets\skeletons\text_editor.cpp)
I don't see anything useful from this function ,can it be elininated ?
BTW, I load a 14M gbk(after read into memory decoded to Windows UCS2 encoding) text file to a textbox object, the profiling shows that pre_calc_line takes about 65%~75% of whole loading process.

The following is code snips which do the work:

#define  Timing(now,end,diff,expression ,buffer,workname)     \
now= std::chrono::system_clock::now();\
expression; \
end= std::chrono::system_clock::now();\
diff = end-now;\
swprintf(buffer,L"%s tooks \t%lld ms\n",workname,std::chrono::duration_cast<std::chrono::milliseconds>(end-now).count()); \
OutputDebugString(buffer);
__inline static void toUSC2(const std::string & str,std::wstring& wstr)
{
    TCHAR BUFFER[200];
    ZeroMemory(BUFFER, sizeof(TCHAR) * 200);
    auto size = ::MultiByteToWideChar(CP_ACP, 0, str.c_str(), str.size(), nullptr, 0);
    wstr.resize(size);
    size = ::MultiByteToWideChar(CP_ACP, 0, str.c_str(), str.size(), const_cast<wchar_t*>(wstr.data()), size);
    if (!size)
    {
        swprintf_s(BUFFER, L"error,%d", HRESULT_FROM_WIN32(GetLastError()));
        OutputDebugString(BUFFER);
    }
}

void tbsinak::_loadfile2()
{
    using Type = decltype(std::chrono::system_clock::now());
    Type now;
    Type end;
    std::chrono::duration<double> diff = {};
    wchar_t buffer[200] = {};
    std::ifstream in("dummy.txt");
    auto const start_pos = in.tellg();
#undef max
    in.ignore(std::numeric_limits<std::streamsize>::max(),-1);
    auto const char_count = in.gcount();
    in.seekg(start_pos);
    auto s = std::string(char_count, char{});
    // or std::vector<char>(char_count);
    // or you can use unsigned char or signed char
    in.read(&s[0], s.size());
    std::wstring wstr(L"", 0);
    memset(buffer, 0, sizeof(wchar_t) * 200);
    Timing(now, end, diff, toUSC2(s,wstr), buffer, L"reencoding");
    memset(buffer, 0, sizeof(wchar_t) * 200);
    Timing(now, end, diff, this->tb.append(wstr, false), buffer, L"append to textbox");
}

**Comment by wjiali6** [comment]
Is there anything I could help?
If I comment out  _m_reset_content_size(true)(whick is responsible for calling pre_calc_line(std::size_t pos, unsigned) )  from text_editer
....\Githubs\cnjinhao\nana\source\gui\widgets\skeletons\text_editor.cpp
 line 2016,nothing shows on textarea, It looks like this method dose have something to do with visual line width( or length,whatever you call it),but I can't get I picture of it

**Comment by cnjinhao** [comment]
The pre_calc_line measures the text extent size of a line. If the text box is line-wrapped, it also calculates the number of visual lines that a long width text line takes.
