### ISSUE TITLE
Can I emit custom messages to main thread

### ISSUE THREAD

**Issue by wjiali6** [cnjinhao/nana#282]
In a multithreaded application (on Windows) I'd like to use Windows message queues to send messges to other threads , is it posible with nana using this kind of machenisim? Like ,can I emit a custom message to 
to main thread and specify a handler to handle it ?

**Comment by cnjinhao** [comment]
Nana doesn't provide method to access windows message queue. You can access the windows message queue through sub-classing tech. There is a helper class for subclassing

https://github.com/qPCR4vir/nana-demo/blob/master/Examples/windows-subclassing.cpp

**Comment by wjiali6** [comment]
Is basic_event class template thread-safe ? I find it  provides every functionality I'm going to use ,the only thing I need to do is making sure it is thread safe and provide it custom arg_complete.

**Comment by cnjinhao** [comment]
Yes, it is thread-safe.
