### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by Unitrunker** [cnjinhao/nana#287]
I have nana working on FreeBSD 11.1 (x64) using LLVM / clang 4 and X11. This includes primitive audio support to /dev/dsp.

I just read the instructions to do such work from Develop. Once I have re-based the code from Master to Develop, I will submit a pull request - likely in a week or two. Meanwhile - the code is here:

https://github.com/unitrunker/nana

The branch largely involves work on how NANA_LINUX, NANA_MACOS, and NANA_POSIX are used. 

The master branch code uses the following pattern:
#ifdef NANA_WINDOWS
// windows stuff
#elifdef NANA_LINUX
// linux stuff
#elifdef NANA_MACOS
// max stuff
#endif

In many cases, the Mac and Linux (and BSD) cases were the same.
I've adopted the following pattern where POSIX behavior for Linux, Mac and BSD overlap.

#ifdef NANA_WINDOWS
// windows stuff
#elifdef NANA_POSIX
// common Linux, Mac and BSD stuff
#endif

If a platform needs special handling (this example is MacOS) ...

#ifdef NANA_WINDOWS
// windows stuff
#elifdef NANA_MACOS
// Mac only stuff
#elifdef NANA_POSIX
// common Posix stuff
#endif

The master branch code assumes a thread handle fits inside an 'unsigned'. This did not work for me so I have promoted a typedef 'thread_t' as unsigned long. Thread ID variables are now 'thread_t' (which had already been done privately inside an existing class). This works for pthread_t and should be fine for <windows.h> HANDLE.

Getting feedback now will help me to create a clean pull request.

**Comment by Unitrunker** [comment]
I found a bug in unicode handling. The nana posix code assumes iconv returns native endian unicode. It does not.

Try this out:

static void unittest()
{
    iconv_t handle = iconv_open("UTF-32LE", "UTF-8");
    if(reinterpret_cast<iconv_t>(-1) != handle)
    {
        char buf[] = {'A', '\0'};
        size_t len = 1;

        char * inbuf = const_cast<char*>(buf);
        size_t outlen = (len * 4 + 4);
        char * strbuf = new char[outlen + 4];
        char * outbuf = strbuf;
        size_t outleft = outlen;
        ::iconv(handle, &inbuf, &len, &outbuf, &outleft);
        std::string rstr(strbuf, outbuf);
        delete [] strbuf;

        for (size_t i = 0; i < rstr.size(); i++)
        {
            std::cout << std::hex << (int)rstr[i] << std::endl;
        }
        iconv_close(handle);
    }
}

If I change "UTF-32LE" to "UTF-32", I get the wrong values for a 64 bit Intel processor.

Hint: using "UTF-32" causes nana to crash on FreeBSD x64.

Also, by specifying "LE", I can avoid the unwanted byte marker. I am looking at introducing NANA_UNICODE as a way to manage big/little endian.

**Comment by cnjinhao** [comment]
Thank you for the contribution!

**Comment by qPCR4vir** [comment]
> I have nana working on FreeBSD 11.1 (x64) using LLVM / clang 4 and X11. 

Great !   
And... do you know how to add clang to travis?

**Comment by Unitrunker** [comment]
I do not but I see a few clues here:
https://docs.travis-ci.com/user/languages/c/

matrix:
  include:
    # works on Trusty
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

before_install:
    - eval "${MATRIX_EVAL}"
