### ISSUE TITLE
Cross-compiling to Windows on Linux is broken without mingw-std-threads 

### ISSUE THREAD

**Issue by dnso86** [cnjinhao/nana#295]
https://github.com/cnjinhao/nana/blob/a653a7a3fa6de698b67693bbe66e8bdeed5507f7/include/nana/c%2B%2Bdefines.hpp#L225

Hi there, this change broke my makefile for cross-compiling Nana with MinGW - perhaps we should give this a second thought? I totally want to use Boost::thread, without changing anything in this file. :)

**Comment by qPCR4vir** [comment]
Hi, coming from [here](https://github.com/cnjinhao/nana/commit/252b8cbf650eea663b35d6198e1127f6d8562cd3):

> I need some help to understand what you mean.
You are in Linux using MinGW to create windows binaries, and your MinGW dont have std-threads, so you want to use something else for threads. Ok?
Let me know where I'm wrong:
`#ifdef NANA_MINGW` is true, and `STD_THREAD_NOT_SUPPORTED` will be defined.
`#  if __has_include(<mutex>)` is false and  `STD_THREAD_NOT_SUPPORTED` is defined.
With `STD_THREAD_NOT_SUPPORTED` defined nana will pick some other implementation, not the std.
IF there is a problem and you see how to fix it, tell me or make a PR and we will fix it in the repository.
Thank

Now I understand you want to force nana to use Boost::thread. 
We will need to to add something like `BOOST_FILESYSTEM_FORCE` in [filesystem](https://github.com/cnjinhao/nana/blob/master/include/nana/filesystem/filesystem.hpp#L52) and [CMakeLists](https://github.com/cnjinhao/nana/blob/master/CMakeLists.txt#L57) if using cmake, to modify [nana/std_thread](https://github.com/cnjinhao/nana/blob/master/include/nana/std_thread.hpp#L5) to force execution of [#include <boost/thread.hpp>](https://github.com/cnjinhao/nana/blob/master/include/nana/std_thread.hpp#L15)

**Comment by dnso86** [comment]
Hi qPCR4vir, thanks for the answer! Yes, I want to force Nana to do that, but before that change which I pointed out, it worked correctly for cross-compilation. Let me look into this tomorrow. Also, I would be glad to do the PR for this.

**Comment by dnso86** [comment]
So, I looked into my project:

- The `mutex` header is present at `/usr/lib/gcc/i686-w64-mingw32/6.3-win32/include/c++/mutex` as a part of the respective Debian package
- though `_GLIBCXX_HAS_GTHREADS` is not defined, therefore even though the `mutex` header is present, std::threads won't work - see https://github.com/gcc-mirror/gcc/blob/master/libstdc%2B%2B-v3/include/std/mutex
- Since `c++defines.hpp` expects std::thread to work if the header is available, the cross-compilation fails.

`i686-w64-mingw32 -v` gives `Thread model: win32`

I hope it makes more sense now. In my opinion, a quick fix would be just to look at `_GLIBCXX_HAS_GTHREADS` too before undefining `STD_THREAD_NOT_SUPPORTED`. Shall I do a PR for that?

**Comment by qPCR4vir** [comment]
Yes, if you have the changes and had tested in your system, please do a PR to branch cnjinhao/hotfix-1.5.6. I can only test that it don't brake windows builds or travis CI.

**Comment by dnso86** [comment]
As agreed, a change was proposed against the hotfix-1.5.6. branch.
