### ISSUE TITLE
Let the parameter of nana::place::div be a string/string_view

### ISSUE THREAD

**Issue by rbrugo** [cnjinhao/nana#298]
Hi!
It would be very handy let the `div_text` be a `const std::string &` or a `std::string_view`.
For now the only way to use a dynamically generated `div_text` is by calling the `::c_str()` method, and it would be nice to have an overload to skip this step.

**Comment by qPCR4vir** [comment]
Actually just `std::string` may be the best solution. Copy by value (or move) and then move that parameter into the internal `string div_text` that keep a copy of the current `div` . We may espect that in the new C++17 version of nana we will have many API change to use `sdt::string_view`.

**Comment by cnjinhao** [comment]
We now have a C++17 branch for C++17 works, any feedback and PR for the branch are welcomed.
