### ISSUE TITLE
Move environment detection to cpp files

### ISSUE THREAD

**Issue by qqiangwu** [cnjinhao/nana#30]
In CMakeLists.txt, we detect environment and copy them into config.hpp. 

In fact, we can use some compiler detection libraries(such as boost/predef) to do this job. We can easily detect compiler versions in cpp files.

eg.

```C++
#if defined(__MINGW__) && __GNUC_MINOR__ < 8
#define   NANA_THREAD_NOT_SUPPORTED
#endif
```

**Comment by Pr0curo** [comment]
as with the new gcc (5.1) the expression `#if defined(__MINGW__) && __GNUC_MINOR__ < 8` would be true, but, it's not what we want.
i guess adding `&&__GNUC__ < 5` should work (not tested)
