### ISSUE TITLE
Outdated Documentation

### ISSUE THREAD

**Issue by tim37021** [cnjinhao/nana#304]
I'm one of the TAs of Programming Language this semester. I would like to assign a homework for practicing cmake and promote nana GUI library at the same time .

However, I found that the documentation is a bit outdated. for example, the following code cannot been compiled by VS2017.

`msgbox(fm, L"Form closing").icon(msgbox::icon_information)<<L"The form is closing now"`

I should change L"" string literal to u8"" string literal for it to be compile successfully. I am afraid that my student will encounter some problem

**Comment by qPCR4vir** [comment]
Thank for reporting !
Where did you find this?
Yes, it is old. Just eliminate the `L`

**Comment by qPCR4vir** [comment]
I did not find a page for msgbox here:
https://github.com/cnjinhao/nana-refman/tree/master/en-us/content/utilities

It will be great if a page in the documentation could include a link to the github file people could edit directly to contribute

**Comment by cnjinhao** [comment]
Thanks for your feedback! I will create new doc for it.

**Comment by cnjinhao** [comment]
fixed.
