### ISSUE TITLE
spinbox does not support select bool

### ISSUE THREAD

**Issue by g4jc** [cnjinhao/nana#314]
A useful feature of the textbox is that you can run "select(true)" to highlight the text. This does not appear to be possible with the spinbox, and would be a nice feature to have.

As Per:
https://qpcr4vir.github.io/nana-doxy/html/de/d10/classnana_1_1textbox.html
    void 	select (bool)
 	Selects/unselects all text.

Yet: https://qpcr4vir.github.io/nana-doxy/html/d7/d43/classnana_1_1spinbox.html
 error: ‘class nana::spinbox’ has no member named ‘select’
      spbox.select(true);

**Comment by cnjinhao** [comment]
Thanks for your feedback! A new commit has been checked into develop branch for this feature.
