### ISSUE TITLE
Treebox double click & Can't log into forum

### ISSUE THREAD

**Issue by dudztroyer** [cnjinhao/nana#315]
Hey @cnjinhao , I cant log into the forum, it does not display the login button neither the fields to type login information. My user over there is eduardoroeder.

So I'll post here a thing I've got into:

I've got a treebox with 3 events: mouse_up (parses right clicking based on current selected item), selected(parses the selection changed) and dbl_click(which should parse a double click on individual items).

The dbl_click does not have an parser for individual items, so I use 

````
	SettingsTree.events().dbl_click([&](const nana::arg_mouse& arg) {
		if (arg.is_left_button() && !arg.propagation_stopped())	{
			arg.stop_propagation();
			if (!MainForm_SettingsTree->selected().empty()) {
				std::string thisNodeLocation = p->cSettings->ParseXPath(MainForm_SettingsTree->make_key_path(MainForm_SettingsTree->selected(), "/"));
			}
		}
	}

````

thisNodeLocation gives me the XPath to the location I want. But, whenever I double click on the expand/colapse box, the double click also triggers. No problem. The thing is that if anything is selected in a child node, that child node double click is triggered.

https://upload.wsbot.net/files/WSBot_2018-05-26_20-56-33.png -> When it is a bool, double clicking toggles it's value. 
https://upload.wsbot.net/files/WSBot_2018-05-26_20-57-09.png -> Toggled value

If I double click the [-] in the Targeter whie Status is selected, the Targeter node does not get selected, it does indeed collapse (just collapse instead of collapsing and expanding[should do bot, since it is a double click]) but the Status get toggled(even tho Targeter is collapsed).

How can I filter thru this events to avoid activating in double click?

Thanks

**Comment by cnjinhao** [comment]
Thanks for your feedback! The forum login issue is fixed.
Do you mean the `Status` should be still selected when double clicks the [-]?

**Comment by dudztroyer** [comment]
No. I meant that whenever I double click the [-] or [+] it sends double click event to the treebox, causing to trigger the double click event to the selected node. Note that it does not select the node with the "expander" which has been double click, leaving the node who was selected before, selected. 

You can reproduce it just adding that double click event with a message box to check what element is getting the event...
