### ISSUE TITLE
Listbox behavior changed in 1.6.0 vs 1.5.6

### ISSUE THREAD

**Issue by milchdose** [cnjinhao/nana#317]
Hi jinhao,
very nice widget-class.
Is this a bug?
If listbox-header is wider then window, the listbox is complete black.
A little example:

/*
mingw 4.92   Compiler-Options   -std=c++11
Add library  libnana.a  gdi32 comdlg32
*/

#include <nana/gui/wvl.hpp>
#include <nana/gui/widgets/form.hpp>
#include <nana/gui/widgets/listbox.hpp>

using namespace nana;

class popnana : public form
{
typedef popnana CLASSNAME;
public:
    listbox lbox {*this};
    place plc {*this};
	popnana(); // Constructor

};

popnana::popnana()
{
    plc.div("< margin=[4,2,4,2] feld1 >");
    plc.field("feld1") << lbox ;
    plc.collocate();

    lbox.append_header( "col1",110);
    lbox.append_header( "col2",80);

    lbox.at(0).append({std::string("Hello1"), std::string("Hello2") });
    lbox.at(0).append({std::string("Hello3"), std::string("Hello4") });
}

int main()
{
   popnana fm;
   fm.caption("Listbox Test");

   nana::size fmsz(100,120); // Window-width less than listbox-header-width
   fm.size(fmsz);
   API::track_window_size(fm, fmsz, false); // minimal Size

   fm.show();
   exec();
}
 

In nana-version 1.5.6 the behavior was OK.
maybe correction in next version?
thanks for your toolset

**Comment by cnjinhao** [comment]
Thanks for your feedback! I compiled the program using VS2017, it works correctly. But it behaves like you mentioned when I compiled it using GCC on Linux. I will check it out.
