### ISSUE TITLE
Error message displayed with modal window code.

### ISSUE THREAD

**Issue by beru** [cnjinhao/nana#32]
nana displays below message with `MessageBoxA`.
```
---------------------------
Nana C++ Library
---------------------------
Nana.GUI detects a memory leaks in events operation, 1 event(s) are not uninstalled.
---------------------------
OK   
---------------------------
```

Below are the code to reproduce.
```
#include <nana/gui.hpp>

int main()
{
	using namespace nana;
	
	form fm(API::make_center(300, 300));
	fm.events().click([&](const arg_mouse& arg){
		msgbox mb(fm, L"test", msgbox::ok);
		mb.icon(mb.icon_question);
		mb << L"Test";
		mb.show();
	});

#if 0
	fm.show();
	exec();
#else
	fm.modality();
#endif
}
```

Typically top level root window doesn't need to be shown with `modality` method, but I switched non-top-level window to be top-level-window for testing purpose (I wanted to skip tedious operations to open child form during testing).

And I wish the messages will be displayed in output window. The error message is displayed on  MessageBox in debug & release build but that makes end-user be causcious of the inner problem.

**Comment by cnjinhao** [comment]
Hi,
Thank you for reporting this issue. The issue was fixed. The "leaked" event will be deleted after the prompting. In fact, it is unnecessary to check the leaks of event. The fix has been checked into the hotfixes branch.

**Comment by beru** [comment]
Thank you for fixing the issue. I confirmed the message is no more with hotfixes-1.0.1 branch.
