### ISSUE TITLE
nana::listbox::scroll not scrolling to correct location

### ISSUE THREAD

**Issue by Diltsman** [cnjinhao/nana#322]
Given the following code, I would expect that the number 99 would be scrolled into view.  The number 98 is scrolled into view, but not the number 99.  All other values passed as a scroll index that I have tried work correctly.

I am running on Windows 7 and compiling with VS2015 Update 3.  I am using Nana 1.6.1.

    #include <iterator>
    #include <nana/gui/wvl.hpp>
    #include <nana/gui/widgets/listbox.hpp>
    #include <numeric>
    #include <vector>
    
    int ValueTranslator(std::vector<nana::listbox::cell> const &cells)
    {
        return std::atoi(cells[0].text.c_str());
    }
    
    std::vector<nana::listbox::cell> CellTranslator(int const &i)
    {
        std::vector<nana::listbox::cell> value;
        value.emplace_back(std::to_string(i));
        return value;
    }
    
    int main(int argc, char *argv[])
    {
        nana::form fm;
        nana::place plc{ fm };
        plc.div("<abc><def>");
    
        nana::listbox l1(fm);
        nana::listbox l2(fm);
        plc["abc"] << l1;
        plc["def"] << l2;
    
        l1.append_header("Name");
    
        std::vector<int> m(100);
        std::iota(std::begin(m), std::end(m), 0);
    
        l1.at(0).model<std::recursive_mutex>(m, ValueTranslator, CellTranslator);
    
        fm.show();
        plc.collocate();
    
        l1.scroll(false, nana::listbox::index_pair{ 0, 99 });
    
        nana::exec();
        return 0;
    }

**Comment by cnjinhao** [comment]
Thank you for reporting this issue. A fix has been checked into the `hotfix` branch.
