### ISSUE TITLE
Large Listbox Not Scrolling Correctly

### ISSUE THREAD

**Issue by Diltsman** [cnjinhao/nana#324]
Given the following code, when compiled against 1.6.1 or the latest hotfix, Use the scrollbar to scroll down.  The values start back at a lower value about a third of the way down.  If the mouse button is released while lower numbers are displayed than expected, then the scrollbar location jumps to the appropriate location for those numbers.  If the constructor argument for the `nana::form` is removed, then the listbox works as expected.

    #include <nana/gui/wvl.hpp>
    #include <nana/gui/widgets/listbox.hpp>
    #include <numeric>
    #include <vector>
    
    std::vector<nana::listbox::cell> cellTranslator(int const &i)
    {
        std::vector<nana::listbox::cell> value;
        value.push_back(std::to_string(i));
        return value;
    }
    
    int main(int argc, char *argv[])
    {
        nana::form fm{ nana::API::make_center(1300, 600) };
        nana::place plc{ fm };
        plc.div("<list>");
    
        nana::listbox lb{ fm };
        lb.append_header("");
        plc["list"] << lb;
    
        std::vector<int> data(1'000'000);
        std::iota(std::begin(data), std::end(data), 0);
    
        lb.at(0).shared_model<std::mutex>(data, cellTranslator);
    
        plc.collocate();
        fm.show();
    
        nana::exec();
    
        return 0;
    }

**Comment by cnjinhao** [comment]
Thank you for reporting this issue!
