### ISSUE TITLE
Unknown progress bar freezed

### ISSUE THREAD

**Issue by qPCR4vir** [cnjinhao/nana#325]
It works only for a few secounds and stops. Interesting, when I click another tab it continue another few sec. The known bar works normally all the time.
Compiled the develop nana (with hotfix-1.6.1 merged today) and nana-demo develop branch. (and with hotfix too)
MSVC-2017 (v15.7.1) VC++14.1
examples: widget_show2_v141_Release_x64 and debug, and widget_show_v141_Release_x64 and debug.
The previous version (2018-01-28) works OK.

**Comment by cnjinhao** [comment]
Thanks for reporting this issue. Fixed!

**Comment by qPCR4vir** [comment]
Ok. tested: Win7pro,CLion,Cmake, MinWG with gcc 8.1, release
