### ISSUE TITLE
fit column content vs. sort column vs. move column

### ISSUE THREAD

**Issue by qPCR4vir** [cnjinhao/nana#326]
When the cursor icon shows it is in position betwen headers it still sort the right column. 
Double click correctly fit left column content but also sort right column.

And some times when the cursor icons shows it is in position betwen headers and you drags it, it move the rigth column instead of resizing the left column. Most of the time works correctly, resizing the left column. 

Compiled the develop nana (with hotfix-1.6.1 merged today) and nana-demo develop branch.
MSVC-2017 (v15.7.1) VC++14.1, but it is and old issue.

**Comment by cnjinhao** [comment]
>When the cursor icon shows it is in position betwen headers it still sort the right column.
Double click correctly fit left column content but also sort right column.

Fixed.

> And some times when the cursor icons shows it is in position betwen headers and you drags it, it move the rigth column instead of resizing the left column. Most of the time works correctly, resizing the left column.

I didn't reproduce the issue, maybe it's very hard to reproduce.

**Comment by qPCR4vir** [comment]
> ...  but also sort right column. Fixed.

Thank !! Ok. tested: Win7pro,CLion,Cmake, MinWG with gcc 8.1, release (sorry I have no time to fix it myself) 

But now I see a regression: in example `listbox_inline_widget` by double-click to resize a column it crash. 
But before that (tested 2016-06-28) by double-click to resize a column it fit only to the length of the button and not the inlined editbox+button

**Comment by cnjinhao** [comment]
Hi,tested the example and it crashed too(actually, it throws std::bad_alloc). IMO, this is a correct behavior, what we do is to fix the bug in the example.

```
	//Sets the inline widget size
	//dimension represents the max size can be set
	//The coordinate of inline widget is a logical coordinate to the sub item of listbox
	void resize(const size& dimension) override
	{
		auto sz = dimension;
		//sz.width -= 50; //HERE! it may cause an underflow error. because its type is unsigned integer
                //fix
		sz.width -= (sz.width < 50 ? 0 :  50);

		txt_.size(sz);

		rectangle r(sz.width + 5, 0, 45, sz.height);
		btn_.move(r);
	}
```
If the width of the column content was less than 50px, it produced a very large sz.width(becuaes of underflow), so `txt_.size(sz)` was going to throw `std::bad_alloc`.
