### ISSUE TITLE
basic mode background button - all black

### ISSUE THREAD

**Issue by qPCR4vir** [cnjinhao/nana#327]
The secound button in example background-effects is all black. 
It was also black in 2017-07-22 but ok in 2016-02-14

**Comment by cnjinhao** [comment]
Fixed, I plan to commit this patch later today or tomorrow. Thanks for reporting this issue.

**Comment by qPCR4vir** [comment]
Ok. tested: Win7pro,CLion,Cmake, MinWG with gcc 8.1, release
