### ISSUE TITLE
Listbox hovered not working

### ISSUE THREAD

**Issue by usernameiwantedwasalreadytaken** [cnjinhao/nana#328]
Hi,

I've created an inline widget (for a checkbox) inside the listbox following the [wiki](https://github.com/cnjinhao/nana/wiki/Creating-Inline-Widgets-for-Listbox). Everything works fine, except for the implementation of the `mouse_move` event of my checkbox (that should highlight the line of the table):

```
_box.events().mouse_move([this] {
      _indicator->hovered(_pos);
});
```

Instead of highlighting the current line, this code **always highlights the first line of the table**.

Looking at the code at `listbox.cpp`, I believe the problem has to do with the line `auto offset = ess_->content_view->origin().y / ess_->item_height();` inside the method `hovered`:

```
void hovered(index_type /*pos*/) override
{
	auto offset = ess_->content_view->origin().y / ess_->item_height();

	if (ess_->pointer_where.first != parts::list || ess_->pointer_where.second != offset)
	{
		ess_->pointer_where.first = parts::list;
		ess_->pointer_where.second = offset;
		ess_->update();
	}
}
```

In this case, `ess_->content_view->origin().y` always return 0 for every selection (even though the `pos` variable is diferent).

Thanks in advance.

**Comment by cnjinhao** [comment]
Thank you for reporting this issue!

**Comment by usernameiwantedwasalreadytaken** [comment]
Thanks for the fix.
