### ISSUE TITLE
Listbox with shared model doesn't handle changes

### ISSUE THREAD

**Issue by Diltsman** [cnjinhao/nana#329]
Given the following code, after the thread has looped a couple of times, it appears that `nana::drawerbase::listbox::drawer_lister_impl::_m_draw_item` has some issue with the line `auto & item = cat.items[item_pos.item];`.  The error appears using VS2015's checked iterators.  When in release mode (no checked iterators), the problem shows up much more infrequently and results in a crash.

    #include <nana/gui/wvl.hpp>
    #include <nana/gui/widgets/listbox.hpp>
    #include <numeric>
    #include <thread>
    #include <vector>
    
    int valueTranslator(std::vector<nana::listbox::cell> const &cells)
    {
        return std::stoi(cells.at(0).text);
    }
    
    std::vector<nana::listbox::cell> cellTranslator(int const &i)
    {
        std::vector<nana::listbox::cell> value;
        value.push_back(std::to_string(i));
        return value;
    }
    
    int main(int argc, char *argv[])
    {
        nana::form fm{ nana::API::make_center(1300, 600) };
        nana::place plc{ fm };
        plc.div("<list>");
        nana::listbox lb{ fm };
        lb.append_header("");
        plc["list"] << lb;
        std::vector<int> data;
        lb.at(0).shared_model<std::mutex>(data, valueTranslator, cellTranslator);
        plc.collocate();
        fm.show();
        std::thread t{ [&] {
            while (true)
            {
                using namespace std::chrono;
                std::this_thread::sleep_for(1s);
                lb.clear();
                lb.avoid_drawing([&] {
                    for (int i = 0; i < 1'000'000; ++i)
                    {
                        lb.at(0).append_model(i);
                    }
                });
            }
        } };
        nana::exec();
        if (t.joinable())
        {
            t.join();
        }
        return 0;
    }

**Comment by cnjinhao** [comment]
Thank you for reporting this issue. This issue is a thread-safety issue, because `lb.clear();` and `lb.at(0).append_model(i);` is not thread-safe. I will fix that.

Generally, nana is thread-safe, but some methods may cause thread-safe problem, because of bug. Don't worry about it, a common solution is call `internal_scope_guard` explicitly.

Let's see some workarounds for the issue.
```
    std::thread t{ [&] {
        while (true)
        {
            using namespace std::chrono;
            std::this_thread::sleep_for(1s);

            nana::internal_scope_guard lock;
            lb.clear();
            lb.avoid_drawing([&] {
                for (int i = 0; i < 1'000'000; ++i)
                {
                    lb.at(0).append_model(i);
                }
            });
        }
    } };
```
It's OK, but it prevents UI refresh if `append` operation spends too much time.

```
    std::thread t{ [&] {
        while (true)
        {
            using namespace std::chrono;
            std::this_thread::sleep_for(1s);
            {
            nana::internal_scope_guard lock;
            lb.clear();
            }
            lb.avoid_drawing([&] {
                for (int i = 0; i < 1'000'000; ++i)
                {
                    nana::internal_scope_guard lock;
                    lb.at(0).append_model(i);
                }
            });
        }
    } };
```
It doesn't prevent the UI, but the `append` costs more time.
