### ISSUE TITLE
A run-time error occurring when text_changed & focus events are interleaved

### ISSUE THREAD

**Issue by jk-jeon** [cnjinhao/nana#332]
Please see the following code:

````
#include <nana/gui/wvl.hpp>
#include <nana/gui/widgets/form.hpp>
#include <nana/gui/widgets/textbox.hpp>

int main() {
  nana::form fm{ nana::API::make_center(200, 200) };
  nana::textbox in{ fm, nana::rectangle{ 0, 0, 200, 200 } };

  in.events().text_changed([&]() {
    if( in.caption() != "" )
      in.fgcolor(nana::colors::red);
  });
  in.events().focus([&]() {
    in.caption("");
  });

  fm.show();
  nana::exec();
}
````

Executing this code, clicking the textbox, and then pressing the return key throws an error.
(`text_editor.cpp`, line 585; `this->sections`'s size is 1, but the code is accessing the second element.)
I couldn't analyze what's happening here.
Thanks.

**Comment by cnjinhao** [comment]
Fixed, a patch has been checked into the hotfix branch.
