### ISSUE TITLE
crash in calling front() for empty vector of vslines while collocating an empty label

### ISSUE THREAD

**Issue by qPCR4vir** [cnjinhao/nana#333]
in label.cpp code:
```  c++
                        rs.index = 0;
                        rs.vslines.clear();
                        rs.vslines.swap(*vsline_iterator++);
                        rs.pos.x = rs.vslines.front().x_base;

                        if (!_m_foreach_visual_line(graph, rs))
                            break;

                        rs.pos.y += static_cast<int>(rs.vslines.back().extent_height_px);
```

it was OK bis Commit: 9ff6567a03f6d8aa20758dc9b44f9aaf9a9aa534
but crash after Commit: 79c34392315d93e6a83cbe10cafeed99dec8d686

**Comment by cnjinhao** [comment]
Thank you for testing it!

**Comment by qPCR4vir** [comment]
Works ! Thank !

**Comment by qPCR4vir** [comment]
It works but I got the warning:

`nana\source\gui\widgets\label.cpp:148:18: warning: unused variable 'line' [-Wunused-variable]`

and

`nana\source\gui\widgets\label.cpp:462:13: warning: unused variable 'rest_extent_size' [-Wunused-variable]`

**Comment by cnjinhao** [comment]
Fixed
