### ISSUE TITLE
Outdated docs

### ISSUE THREAD

**Issue by KingDuckZ** [cnjinhao/nana#336]
I'm trying to learn how to implement my own widget with nana and I found [this page](https://github.com/qPCR4vir/nana-docs/wiki/Implement-a-widget) that seems to be exactly what I need.
Unfortunately the instructions are not clear at all, for example the button_drawer::set() method was never declared in the class prototype. Other bits are sketchy, for example I don't think void focus (paint::graphics &gra, const arg_mouse &ei) override; is correct (why focus() would receive a mouse event?).
Overall I found that page to be very confusing.

Worst of all, the actual button.hpp file in 1.6.2 is very different from all that. detached() is not overridden, so I'm left wondering if I really need to do that myself. bind_window() doesn't exist, and the attached() method is completely different. There is a measurer class, which is not even mentioned in the documentation.
As a newcomer, I'm finding it really hard to figure out what I should do.

**Comment by cnjinhao** [comment]
The documentation is continuously updated. But documentation is an arduous work, we can't make all contents updated.
