### ISSUE TITLE
tabbar控件的activated方法错误，当tabbar的数量比较多的时候，activated方法无法显示当前的按钮

### ISSUE THREAD

**Issue by wang12162008** [cnjinhao/nana#340]
如题,当tabbar的数量比较多的时候，activated方法无法显示当前的按钮,也没有相应的方法显示当前激活的页的按钮，创建完当tabbar后总是显示最后一个添加的页的按钮，给使用造成麻烦，希望能够有方法解决。

**Comment by cnjinhao** [comment]
感谢您的反馈！

**Comment by cnjinhao** [comment]
能否提供一段可重现此bug的代码？

**Comment by wang12162008** [comment]
找到原因了，我用了place,先调用了tabbar_.activated(0)，然后调用place_.collocate();导致显示页面是第一页，但tabbar_是最后一页，反过来调用就是正确的。
