### ISSUE TITLE
Drag&drop

### ISSUE THREAD

**Issue by cnjinhao** [cnjinhao/nana#345]
The support of drag&drop feature is under construction. Refer to [nana's forum](http://nanapro.org/en-us/forum/index.php?u=/topic/1030/ggdrag-and-drop) for details.

I encourage you to test this new feature and feel free to give your feedback.

Thanks in advance!

**Comment by cnjinhao** [comment]
The support of X11 has been implemented, it now requires libXcursor.

**Comment by beru** [comment]
I tested the example code and noticed several things.

- I can start dragging left listbox's item and drop it to the right listbox. But dragging right listbox's item into left listbox is not implemented. Although this may be intentional, I feel it is a bit unnatural.

- I cannot change the order of listbox's items with drag & drop operation. If the feature to move listbox's item into another listbox is available, the same thing should be possible with owner listbox. I think many users intuitively expect the feature.

- I expect the item to be dropped to the nearest cursor position but it is always added to the bottom position. Also, drawing preview line to indicate the drop position would be preferrable.

**Comment by cnjinhao** [comment]
Do you mean by that allowing dragging items from right list box to left list box is to make people easily understand the usage of simple_dragdrop?

The simple_dragdrop and dragdrop were designed to be general classes. IMO, the position where item to be inserted should be determined by the drop target function(the second parameter of simple_dragdrop::make_drop).

**Comment by beru** [comment]
I thought having some sort of an indicator such as a caption or right arrow icon lets users easily understand the instruction. But considering that the sample code is for developers, it may not be needed...

I modifed the program based on your suggestion.

```cpp
#include <nana/gui.hpp>
#include <nana/gui/widgets/listbox.hpp>
#include <nana/gui/dragdrop.hpp>

int main()
{
    using namespace nana;

    form fm;
    listbox list1{ fm };
    listbox list2{ fm };

    list1.append_header("column");
    list2.append_header("column");

    //Add items
    list1.avoid_drawing([&]{
        for (int i = 0; i < 100; ++i)
            list1.at(0).append({ "item " + std::to_string(i) });
    });

    fm.div("<list1><weight=10%><list2>");
    fm["list1"] << list1;
    fm["list2"] << list2;
    fm.collocate();

    fm.show();

    //Enables drag&drop from list1 to list2
    simple_dragdrop smpl_dnd{ list1 };

    //Starts drag and drop if user presses the left button
    //on an item in list1.
    smpl_dnd.condition([&list1]{
        return !list1.hovered().empty();
    });

    //Sets the drop target and specifies a function to transfer
    //data from list1 to list2.
    smpl_dnd.make_drop(list2, [&]{
        auto selections = list1.selected();

        list2.avoid_drawing([&]{

			auto cur_pos = API::cursor_position();
			API::calc_window_point(list2, cur_pos);
			auto pos = list2.cast(cur_pos);
			auto cat_fixed = 0;
			if (pos.empty())
				pos.item = list2.at(cat_fixed).size();
			pos.cat = cat_fixed;
			for (auto & s : selections)
			{
				auto txt = list1.at(cat_fixed).at(s.item).text(0);
				if (pos.item >= list2.at(cat_fixed).size())
					list2.at(cat_fixed).append(txt);
				else
					list2.insert_item(pos, txt);
				++pos.item;
			}
        });

        list1.erase(selections);
    });

    exec();
}
```

Now I understand that checking item position from cursor position is indeed possible thanks to the library's features. If I pay attention to details, the algorithm to calculate item index from cursor position can be fine-tuned for this specific purpose. No big deal though...

While writing the program, I felt that `cat_proxy` class not having `insert` method a little inconvenient.

`listbox::insert_item` throws an exception when index position is equal to the size of items, it might be handy if the method appends item in that case.

**Comment by cnjinhao** [comment]
Hi, @beru 
Thanks for your feedback. Based on your modification, I provides a new `insert_item` overloading to make the example more intitive.

```
    //on an item in list1.
    smpl_dnd.condition([&list1]{
        //here, pass false to hovered. it indicates an empty position returned if no item is hovered.
        return !list1.hovered(false).empty();
    });

    //Sets the drop target and specifies a function to transfer
    //data from list1 to list2.
    smpl_dnd.make_drop(list2, [&]{
        auto selections = list1.selected();

        list2.avoid_drawing([&]{
/*
			auto cur_pos = API::cursor_position();
			API::calc_window_point(list2, cur_pos);
			auto pos = list2.cast(cur_pos);
			auto cat_fixed = 0;
			if (pos.empty())
				pos.item = list2.at(cat_fixed).size();
			pos.cat = cat_fixed;
*/
                        //pass true here, it indicates the position next to last item(means 'end') returned if no item is hovered.
			auto pos = list2.hovered(true);

/*
			for (auto & s : selections)
			{
				auto txt = list1.at(cat_fixed).at(s.item).text(0);
				if (pos.item >= list2.at(cat_fixed).size())
					list2.at(cat_fixed).append(txt);
				else
					list2.insert_item(pos, txt);
				++pos.item;
			}
*/
			//the columns are copied.
                        //the number of columns to be copied: std::min(list2.coloumn_size(), list1.column_size());
			list2.insert_item(pos, list1, selections);
        });

        list1.erase(selections);
    });
```

**Comment by beru** [comment]
@cnjinhao Thank you for updating the library and providing the sample code.

I've noticed strange item selection behaviour so opened the issue #355. Please check it out.

**Comment by cnjinhao** [comment]
The intial `drag and drop` has been implemented. Now, it can works on both Linux and Windows. Data can be dragged and dropped between application and `Window Explorer`/`Linux file manager`.

`XDS` hasn't been supported, data can't be accpeted when dragging it from applications using `XDS` protocol, e.g. `xarchiver`.

**Comment by cnjinhao** [comment]
Hi, there, it's been a while. The developmenet of basic features of drag and drop has been finished, it can work correctly under Windows and Linux.

Now it can be downloaded from `develop-1.7` branch. If you are using MinGW, please make sure the distro of the MinGW contains COM headers.

The next phase of development is to verify the design and improve interfaces. 
Any feedback appreciated!
