### ISSUE TITLE
listbox weird multiple items selection after dragging items

### ISSUE THREAD

**Issue by beru** [cnjinhao/nana#355]
Hi, I've noticed listbox's multiple items selection with pressing shift-key does not work as expected after dragging items.

![test](https://user-images.githubusercontent.com/1131125/48305013-e703a200-e566-11e8-85a4-e1728d40d7bb.gif)

**Comment by beru** [comment]
Here's the test code.

```cpp
#include <nana/gui.hpp>
#include <nana/gui/widgets/listbox.hpp>

int main()
{
    using namespace nana;

    form fm;
    listbox list1{ fm };

    list1.append_header("column");

    //Add items
    list1.avoid_drawing([&]{
        for (int i = 0; i < 100; ++i)
            list1.at(0).append({ "item " + std::to_string(i) });
    });

    fm.div("<list1>");
    fm["list1"] << list1;
    fm.collocate();

    fm.show();
    exec();
}
```

I tested with `develop-1.7` branch, b3eacfddd09ac9fb74b9678915570a5501c3efad

**Comment by cnjinhao** [comment]
Sorry for late reply. Thanks for your feedback!
