### ISSUE TITLE
can use 'xdg-open' instead of 'firefox' to open url (system::posix_open_url )?

### ISSUE THREAD

**Issue by vtliem** [cnjinhao/nana#356]
On debian for Raspberry PI, there is no firefox by default.
system::posix_open_url can't open url (label).
I googled and found 'xdg-open' which can be used to open url by default browser.
Is there any reason not to implement it to nana?

**Comment by vtliem** [comment]
ps: My implement. It works OK on Raspberry Pi Desktop and ubuntu
```
              auto path = "/usr/bin/xdg-open";
		if (stat(path, &exists) == 0 && S_ISREG(exists.st_mode)) {
			char name[] = "xdg-open";
			char *argv[3] = { name, const_cast<char *>(url_utf8), nullptr };
			pid_t pid = 0;
			posix_spawn(&pid, path, NULL, NULL, argv, environ);
			return;
		}
```

**Comment by cnjinhao** [comment]
This feature will be shown in release of 1.7.4
