### ISSUE TITLE
static analysis fixes

### ISSUE THREAD

**Issue by Shamari91** [cnjinhao/nana#362]
Hi,

I've been using Nana for some time for some personal projects and now i want to contribute to open source projects.

So was wondering If I could fix some static analysis issues ? The small coding issues found were from cppcheck.

Thanks,
Shamari

**Comment by Shamari91** [comment]
Hi,

I have a small pull request for some cpp check issues.

It seems I don't have access to push any changes to my remote branch. (cloned from develop)

Would you be able to grant me access?

Thanks,

**Comment by qPCR4vir** [comment]
Hi, @Shamari91,
just use GitHub to make a 'fork' of this repo. 
It will appear in your GitHub user profile. You will be able to push your commit there. And from there you will be able to make Pull Requests to this repo.
Read this please: [GitHub Standard Fork & Pull Request Workflow](https://gist.github.com/Chaser324/ce0505fbed06b947d962)
