### ISSUE TITLE
experimental/filesystem: no such file or directory

### ISSUE THREAD

**Issue by Jomme5** [cnjinhao/nana#366]
Building the nana libraries 1.6.1 with Code::blocks and Mingw 8.1 under the hood I got this:

||=== Build: Debug in nana (compiler: GNU GCC Compiler) ===|
..\..\include\nana\filesystem\filesystem.hpp|125|fatal error: experimental/filesystem: No such file or directory|

Solution?

(I'm not a experienced C++ programmer)

**Comment by cnjinhao** [comment]
Thank you for reporting this bug! I will fix it.

**Comment by Jomme5** [comment]
for the sake of completeness:  it is Mingw-64 (version 8.1) apparently a big difference with the original Mingw like stated [here.](https://sourceforge.net/p/mingw/bugs/2363/)

**Comment by qPCR4vir** [comment]
To my knowledge, there is no implementation of filesystems in GCC for Windows. If you find it please tell me about it.
You need to use the nana filesystem or the 'boost' filesystem. Nana will try to select one of them, but you can help by settint it in your cmake or CB project.

Anyway, please first try the lates hotfix (1.6.2).

**Comment by cnjinhao** [comment]
only <filesystem> available on 8.1. <experimental/filesystem> removed

**Comment by ffred** [comment]
Hi,
just trying to compile nana 1.7.4 for the first time with Codelite & mingw_w64 v8.1 and got the same problem.
first try also with a "big" library compile with Codelite, so probably still much to learn here.
don't have more time just now; will search more probably tonight. but if you know something to help me...
thanks.
