### ISSUE TITLE
checkbox enable/disable

### ISSUE THREAD

**Issue by besh81** [cnjinhao/nana#368]
enabling/disabling a checkbox at run time doesn't change the appearance until the mouse move into the control

**Comment by JamesBremner** [comment]
Can you provide a brief code example showing the problem?

The following works as expected, 5 seconds after starting the checkbox is greyed out showing it is disabled without the mouse coming anywhere near.


```
int main()
{

    nana::form fm;

    nana::checkbox cb( fm, nana::rectangle( 10,10,50,30) );
    cb.caption("test");

    nana::timer t;
    t.interval( 5000 );
    t.elapse([&]()
    {
        cb.enabled( false );
    });
    t.start();

    fm.show();
    nana::exec();
}
```

**Comment by besh81** [comment]
Hi,

I'm using the checkbox without the text (only the square part) Sorry for not being enough specific.
What I'm pointing at is the square. It doesn't change the bgcolor until you move the mouse on it.
When the checkbox is disabled and you move the mouse on it the square change bgcolor and the control seem enabled.

Ciao

**Comment by besh81** [comment]
Just submitted a pull request #369 that should fix this

Ciao
