### ISSUE TITLE
How to run nana

### ISSUE THREAD

**Issue by yougar** [cnjinhao/nana#374]
hello,I'm a novice,I don't know how to run it.  so, I very aspire some help.
I have tried two methods,but they all failed.
1.  I cmake this file ,and get a nana.sln  but ,when I run it,  it notice me,fatal error LNK1120: Nine unresolved external commands.
2. I find a vc2017 file in build folder,so I get in it,I also find a nana.sln .but,when I run it, I get this notice ,nana_v141_Debug_x86.lib is not a valid Win32 Application

so ,I should do what to run it successfully?

**Comment by cnjinhao** [comment]
-lnana -lX11 -lpthread -lrt -lXft -lasound -lfontconfig -lXcursor

**Comment by micfan** [comment]
good, this option compiled successfully

``` bash
# Makefile
default:
	g++ main.cpp -I../nana/include -lnana -L../nana/build/bin -lX11 -lpthread -lrt -lXft -lasound -lfontconfig -lXcursor -lstdc++fs
```

**Comment by micfan** [comment]
I have build successfully most of the target of https://github.com/qPCR4vir/nana-demo

And if there is space, a CMake support for windows is under considering
