### ISSUE TITLE
switch between radio button to check box bug

### ISSUE THREAD

**Issue by Bluescaster** [cnjinhao/nana#375]
Hi, i discovered a bug in this great lib when trying to switch between radio button and check box (group class).

The 2 buttons allow to choose the kind of object but when you play with check boxes, program crash.

![image](https://user-images.githubusercontent.com/46357385/50659382-b3f4f200-0f9c-11e9-90d8-6173cc0da820.png)

`#include <nana/gui/wvl.hpp> 
#include <nana/gui/widgets/button.hpp>
#include <nana/gui/widgets/group.hpp>

class Principal : public nana::form
{
    public:

        Principal() : form(nana::API::make_center(400,300)) {

        	m_btnradio.caption("Radio");
        	m_btnradio.events().click([this]{
            	this->m_group.radio_mode(true); 
        	});

        	m_btnbox.caption("Box");
        	m_btnbox.events().click([this]{
            	this->m_group.radio_mode(false); 
        	});

        	m_group.radio_mode(false);
        	m_group.add_option("Disco");     
            m_group.add_option("Blues");
            m_group.add_option("Jazz");
            m_group.add_option("Rock");
            m_group.add_option("Dance");
            m_group.add_option("Rap");
        }

    private:

    	nana::button m_btnradio{*this,nana::rectangle(50,30,140,20)};
    	nana::button m_btnbox{*this,nana::rectangle(210,30,140,20)};
        nana::group m_group{ *this, "Music Style", false, 2, nana::rectangle(50,70,200,200) };
};

int main()
{
	Principal f;
	f.show();
	nana::exec();

    return 0;
}`

**Comment by cnjinhao** [comment]
Hi, Thank you for reporting this bug!
