### ISSUE TITLE
blurry on high dpi

### ISSUE THREAD

**Issue by ejamshidiasl** [cnjinhao/nana#378]
Hello
i have windows 10 and 1080p monitor with high dpi.i am using 150% scale in display settings.now nana is blurry and if i change to 125% scale then blurry fixes but gui become too small.in windows and c# i always use **SetProcessDPIAware** function.it is a user32.dll function but i can't call it in c++ project

**Comment by cnjinhao** [comment]
Thanks for your feedback! It's a known issue, the high DPI support will be added in future.

**Comment by beru** [comment]
#184 is related.

**Comment by beru** [comment]
@ejamshidiasl You should be able to call `::SetProcessDPIAware` WindowsAPI even if you use C++.
