### ISSUE TITLE
Linux menubar error

### ISSUE THREAD

**Issue by wumalv** [cnjinhao/nana#379]
ubuntu，menubar pop position error

**Comment by cnjinhao** [comment]
Hi,
Thank you for reporting this issue. Could you please tell me the version of Ubuntu and desktop environment you are using?

**Comment by cnjinhao** [comment]
Hi, this bug has been fixed, please download the branch `hotfix-1.6.2`

**Comment by cnjinhao** [comment]
This issue still exists. But a new fix will be shown up in next 1.7
