### ISSUE TITLE
Combo box position error on Ubuntu

### ISSUE THREAD

**Issue by Bluescaster** [cnjinhao/nana#380]
Hi,

When I open menu and combo box on Ubuntu, items appears not under the widget but far away.

After opening a combobox Ubuntu freeze.

I can send you my program and a video if you want.

Regards

**Comment by cnjinhao** [comment]
Hi,
Thank you for reporting this issue. Could you please tell me the version of Ubuntu and desktop environment you are using?

**Comment by Bluescaster** [comment]
Hi,

I use Ubuntu 16.04LTS 32bits with Gnome.

Regards

**Comment by cnjinhao** [comment]
This issue still exists. But a new fix will be shown up in next 1.7
