### ISSUE TITLE
subform position on opensuse - xfce

### ISSUE THREAD

**Issue by crillion** [cnjinhao/nana#389]
Hi,

  I think this issue is similar to the one of the combo box position on ubuntu, but this time it's with a subform.
  I'm getting it with nana 1.6.2 on opensuse 15.0, environment xfce.
  When I open a subform, on linux it appears displaced far away (while in windows 10 it's immediately near the parent form). Here's the code :

#include <nana/gui.hpp>

using namespace nana;

int main()
{
    form form1;
    form1.show();
    form form2 { form1, rectangle { 0, 0, 200, 500 } };    
    form2.show();
    exec();
}

Thanks and regards,

               Marco

**Comment by cnjinhao** [comment]
A patch has been checked into `develop-1.7` branch.
