### ISSUE TITLE
Added a textbox::text method

### ISSUE THREAD

**Issue by wpp2014** [cnjinhao/nana#397]
I think getting all text from textbox is a common feature, but I can't find the function in textbox. So I change my local code, I hope textbox can support this function.

this is my local changes:

```C++
// hpp
// Get all text from textbox.
// It returns a empty string if failed or the textbox is empty.
std::string text() const;

// cpp
std::string textbox::text() const {
  internal_scope_guard lock;
  auto editor = get_drawer_trigger().editor();
  if (editor) {
    return to_utf8(editor->text());
  }
  return std::string();
}
```

**Comment by qPCR4vir** [comment]
Sorry, did you tried just 'tb.caption();' ?

**Comment by qPCR4vir** [comment]
But yes, I like your proposition. It could be implemented just as:
`std::string text() const { return caption() ;};`

see: https://github.com/cnjinhao/nana/blob/master/source/gui/widgets/widget.cpp#L57
and: https://github.com/cnjinhao/nana/blob/master/source/gui/widgets/textbox.cpp#L808

**Comment by wpp2014** [comment]
I didn't try textbox::caption because I don't understand what this function means. This function satisfies my needs.
I agree you to add `std::string text() const { return caption() ;};`. This allows the developers to better understand.
Thank you!

**Comment by dnso86** [comment]
@wpp2014 I think it is a good idea - would you consider opening a PR with the changes?

**Comment by wpp2014** [comment]
@dnso86 OK

**Comment by cnjinhao** [comment]
1.7.2 includes this change.
