### ISSUE TITLE
group bug: the layout isn't updated when enable_format_caption(bool) is called

### ISSUE THREAD

**Issue by ErrorFlynn** [cnjinhao/nana#399]
If the user first sets the group caption using formatted text, and then calls `enable_format_caption(true)`, the caption label is placed in a field that has the size of the text  without formatting applied. For example:
````
group grp{fm};
grp.caption("<bold color=0x81544F size=12>Group caption</>");
grp.enable_format_caption(true);
````
The only way for the user to cause the layout to update and use correct dimensions, is to call `caption_align` with an alignment other that `left`, or to change the caption again. The user shouldn't have to care about such implementation quirks, so I consider this a bug.

**Comment by cnjinhao** [comment]
Thanks for your feedback! The corresponding PR has been merged.
