### ISSUE TITLE
codeblocks7.12无法编译nanagui1.7

### ISSUE THREAD

**Issue by wang12162008** [cnjinhao/nana#407]
如题

**Comment by cnjinhao** [comment]
Nana 1.7 doesn't support the MinGW comming with Code::Blocks. Please use MSYS2's MinGW distro instead. Follow the steps to replace with MSYS2's MinGW.
https://github.com/cnjinhao/nana/wiki/Troubleshooting-MinGW

**Comment by wang12162008** [comment]
thank you!






At 2019-03-17 07:06:40, "Jinhao" <notifications@github.com> wrote:


Nana 1.7 doesn't support the MinGW comming with Code::Blocks. Please use MSYS2's MinGW distro instead. Follow the steps to replace with MSYS2's MinGW.
https://github.com/cnjinhao/nana/wiki/Troubleshooting-MinGW

**Comment by wang12162008** [comment]
编译确实通过了，但无法和dll文件一起使用，导致无法正常运行






At 2019-03-17 07:06:40, "Jinhao" <notifications@github.com> wrote:


Nana 1.7 doesn't support the MinGW comming with Code::Blocks. Please use MSYS2's MinGW distro instead. Follow the steps to replace with MSYS2's MinGW.
https://github.com/cnjinhao/nana/wiki/Troubleshooting-MinGW
