### ISSUE TITLE
Combox selected event shouldn't be triggered when displaying modal msgbox.

### ISSUE THREAD

**Issue by beru** [cnjinhao/nana#411]
Hi, I encountered strange behaviour when testing nana-demo's [widget_show](https://github.com/qPCR4vir/nana-demo/blob/master/widget_show.cpp) program.
I use Windows 10 OS and build apps with VS2017.

Please check these steps to reproduce the issue.

1. Start `widget_show` program.
2. Push close (x) button on the right side of the title bar.
3. The message box will be shown. Caption : `Question`, Text : `Are you sure you want to exit the demo?`
4. Move mouse cursor over editable combox and rotate mouse wheel.
5. Another message box will be shown. Caption : `Item Selected`. Text : `The item 0 is selected in editable combox`

The same thing happens with uneditable combox.

I expect the event wouldn't be fired since the comboxes are in parent window when modal msgbox is displayed.

![ss](https://user-images.githubusercontent.com/1131125/54863116-c7d41700-4d87-11e9-85f7-751ccd40f69d.jpg)

**Comment by cnjinhao** [comment]
Fixed! Thank you for reporting this issue.

**Comment by beru** [comment]
@cnjinhao I've confirmed that the issue is fixed. Thank you!
