### ISSUE TITLE
Distinguish between the mouse buttons with widgets event handlings

### ISSUE THREAD

**Issue by beru** [cnjinhao/nana#413]
Many widgets react not only the left mouse button but also middle and right mouse buttons.

For example, `combox`'s push button reacts to (middle | right) mouse down and item selection can be changed with (middle | right) mouse down and up. Also, `tabbar`'s activated item can be changed by (middle | right) mouse button.

I think these behaviours aren't favourable since they are different from standards.

**Comment by cnjinhao** [comment]
Fixed, thanks for your feedback!

**Comment by beru** [comment]
@cnjinhao I've confirmed the fixed behaviour. Thank you!
