### ISSUE TITLE
Don't typedef 'nana::string' as an alias for `std::wstring` on Linux systems

### ISSUE THREAD

**Issue by kirbyfan64** [cnjinhao/nana#42]
More info [here](http://stackoverflow.com/questions/402283/stdwstring-vs-stdstring). In short: `std::wstring` sucks on Linux systems. Badly.

**Comment by cjxgm** [comment]
Agree.
And I think it's better to behave just like other cross-platform toolkit (qt/gtk) on this issue that, the user always use utf-8, only the platform-specific code (the one calling Win32 API) do the conversion from utf-8 to utf-16.

**Comment by qPCR4vir** [comment]
I dont agree.
The nana solution is a lot more efficient and honest. It give you more control about the issue.
 It is the way modern c++ libraries go. See filesystem - it could add some more ideas.
In Linux it is std::string as long as I know, or?

**Comment by qPCR4vir** [comment]
I don't understand why you mention std::wstring in Linux. 
Where have you see that?? 
It could be some kind of error simple to fix.

**Comment by qPCR4vir** [comment]
Now, let see a typical situation: 
- you get the result from one GUI function just to pass it immediately to another. 
A simplified view of the current situation in nana involve only 3 efficient move in any system.
But (pre)Historical libraries will force in some system two full conversions and a lot of copy and move, and the programmer can't do anything about it, and any modern compiler will not help.

In a similar situation: 
- you have a lot of string in the same "format" your system uses. 
In current nana you pass (move) it for free, or convert once in other system.
But some other GUI force you to manually convert the strings to some "universal" format, only to reconvert it internally while passing into the system: two full conversion in a system you expect it for free !! (and still one in any other)

You have to pay only for what you use.

**Comment by kirbyfan64** [comment]
@qPCR4vir The problem is that *unicode support with wstrings is broken*. Basically, on Linux systems, embedding UTF-8 chars in a wstring will print crap to the screen.

I agree with you, but this is more of a what works vs what doesn't work thing.

**Comment by qPCR4vir** [comment]
OK, if don't works...
But I 'm still trying to understand the problems of wstring in Linux with nana (with uses string and char in Linux). 
The problems with wstring are all in windows, but this is a windows problem, not a nana problem. By hidden it inside nana you only.. well hide it, but no solve it and you loss any possibility of being at control. I don't like any extra typing, and the core of my code uses string exclusively, so using only string in nana could be an small plus for me. But I know every time I print a text on the screen it will be converted in windows possible many times...
I agree that we need to continue to think about and at some point change things, but for now it is not very easy.

**Comment by kirbyfan64** [comment]
@qPCR4vir I think you got me wrong.

I'm not suggesting changing anything on Windows systems. My suggestion is that, if Nana is being built on Linux, to always set `nana::string` to `std::string`. Something like:

```c++
#ifdef __linux
typedef std::string string;
#else
// normal stuff goes here
#endif
```

**Comment by qPCR4vir** [comment]
Oh... NANA_UNICODE is always defined?... 

```cpp
// file:    include\nana\deploy.hpp
#ifndef NANA_UNICODE
	namespace nana
	{
		typedef char		char_t;
		typedef std::string string; ///< An alias of std::wstring or std::string, depending on the macro NANA_UNICODE
	}
	#define STR(string) string
#else
	namespace nana
	{
		typedef wchar_t			char_t;
		typedef std::wstring	string; ///< An alias of std::wstring or std::string, depending on the macro NANA_UNICODE
	}
	#define STR(string) L##string
#endif
```

**Comment by qPCR4vir** [comment]
I think this have to be controled not by NANA_UNICODE but by something like SYS_PREFER_WCHAR defined in windows but not in Linux... or?

**Comment by cnjinhao** [comment]
Maybe, removing the typedef-name nana::string is a good solution, all methods/interfaces have both overloads.
```
void xxx(std::string str);  //UTF8
void xxx(std::wstring str); //Wide char string
```

**Comment by kainjow** [comment]
I agree, wstring should only be used on Windows.

IMO, it's kind of a mess currently with use of std::string and std::wstring throughout the code. I would suggest using nano::string everything, rip out direct use of STL strings and make nano::string a compile-time wrapper around either a lite UTF8 std::string class, or UTF16 std::wstring class (meaning, they are unicode aware based on their encoding). Each class could have methods like to_utf8() and to_utf16(), while c_str() would be the native char type. This would be the best of both worlds.

**Comment by redagito** [comment]
I am currently having a related problem. Compiling without NANA_UNICODE being set, yields the error 
> error C2535: 'void nana::widget::caption(std::string)' : member function already defined or declared	d:\projects\nanatest\external\nana\include\nana\gui\widgets\widget.hpp

This is caused by the declarations in widget.hpp

    void caption(std::string utf8);
    void caption(nana::string);

where nana::string resolves to a std::string and thus causes the error.
I am working with Visual Studio 2013 Express.

**Comment by cnjinhao** [comment]
A solution for this issue.
```
void caption(std::string text_utf8);
void caption(std::wstring text); //not nana::string
std::string caption() const; //returns a text as UTF8 encoded
```
Under Windows, maybe std::wstring caption() is preferred by Non-English Windows programmers.

**Comment by kirbyfan64** [comment]
All I know is that Linux's `std::wstring` is virtually broken...

**Comment by cnjinhao** [comment]
Thank you

**Comment by cnjinhao** [comment]
Hi, guys, this work is starting now, see prepare-utf8 branch. The purpose of this branch is to kill NANA_UNICODE and typedef-name nana::string. Any suggestion will be appreciated.

**Comment by qPCR4vir** [comment]
Hi !
I see. I big problem. Here are my ideas, but I don't know the problem very well. 

I think there is a technical problem to solve. It is complex but we could resolve it (how to efficiently communicate with different OS which prefer different char type: char8 in linux and char16 or char8 in windows). Where to have the text coded in UNICODE or ASCII is a very related but different problem. It can be UNICODE in char8 or char16 - or 32, or windows codepages, etc.

The second problem is a "usability" problem. The practice shows that many people don't like or don't understand **STR(), nana::string, nana::chat_t, NANA_UNICODE**. Unfortunately this is a very serious non technical problem. 
I think that you are right, and in this moment, to have more users of nana all of this have to be removed or "killed".
But I suggest not to kill completely. I suggest:
- Eliminate any mention of this in any introduction, presentation, demo, etc.
- Eliminate it from any normal or default config or installation procedure - make no possible installation error related to this, even if this produce less efficient solutions.
- Eliminate this from most API. Let for example caption() return and take std::string.
- Don't completely kill it. Keep it for internal use, with no default exposure to users. Nana have many things which are much more complex and problematic, but at the core, not exposed, and nobody care, and nobody can make errors with it. Let for example: to normally set or get the text from a label widget use std::string - one do that not so oft, no problem, but internally keep in the same form what you need to print it again and again - resizing and repainting occur very oft.
- move to an external namespace to make it evident it is not a nana problem: 
```cpp
namespace OS_prefered // some ugly name, it is for advanced users or internal use only
{
#ifdef NANA_WINDOWS
using char_t = TCHAR;
#else
using char_t = char;
#endif

using string = std::basic_string<char_t>; // or something equivalent
}
namespace nana
{
...
class widget: public ...{
...
public:
std::string caption() const {return convert<std::string>(OS_caption());};
widget & caption(std::string txt){OS_caption(convert<OS_prefered::string>(txt));};

//for internal and advanced users:
OS_prefered::string OS_caption(return m_caption_text;) const;
widget & caption(std::string txt);

protected:
void draw() const override {drawtxt(m_caption_text);} //internal API, take OS_prefered::string
private:
OS_prefered::string m_caption_text;
};
}
```
Most user will never touch the OS_prefered namespace, and will make no error.
Additionally, never use wstring because it is not well define. In case of need use `std::u16string` and  `char16_t`
convert will be an inline template function that call charset() to convert or (perfect forward?) return the argument if both types are equal or (c++) convertible.

- for STR() don't use a macro style. Just 
OS_prefered_literal_string // very ugly
or
OS_str 
```cpp
// in windows
#define OS_str L"" 
//in linux
#define OS_str   
w.OS_caption( OS_str "my caption"); //for advanced users. Remember literal string notation not a macro
```
see http://ideone.com/4EKpla

**Comment by qPCR4vir** [comment]
Ohh !!
Very funny. I wanted to know if my "ugly macro" OS_str was sufficiently ugly to be usable and googled and, and found this:
https://github.com/rust-lang/rust/blob/master/src/libstd/ffi/os_str.rs
https://github.com/rust-lang/rust/blob/master/src/libstd/sys/windows/os_str.rs
https://doc.rust-lang.org/std/ffi/struct.OsStr.html

**Comment by cnjinhao** [comment]
What a constructive suggestion! The marco OS_str will be helpful.

I intend to provide `caption()` function with various versions. This is what [filesystem::path](http://en.cppreference.com/w/cpp/experimental/fs/path) does.
```
widget& caption(std::string utf8str); //throws if utf8str does not hold a string encoded as UTF8
widget& caption(std::wstring str);

std::string caption() const; //a UTF8 string
std::wstring caption_wstring() const;
native_string_type caption_native();
```
Refer to [filesystem::path](http://en.cppreference.com/w/cpp/experimental/fs/path) , it 
native_string_type is native encoded of operation system: std::string on POSIX, std::wstring on Windows.

API::window_caption() is another function used to set and get text of widget. It only has UTF8 version.

**Comment by qPCR4vir** [comment]
I agree, that is OK.  filesystem resolved that problem.
Only please, don't do:  `nana::native_string_type ` because people will get confused again. They will think nana implement some kind of string. Please do: `OS::native_string_type ` or something else.

All this will make my programs much more "std" like. Thank !

**Comment by qPCR4vir** [comment]
One more observation: 
always when possible prefer to throw during the conversion or check the result and then throw, and not check first and then convert, because that will penalize all the time you pass a correct string, which will be always the case in a correct program.

**Comment by cnjinhao** [comment]
The native_string_type is a member type of class widget, only used for the return type of 'caption_native()' method.

**Comment by cnjinhao** [comment]
Essentially, the solution you provided is no difference with what I intended to provide, except the form.

```
widget & OS_caption(OS_prefered::string txt);
//will hit one of 
widget& caption(std::string utf8str);
widget& caption(std::wstring wstr);
```
and
```
OS_prefered::string OS_caption() const;
//is equalt to
widget::native_string_type caption_native();
```

**Comment by cnjinhao** [comment]
The marco OS_str is a superb invention. Thank you qPCR4vir for shareing this idea.
```
widget.caption("text"); //no conversion takes place on POSIX system
widget.caption(L"text"); //no conversion takes place on Windows
widget.caption(OS_str"text"); //no conversion takes place both on POSIX system and Windows
```

**Comment by Pr0curo** [comment]
Hi,

the best thing from my perspective (as a nana user) is, wrapping the system-dependant strings (utf8 on linux, utf16 on windows) and only give an interface with std::string to the user of the library.

**Comment by mrtimdog** [comment]
I'm looking for a toolkit for a new project and am possibly considering nana, but here I agree with Pr0curo. As this is a C++ library, users will surely expect to be able to use standard types, i.e. std::string, when using any of the nana interfaces for strings. Renaming existing, standard, types just to enable cross platform conformity is a unnecessary knowledge overhead of library usage obfuscating what should be simple, transparent, tasks with strings.

Just my thoughts.

**Comment by qPCR4vir** [comment]
Hello @Pr0curo , @mrtimdog ,
That is exactly what is going on now, already working in nana v 1.3.
Please just forget you have ever listened about nana::string, STR(), etc.

Just use std::string, encoded with UNICODE utf8 and be happy!
I have already adapted some of the demos and is working very good.
Enjoy.
