### ISSUE TITLE
Treebox treats root paths / and \ as a node

### ISSUE THREAD

**Issue by dudztroyer** [cnjinhao/nana#422]
@cnjinhao is parsing the first / or \ as a node intended? Because if you use the default xPath from other libraries it generates / as the first character from the root documents (eg pugixml).

I've seen the commit https://github.com/cnjinhao/nana/commit/5c50bd7a56291c4d818a00c7eff16c10b33ea317#diff-860264e5a2113a1a836ffd5e3cc74b11 but idk if this is intended. Can you check it out?

I've got a xml that's been parsing correctly until this change, which is just a simples 2 nodes but when populating it is giving me a new unwanted node.

````
<info version="123" date="2019-04-10"/>
<settings>
<child />
</settings>
````
Should parse as is, but instead it is parsing as if there was a parent node without name in this two, such as:
````
<>
<info version="123" date="2019-04-10"/>
<settings>
<child />
</settings>
</>
````
I''ve got a running version with nana-1.6.2 pre-this-commit, and a nana-hotfix-1.7.0 after-this-commit.
Both ways i'm using when inserting the path "/Settings/Walker".

What happens:
https://upload.wsbot.net/files/devenv_2019-04-17_20-11-47.png
>On the menu, first line is the Path to the node from the tree node. 

Expected:
https://upload.wsbot.net/files/devenv_2019-04-17_20-12-31.png
>On the menu, second line is the Path to the node from the tree node. 

I think that this is not intended. If it is, I dont think of a use case scenario which would be better to parse starting nodes from / as a new one.

The code to insert nodes is this:
````
	_treeSettings.insert(node->path(), node->name());
````
Which for the example one is equal to:
````
	_treeSettings.insert("/Settings", "Settings"));
````
And yet it produces a root child empty.

**Comment by cnjinhao** [comment]
Fixed! Any feedback is appreciated!

**Comment by dudztroyer** [comment]
Thanks @cnjinhao 

I'll do some testings and see what comes up.
