### ISSUE TITLE
Linking to stdc++fs.lib fails

### ISSUE THREAD

**Issue by khrynczenko** [cnjinhao/nana#423]
I tried building my project with nana with latest commit (commit ffa170b5f560dbf899030bdeb0e539aa95b0364) and was unable to do so beacuse of linkage error:
`LNK1104	cannot open file 'stdc++fs.lib'`
I am using Visual Studio 15 2017 version 15.9.11.

**Comment by cnjinhao** [comment]
There is not a stdc++fs file in Visual Studio. Please remove the linker option.

**Comment by khrynczenko** [comment]
Yes, I did that already. My point is why CMake generates project with such linker option in the first place.

**Comment by khrynczenko** [comment]
Okay so my question is do we really need to link `stdc++fs` explicitly in file `select_filesystem.cmake`? We already define `target_compile_features(nana PUBLIC cxx_std_17)` in `CMakeLists.txt` so is it really necessary? This linking part breaks my builds on Windows.  
https://github.com/cnjinhao/nana/blob/39c3f85627571e9d3420781787a576ce8e300ac1/build/cmake/select_filesystem.cmake#L46  
https://github.com/cnjinhao/nana/blob/39c3f85627571e9d3420781787a576ce8e300ac1/CMakeLists.txt#L33

**Comment by 5cript** [comment]
Yes since you can have C++17 enabled without using std::filesystem on g++.
And I think clang doesn't need the linker line too.

This is one rare case where checking against the compiler is a viable method:
https://stackoverflow.com/a/50173063

**Comment by khrynczenko** [comment]
@5cript Thank you for answering. Indeed in order to use std::filesystem with GCC stdc++fs needs to be linked explicitly. I found out that in newest GCC release (9.1) it is not longer required to do that but yeah I suppose we still want to be able to build *nana* on older versions. Anyway I am going to add PR with changes so that stdc++fs is only linked on GNU using systems.
![obraz](https://user-images.githubusercontent.com/15171153/59976232-d073fd80-95c1-11e9-9023-930554c5f9c7.png)

**Comment by qPCR4vir** [comment]
Solved by https://github.com/cnjinhao/nana/pull/494
