### ISSUE TITLE
Add git tags for versions 1.7.0 and 1.7.1

### ISSUE THREAD

**Issue by khrynczenko** [cnjinhao/nana#424]
Official nana site states that current release is `1.7.1`. Latest git tag is `1.7.0-alpha` so I assume it was not updated yet. In my projects I like to use git tags in cmake to point to the version I want to use as my dependency. I think it would be nice do add tags for the missing versions.

**Comment by cnjinhao** [comment]
Hi, @khrynczenko , thanks for your feedback! the tags are added.

**Comment by khrynczenko** [comment]
Cool, thank you :)
