### ISSUE TITLE
linking issue with filebox::show()

### ISSUE THREAD

**Issue by ducttapecoder** [cnjinhao/nana#425]
Hi all,

I got the error below when linking my project

`undefined reference to `nana::filebox::show[abi:cxx11]() const'`

Commented the show() line out and it linked fine.

nana built on msys2 - mingw64 with gcc-8.3

**Comment by cnjinhao** [comment]
Was `-std=c++17` specified when building nana and your project?

**Comment by ducttapecoder** [comment]
It was not compiled with the flag. I rebuilt with the flag and it worked beautifully now. Thank you.
