### ISSUE TITLE
widgets update during event handling still not working properly

### ISSUE THREAD

**Issue by besh81** [cnjinhao/nana#431]
Hi @cnjinhao 

I'm using nana 1.7.1 and I'm facing a problem with the widgets update during event handling.
The release note of 1.7.1 says it should be fixed but there are still some problems.
It's very easy to see using nana creator 0.19.0 (create a new form or panel and add 2 fields at the same level. Clicking on the fields to select them doesn't work properly). This weird behavior appear in nana 1.7.0. Using nana 1.6.2 everything is ok.
Unfortunately I'm not able to replicate it with an easier example.

Any ideas?

**Comment by cnjinhao** [comment]
Fixed! Thank you for reporting this issue!

**Comment by besh81** [comment]
Great now everything work as expected!
Thanks.
