### ISSUE TITLE
Changing release ZIP filenames on SourceForge to not contain whitespace

### ISSUE THREAD

**Issue by dnso86** [cnjinhao/nana#432]
A small idea, however I don't think I am the only one who struggles with using a filename such as `nana 1.7.1.zip` in a Makefile for instance - if automatically downloading and unpacking it from `https://netcologne.dl.sourceforge.net/project/nanapro/Nana/Nana%201.x/nana%201.7.1.zip`.

Even though there are multiple ways to handle such a filename in `make`, I think on the long term having a release filename without a space - `nana_1.7.1.zip` for example - would make sense.

**Comment by cnjinhao** [comment]
Hi, I don't recommend dowloading from the sourceforge. Because when a mirror provider doesn't get updated a new file, the downloading URI always refers to a page to redirect the download.

I uploaded 1.7.2, please try the filename nana_1.7.2.zip
