### ISSUE TITLE
Chinese Font Issue On Linux

### ISSUE THREAD

**Issue by Hackman1993** [cnjinhao/nana#439]
I noticed there are some issue on Ubuntu Linux 18.04,All Chinese Character become square,It can be resolved by using font::set_default method but I don't think it's a good result because sometimes chinese character is good but english character become square,and we don't know wheather client computer installed the specific font.
   Build Enviroment: Ubuntu Linux 18.04 Desktop x86_64
                toolchain: GCC + CMake
                additional libraries:boost

**Comment by Hackman1993** [comment]
maybe offer a fallback font setting or something else would better,other program with chinese is good

**Comment by cnjinhao** [comment]
Hi, it's unknown issue. I will fix it. Thanks for your feedback!

**Comment by cnjinhao** [comment]
Fixed! Added a fallback fontset for various languages.

![fallback-fontset](https://user-images.githubusercontent.com/1246418/58619174-ebbb5800-82f6-11e9-80c5-adecc8943b73.png)

**Comment by cnjinhao** [comment]
Fixed! There is a new API to change the languages.
```
nana:;API::font_languages("zh,ar"); //Chinese and Arabic are rendered correctly.
```
