### ISSUE TITLE
can't compile filebox.cpp with vs2015

### ISSUE THREAD

**Issue by KuddLim** [cnjinhao/nana#452]
When I use nana v1.7.1 with VS2015, following function can not be compiled because it uses C++17 feature.

`
folderbox::folderbox(window owner, const path_type& init_path, std::string title)
    : impl_(new implement{ owner, fs::weakly_canonical(init_path).make_preferred(), title, false})
{}
`

> 1>d:\project_hdd\myproj\libnana\source\gui\filebox.cpp(1592): error C2039: 'weakly_canonical': is not a member of 'std::filesystem'
1>  d:\project_hdd\myproj\libnana\include\nana\filesystem\filesystem.hpp(569): note: see declaration of 'std::filesystem'
1>d:\project_hdd\myproj\libnana\source\gui\filebox.cpp(1592): error C3861: 'weakly_canonical': identifier not found
1>d:\project_hdd\myproj\libnana\source\gui\filebox.cpp(1592): error C2228: left of '.make_preferred' must have class/struct/union
1>  d:\project_hdd\myproj\libnana\source\gui\filebox.cpp(1592): note: type is 'unknown-type'

https://en.cppreference.com/w/cpp/filesystem/canonical

It should be available only when __cplusplus >= 201703.

**Comment by qPCR4vir** [comment]
Yes, you better update to C++17. If not, try to force use of nana::filesystem.

**Comment by qPCR4vir** [comment]
Use your IDE GUI to set NANA_FILESYSTEM_FORCE to 1. If works, it will be only "temporal": at some moment you will need to update to C++17

**Comment by cnjinhao** [comment]
Hi, there is a relevant fix, please try the `develop` branch.

BTW, the minimum support is VS2013, so VS2015 should not be a problem
