### ISSUE TITLE
awkward behavior of keyboard cursor in a textbox

### ISSUE THREAD

**Issue by wwriter** [cnjinhao/nana#456]
Hi, thank you for the effort you've put into maintaining this wonderful library. Recently, I've been looking for the C++ GUI library that best suits my needs and I thought Nana could be it. So, I've been testing it with some sample codes and I found out this one thing. When I run [this sample notepad program](https://qpcr4vir.github.io/nana-doxy/html/d1/d53/notepad_8cpp-example.html) and typed some Korean letters in the text editor field, the keyboard cursor looked weird. At some point, I can see two cursors blinking at both sides of the word that I'm typing. Furthermore, the new characters kind of overshadow the already written ones. I just wanted to know if this is happening because I did something wrong. Could you please check on this? That would be very much appreciated. I also will look into the textbox code tomorrow, thank you. 

![nanatextbox](https://user-images.githubusercontent.com/52746640/60976857-6f8e4880-a369-11e9-9614-63323bc9621c.gif)

**Comment by cnjinhao** [comment]
Hi, thank you for your feedback. I did some research, the left bolder caret you saw was not rendered by the library, it actually is the composition window of the input method. But I don't know why the composition window of the korean input method is incorrect.

**Comment by wwriter** [comment]
Thank you for your kind reply. While waiting for your answer, some of my team have looked into the code and kind of found out what could have caused the issue. But we've encountered some problems on the way, so we're currently working on it. I'll let you know if we find out something more. Please let me know if you do !

**Comment by JannLee** [comment]
I fixed this issue on #468
