### ISSUE TITLE
How windows drawn?

### ISSUE THREAD

**Issue by ejamshidiasl** [cnjinhao/nana#459]
Hello
i am learning c++
now i want to learn "HOW I CAN MAKE A GUI"
for example game engine draw images and etc. with opengl or directx ,...
how nanapro renders ui? which file is the base of draw in nanapro?

**Comment by marwik15** [comment]
Nana is drawing UI using native OS's APIs. Check "paint" directory. 
You can draw your own shapes using previously mentioned APIs. 
For Windows https://docs.microsoft.com/windows/win32/api/wingdi/
GNU/Linux https://xcb.freedesktop.org/XcbApi/
macOS https://developer.apple.com/documentation/coregraphics

Writing even simple GUI for a beginner could be overwhelming task. I'd recommend using system already established solutions like WPF or GTK. Using existing multi platform libraries is the best option here.

**Comment by ejamshidiasl** [comment]
nice
thanks
