### ISSUE TITLE
Three listbox bugs in essence::count_of_exposed() and listbox::last_visible()

### ISSUE THREAD

**Issue by ErrorFlynn** [cnjinhao/nana#472]
I have found three more listbox bugs:

1. `drawerbase::listbox::essence::count_of_exposed()`:
this function counts an extra item over the real count when "with rest" is requested and all the items fit in the viewport (when the vertical scroll bar is not being used)

2. `listbox::last_visible()`:
This function returns the item following the last visible item, because the item count returned by `count_of_exposed()` is added to the position of the first visible item. For example, if the first visible item is at display position 100, and 5 items are visible, the function returns display position 105, which is wrong. Since item 100 is itself part of the visible items, the function should return 104.

3. `listbox::last_visible()`:
This function can return an empty `index_pair` object when all items fit in the viewport, because `count_of_exposed()` doesn't account for any empty space in the viewport. For example if the viewport can fit 10 items, but the listbox only has 5 items, `count_of_exposed()` will return 10 instead of 5. That value is then passed to `drawerbase::listbox::es_lister::advance()`, which returns `npos`.

I will submit a PR with my proposed fixes (feel free to ignore them if there are better solutions).

**Comment by cnjinhao** [comment]
Thank you a lot for fixing these bugs.
