### ISSUE TITLE
graphics::gradual_rectangle off by one

### ISSUE THREAD

**Issue by KingDuckZ** [cnjinhao/nana#475]
On Linux at revision 38cdf4779456ba697d7da863f7c623e25d30f650, calling graphics::gradual_rectangle() results in a rectangle that is 1 pixel wider than the given width. For example this rect:

nana::rectangle r(0, 0, 10, 10);

will result in the area [0-11] to be filled horizontally, and [0-10] vertically. From a quick look at source/paint/graphics.cpp:1480, I see that XDrawLine() gets invoked with good_rct.right(). The [documentation](https://linux.die.net/man/3/xdrawline) of XDrawLine() says: *draw a line between the specified set of points (x1, y1) and (x2, y2)* which to me sounds like the coordinates are inclusive on both ends of the line.
Conversely, rect.right is usually exclusive, so that right - left = width (which is consistent with nana's behaviour).
It's a bit confusing but take the example of a 1-pixel wide rect, which would be given as left=0, right=1 (right - left = 1 - 0 = 1 width). Connecting pixels 0 to 1 actually means lighting the pixel at column 0 and the pixel at column 1, thus 2 pixels, which results in the bug I'm describing.

**Comment by cnjinhao** [comment]
Thank you for reporting this issue! Fixed
