### ISSUE TITLE
make编译失败,需要改成C++17标准

### ISSUE THREAD

**Issue by atmtntut** [cnjinhao/nana#486]
../../source/gui/filebox.cpp:1594:37: 错误：‘weakly_canonical’不是‘fs’的成员
   : impl_(new implement{ owner, fs::weakly_canonical(init_path).make_preferred(), title, false})

这个接口是C++17才支持的,makefile中std=C++11,编译失败,修改为C++17可以编过

**Comment by cnjinhao** [comment]
你的编译环境和nana的版本是什么？1.x版本是被设计成支持C++11的。当选择C++11时，可能是选用std::experimental::filesystem或者nana::filesystem，这个BUG应该是选择C++11时判断编译环境不全导致未启用nana定义的weakly_canonical
