### ISSUE TITLE
Consider using a tool such as Bakefile

### ISSUE THREAD

**Issue by kirbyfan64** [cnjinhao/nana#5]
Currently, all the build files are hand-written. This is prone to error and maintenance hell as time passes. You should consider using [Bakefile](http://bakefile.org/), which is based on the idea of pre-generating the build files. You run Bakefile on your computer, upload the generated files, and the user doesn't even know it exists.

It supports VS 2013 and GNU make. I can look into opening a PR for Code Blocks if desired.

Also, I'd be happy to contribute the build files if it's decided that this would be a good idea.

**Comment by cnjinhao** [comment]
Looking forward your contribution
