### ISSUE TITLE
It doesn't allow nana::form as global variable by using VS2019

### ISSUE THREAD

**Issue by WentsingNee** [cnjinhao/nana#503]
I found that VS 2019 doesn't allow nana::form as global variable.

```
nana::form fm;

int main()
{
	fm.show();
	nana::exec();
}
```

![image](https://user-images.githubusercontent.com/28091833/73942099-6ed28a80-4929-11ea-9f5d-c71011ae87c6.png)

However, I am sure this problem won't occur under Linux environment. No matter which compiler is, GCC or Clang.

**Comment by cnjinhao** [comment]
Hi, all widgets classes aren't allowed to defined as global variables no matter what compiler is using.

Do it in this way.
```C++
shared_ptr<nana::form> fm;

int main()
{
	fm = make_shared<nana::form>();
	fm->show();
	nana::exec();
}
```

**Comment by WentsingNee** [comment]
Thank you a lot! By the way, is it still unreasonable even it is compiled success on Linux?

**Comment by cnjinhao** [comment]
>is it still unreasonable even it is compiled successfully on Linux?

Yes, it is.
