### ISSUE TITLE
build error: filebox.cpp:1016, etc. using deleted nanas path.u8string() in linux

### ISSUE THREAD

**Issue by kojeriz** [cnjinhao/nana#511]
**Great merge to master. Build error!**
**gcc 7.4.0.**

Cmake command:
**cmake -D BUILD_SHARED_LIBS=OFF -D CMAKE_CXX_FLAGS=-fPIC -D NANA_CMAKE_ENABLE_JPEG=ON -D NANA_CMAKE_NANA_FILESYSTEM_FORCE=ON ..**

-- The CXX compiler identification is GNU 7.4.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
You are using nana directly from original sources. (Recommended!) If this was not your intention, and what you want is to install precomplied nana first, then please tern ON option NANA_CMAKE_INSTALL 
-- Found X11: /usr/include   
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found Freetype: /usr/lib/x86_64-linux-gnu/libfreetype.so (found version "2.8.1") 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'fontconfig'
--   Found fontconfig, version 2.12.6
-- Found Fontconfig: /usr/lib/x86_64-linux-gnu/libfontconfig.so  
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Found JPEG: /usr/lib/x86_64-linux-gnu/libjpeg.so (found version "80") 
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/nana/build-nana

![Screenshot from 2020-02-25 10-28-17](https://user-images.githubusercontent.com/37227782/75224558-bece9f80-57b9-11ea-839a-d31ed0a2ca08.png)

**Comment by qPCR4vir** [comment]
Yes, it is a posible bug now (because at some point it was OK). Could you help by replacing those 3 `.u8string `with .`string` and recompile and test if it is really running OK?
