### ISSUE TITLE
picture在macos上的图片展示问题

### ISSUE THREAD

**Issue by Hackman1993** [cnjinhao/nana#515]
原本应当是这样子的图片，原图格式为bmp,不让我上传所以我传了gif
![img_login_window_top](https://user-images.githubusercontent.com/10394867/76333872-d44cd900-6324-11ea-864e-696f3c2d5cb6.gif)
实际显示为
<img width="2046" alt="WeChat6ac172cd48118ddc10ebedd8a93984dc" src="https://user-images.githubusercontent.com/10394867/76333961-fe060000-6324-11ea-9cfb-e8d3b3110cc0.png">
感觉像是被绘制了很多很多次,代码很简单，使用了place，然后将picture对象放进去

**Comment by cnjinhao** [comment]
你把bmp文件发给我看看呢

**Comment by Hackman1993** [comment]
github上传不了bmp,但是就是用第一张gif转换出来的

**Comment by cnjinhao** [comment]
怀疑是bmp格式的支持问题，email发给我，cnjinhao at hotmail dot com

**Comment by Hackman1993** [comment]
发了，刚开始用，还不是很熟悉这套架子的调用栈，没法自己排查，抱歉

**Comment by cnjinhao** [comment]
邮件收到，但实际格式是一个JPEG，可能邮件服务器自动转换了格式。还得重新再发一次，最好是先压缩了，然后用附件发过来

**Comment by cnjinhao** [comment]
目前不支持压缩的BMP文件。比如用GIMP 打开该BMP，文件->导出为 弹出文件对话框 选导出 然后弹出到处选项对话框，不要勾选`行程长度编码`，最后导出文件。你这个BMP文件不压缩，反而更小。

或者 直接用 Windows画图打开 另存为 BMP 选24位/32位色 保存 即可。
