### ISSUE TITLE
not working code on Documentation

### ISSUE THREAD

**Issue by mohammed-altmimi** [cnjinhao/nana#518]
there is not working code on Documentation or in the reference manual
like this cod 
 
//......................................code ........................................//
#include <iostream>
#include <nana/gui/wvl.hpp>
#include <nana/gui/widgets/categorize.hpp>

void selected(nana::gui::categorize<int> & categ, int&)
{
    nana::gui::msgbox mb(categ, STR("categorize"));
    mb.icon(mb.icon_information);
    mb<<STR("The value of selected is ")<<categ.value()<<STR(", caption is \"")
      <<categ.caption()<<STR("\"");    //caption() method, see Note 3.
    mb();
}

int main()
{
    using namespace nana::gui;
    form fm;
    categorize<int> categ(fm, 10, 10, 200, 24);

    categ.childset(STR("Invalid Category"), 0);
    //Invalid category because of empty current category.

    categ.insert(STR("First"), 0);
    //Insert a category and now it is the current category.

    categ.insert(STR("Second"), 1);
    //Insert a category as a child of "First" category, and then
    //the "Second" is the current category.

    categ.childset(STR("Third"), 2);
    //Insert a category as a child of "Second".

    categ.childset(STR("Another Child"), 2);

    categ.ext_event().selected = selected;
  
    fm.show();
    exec();
}

//...............................................code.............................................//

and it not working because "nana/gui/wvl.hpp" was removed  from 
the lib in the newest  version  
and because some of these doc is very old 
"some page last modification  11/06/2013 02:02:52 
when run javascript command 
javascript:alert(document.lastModified)
if i not wrong
on the page"
the issue is that  i can not find a good examples for the newest version of 
the lib ....
or can any one modify the old version of the documentation of the old version  of the lib to newest version 

and excuse my English it`s not very good 
think you.

**Comment by cnjinhao** [comment]
Some parts of doc are out of date. I will update these docs when people are confused about them. Thank you for your feedback.

Here is the new version of the example. Please use the `hotfix-1.7.3` branch, there is a new fix to fix the compilation error.

```c++
#include <iostream>
#include <nana/gui.hpp>	//Use it instead of nana/gui/wvl.hpp
#include <nana/gui/widgets/categorize.hpp>

//there is no namespace nana::gui now.
void selected(const nana::arg_categorize<int>& arg)
{
	nana::msgbox mb(arg.widget, "categorize");
	mb.icon(mb.icon_information);
	mb << "The value of selected is " << arg.value << ", caption is \""
		<< arg.widget.caption() << "\"";    //caption() method, see Note 3.
	mb();
}

int main()
{
	using namespace nana;
	form fm;
	categorize<int> categ(fm, rectangle{ 10, 10, 200, 24 }, true);

	categ.childset("Invalid Category", 0);
	//Invalid category because of empty current category.

	categ.insert("First", 0);
	//Insert a category and now it is the current category.

	categ.insert("Second", 1);
	//Insert a category as a child of "First" category, and then
	//the "Second" is the current category.

	categ.childset("Third", 2);
	//Insert a category as a child of "Second".

	categ.childset("Another Child", 2);
	//childset() always insert categories into current category, and
	//it does not displace the current category, and therefore "Another Child"
	//is a child of "Second".

	categ.events().selected(selected);
	//This may crash in VC2012-RC due to compiler bug.
	//Please refer to compatibility-issue for more details

	fm.show();
	exec();
}
```

**Comment by mohammed-altmimi** [comment]
think you 
this very helpful
