### ISSUE TITLE
how to make checkbox's text align center vertically and fit its content?

### ISSUE THREAD

**Issue by yinkaisheng** [cnjinhao/nana#519]
Hi, 
`<init fit weight=28 gap=4 arrange=[variable,280,variable,variable,variable,48,variable,variable,variable,variable,variable]>`

![image](https://user-images.githubusercontent.com/5846696/76719968-61a18a80-6776-11ea-8c7d-d26927414400.png)
There is enough space to display 4 checkboxs, but the UI is ugly.
checkbox aligns top and is multiline when narrowing it.
I want checkbox to behave like button and combox.
The layout seems not flexible.

Thanks.

**Comment by cnjinhao** [comment]
`checkbox` doesn't have `text_align` method. Only way to make it is to change the div-text
```
<<init fit weight=28 gap=4 arrange=[variable,280,variable,variable,variable,48]><arrange=[100, 200, 300, 400] gap=4 margin=[top_bottom_xxx, 0]><test>>
```
The `top_bottom_xxx` is a value that is used for making the checkboxes in center. The checkbox doesn't support the `fit-content` feature, so, the weights[100, 200, 300, 400] of checkboxes have to be specified.

**Comment by yinkaisheng** [comment]
Thanks.

**Comment by yinkaisheng** [comment]
It works but it still behaves odd when resizing the window.
![nana](https://user-images.githubusercontent.com/5846696/76754611-65a4cb00-67bd-11ea-86b3-56709154444b.gif)
Other controls that support fit behave good.
I must set a mini size for the main window to avoid overlap.

I think it would be better if checkbox supports fit and v align.

**Comment by cnjinhao** [comment]
Suggest that a fixed weight is specified for the `init`, it can avoid the checkboxes overlapping the widgets.

**Comment by yinkaisheng** [comment]
OK, thanks.
