### ISSUE TITLE
Insanely weird behavior of text boxes on Linux

### ISSUE THREAD

**Issue by kirbyfan64** [cnjinhao/nana#52]
This is hard to explain. I open up the Notepad demo app. If I cycle between `a`, `s`, and `d`, the text cursor will start jumping down and up and left and right and inserting newlines. Pressing the space tends to move up a line.

In the place_login demo app, doing the same thing looks fine. However:

1. If I select all the text and start typing, it will be prepended to the beginning instead of replacing the selected text.

2. If I prepend text to the beginning and cycle through `a`, `s`, and `d` again, the text cursor will gradually move to the right.

Also, `API::exit` doesn't seem to exit anything. The window just stays there.

I love Nana, but this is just *insane*.

**Comment by kirbyfan64** [comment]
Also, in the `inputbox` example, I have to press the up and down arrows to change the date. I mean, *press*. I can't just lightly click it like most GUIs. I have to press it for about half a second.

But those blue colors look *cool*!

**Comment by qPCR4vir** [comment]
Did you test that with the new hotfixes-1.0.1 ? (not the develop branch)
some incorrect maping of key codes?
x86 or x64?
In windows is Ok.
Could you set a break point in line 1354 of  \source\gui\widgets\skeletons\text_editor.cpp and see what hapend after pressing a key?

**Comment by kirbyfan64** [comment]
Definitely still happens with that branch.

Ubuntu 14.04 x64.

I couldn't get the breakpoint thing to work, so I did the next-best thing: put a `cout` statement that prints the char codes. They look fine. I'm guessing the issue is in `move_caret`. Looking into it now...

**Comment by kirbyfan64** [comment]
@qPCR4vir Yup, definitely in `move_caret`. It's jumping up and down columns. Trying to find a fix.

**Comment by kirbyfan64** [comment]
@qPCR4vir I know very little about Nana's internals. All I can find out is that `points_.caret.y` keeps jumping up and down and up and down.

You guys need a Linux VM to test this...

**Comment by kirbyfan64** [comment]
Also, I uploaded a video of it to [YouTube](http://youtu.be/JGSMEqZ-28E). You can see the cursor jump around, even though the only button I press is Enter and the keys `a`, `s`, and `d`.

**Comment by cnjinhao** [comment]
Thank you for reporting this issue! A fix will be shown up in release of 1.0.2

**Comment by kirbyfan64** [comment]
@cnjinhao Thanks!

Only other thing I noticed was `API::exit` doesn't work. And the left column of the text box is oddly close to the window border.

This is still great, though. Nana's API is much nicer than GTK+, Qt, or (bleh) wxWidgets.

**Comment by cnjinhao** [comment]
The API::exit() issue is fixed. Thank you for your patience!

**Comment by kirbyfan64** [comment]
@cnjinhao It's fine! I like using Nana a lot already!
