### ISSUE TITLE
datetime.cpp with GCC 10.1 requires inclusion of stdexcept

### ISSUE THREAD

**Issue by crillion** [cnjinhao/nana#539]
Hi,

    I've tried to build nana 1.7.3 (as downloaded on 2020 may 11) on windows 10 with msys2/mingw-w64/gcc 10.1, using -std=c++17 .
	
	With the above configuration it seems to occur a problem : with this version of the compiler the class std::runtime_error is reduced in visibility (maybe it's included by less headers of the standard library) and so it's necessary, at least for the file datetime.cpp, to include its definition:
	
#include <stdexcept>

I send you a copy of the modified file, just with this simple change I managed to compile again the library.

 Thanks for your precious work.

         Marco

[datetime.zip](https://github.com/cnjinhao/nana/files/4611390/datetime.zip)

 
         Marco

**Comment by cnjinhao** [comment]
Thanks for reporting this bug. It has been fixed by PR#509.
