### ISSUE TITLE
Modify the content of a listbox(or any other component from the gui) from a different thread

### ISSUE THREAD

**Issue by chreniuc** [cnjinhao/nana#555]
How can we change the contents of a listbox from a different thred?

Our app does a lot things and we are using the `nana` library just to print a table when we receive something from the socket. So we created a thread where we started the gui app, and the main thread(+ a lot of other threads, we're using boost asio) does all the business logic.

Now when we receive something from socket(which is in a different thread) we want to change the contents of the listbox from that form based on some conditions. Does anyone know how we can do this?

This is a minimal example of what we have:

```c++
int main()
{
  std::shared_ptr<nana::form> form_ptr = std::make_shared<nana::form>(
      nana::rectangle{300, 200, 550, 300});
  std::shared_ptr<nana::listbox> lsbox_ask_ptr
      = std::make_shared<nana::listbox>(*form_ptr,
                                        nana::rectangle{10, 10, 250, 200});
  lsbox_ask_ptr->append_header("col_1");
  lsbox_ask_ptr->append_header("col_2");
  // start the thread that will show the form
  thread th1([&] {
    form_ptr->show();
    nana::exec();
  });
  
  // main thread or a different thread
  // We want here to change the contents of that list box:
  sleep(1);
  lsbox_ask_ptr->erase();
  lsbox_ask_ptr->at(0).append(
        {"col1_content", "col2_contents"});
}
```

We've lost almost 2 days trying to find a way, but we couldn't. This is the first time we are using this library. We're using 1.7.4 version.

Thanks.

LE: Or is there a way to initiate a custom event where we send a list of strings, and then we define an event handler on that form for that specific custom event which will get the list of strings and will populate the listbox contents?

**Comment by chris-shenzhen-china** [comment]
you could create a message queue and receive message with block mode in th1, and send a ui update message to th1 in other thread, then apend the listbox in th1。

**Comment by cnjinhao** [comment]
~~~
std::shared_ptr<nana::listbox> lsbox_ask_ptr;

int main()
{
  // start the thread that will show the form
  thread th1([&] {

  //The form should be created in the thread where nana::exec() executes.
  std::shared_ptr<nana::form> form_ptr = std::make_shared<nana::form>(
      nana::rectangle{300, 200, 550, 300});
  
  lsbox_ask_ptr
      = std::make_shared<nana::listbox>(*form_ptr,
                                        nana::rectangle{10, 10, 250, 200});
  lsbox_ask_ptr->append_header("col_1");
  lsbox_ask_ptr->append_header("col_2");

    form_ptr->show();
    nana::exec();
  });
  
  // main thread or a different thread
  // We want here to change the contents of that list box:
  sleep(1);
  lsbox_ask_ptr->erase();
  lsbox_ask_ptr->at(0).append(
        {"col1_content", "col2_contents"});
}
~~~
