### ISSUE TITLE
Dependency on libz.a?

### ISSUE THREAD

**Issue by qPCR4vir** [cnjinhao/nana#56]
Please see discussion here:
https://github.com/qPCR4vir/nana-docs/issues/2#issuecomment-101541717

**Comment by cnjinhao** [comment]
A fix will be shown in next release. This issue is caused by the precompiled libpng.a that does not contain zlib, but precompiled libpng.lib for VC contains zlib.

BTW, try this doc https://github.com/cnjinhao/nana/wiki/Configuration-of-Third-Party-Libraries-for-Nana, any revision is appreciated
