### ISSUE TITLE
if has_decoration =false ,msgbox will be cover by parent window in linux,window is well。 linux 下如果窗口设置为无边框模式,msgbox会隐藏到窗口下方

### ISSUE THREAD

**Issue by sdlforever** [cnjinhao/nana#560]
if has_decoration =false ,msgbox will be cover by parent window in linux,window is well。
linux下当主窗口设置为无窗口模式的时候,msgbox可以弹出,但是窗口处于主窗口下边,造成无法点击程序卡死。window无此问题。

**Comment by cnjinhao** [comment]
Fixed! There is a fix also has been checked into branch `hotfix-1.7.4`
