### ISSUE TITLE
能不能做一个和Qt的QWidget::winId()函数类似的功能，生成一个NativeControl

### ISSUE THREAD

**Issue by yinkaisheng** [cnjinhao/nana#567]
做界面有些地方需要平台的原生控件，比如视频播放器，视频播放窗口需要一个原生控件给播放器去播放。

我现在是参考nana-demo\Examples\windows-subclassing.cpp生成一个Windows原生控件去播放视频，但有点麻烦。
希望nana提供一个简单的方法，能创建各平台的一个原生控件。
![image](https://user-images.githubusercontent.com/5846696/94096825-a7db5300-fe57-11ea-832a-f5bf9666e474.png)

Thanks.

**Comment by cnjinhao** [comment]
有个nana::API::root()可以用。获得指定窗口的原生系统句柄。需要注意的是，如果参数是窗口上的widget，得到的原生句柄也是这个窗口的句柄。API::root(textbox_ykstest) == API::root(form) 结果是true.

直接在窗口上放一个native的窗口，可能在处理布局时会变得比较棘手，比如form用place来处理布局的。这个时候，可以先放一个nested_form，让place自动处理布局，然后把你的native窗口放在nested_form上，并处理nested_form的resized事件，使native窗口的大小和nested_form保持一致。
