### ISSUE TITLE
Filebox cannot select file names with a space: feature or bug?

### ISSUE THREAD

**Issue by biquad** [cnjinhao/nana#569]
Hi,
I have recently started a small project and find that nana is a breeze to use compared to many GUI alternatives. However, as I dig into the framework, I also start to find some (apparent) bugs or "inconveniences". The first one concerns the filebox utility.

If I compile the example from the nanapro documentation (http://nanapro.org/en-us/documentation/page.php?u=/utilities/filebox), I can select any filename, except filenames that contain a space, such as "This is a text file.txt". 

So some question to the developer(s) or anybody else contributing to the code base:
- is that a feature (i.e. intended behavior) or a bug?
- wouldn't it be better to delete the code that validates filenames, especially if they are loaded from the operating system, or
   make use of std::filesystem::exists(filename) (C++17)
- if the implementation changes to accept spaces, is there anything that I have overlooked?

Finally some question about how to do it? 
- I would be happy to make the necessary changes but should it be in the 1.7.4 or in the 1.8 branch (I didn't check if the problem is the same in 1.8 yet), and
- how is the review process working for nana?

Any feedback is welcome!

Best regards

= = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
System: Ubuntu 20.04 LTS, gcc
Current tagline: Nana is a beautiful GUI with hidden features

**Comment by qPCR4vir** [comment]
Hi,
Happy you liked nana...
I have been using nana::filebox for years in windows and never saw this problem. A problem in the implementation for X11?

> is that a feature (i.e. intended behavior) or a bug?

If certain. this is a bug (in the library or some setting).

>or make use of std::filesystem::exists(filename) (C++17)

Yes, use std::filesystem

Bug fixes go to 1.7.4. Only if you find very very difficult to work with old code with workarounds for old compilers go directly to 1.8 which has a clearer c++17 code.

>how is the review process working for nana?

uf.. here and with almost everything we will appreciate any help. Very simple: You post your PR, it will be automatically tested in Travis and manually reviewed and merged.

**Comment by cnjinhao** [comment]
@biquad , fixed! Thanks for your feedback.

**Comment by cnjinhao** [comment]
>I would be happy to make the necessary changes but should it be in the 1.7.4 or in the 1.8 branch (I didn't check if the problem is the same in 1.8 yet), and

Small fixes, goto `1.7.4`, it will help people who are using `1.7.4`,
`1.8` is recommended for big changes, because there are already many changes between `1.8` and `1.7.4`. If the big changes are committed to `1.7.4`, there will be many conflicts to fix when merge `1.7.4` into `1.8`

**Comment by biquad** [comment]
Hi folks,

Thanks for accepting the proposal - impressed by the speed of the update!

Follow-up remark: I put in the title of this issue the question whether the behavior should be considered a bug or a feature. In my view, it is a bug because  the intended behavior of a filebox is to open any file valid file. Hence, - in my view again - the update should both be in 1.7.4 (the current hot-fix) as well as 1.8-develop (looking forward). 

It all boils down the meaning of 'hot-fix' and 'develop' in this project. 

I was re-reading the explanation on the front page. The explanation is short and dry (good) but does not really help the causal user of the framework to select which branch to download. Could it be improved?

**Comment by cnjinhao** [comment]
@biquad , I checked the fix into branch `develop-1.8` yesterday. Generally all fixes that occur in existing versions should be checked into the hotfix branch, now there is a fix has been checked into `1.7.4`

**Comment by biquad** [comment]
Great -  Thanks a lot!
