### ISSUE TITLE
window 7 线程数问题？why win7 more than 10 threads?

### ISSUE THREAD

**Issue by sdlforever** [cnjinhao/nana#570]
在win7下只是单单建立一个窗体几个显示字符为什么就会有如此多的线程呢？
In win7, why there are so many threads just to create a form with a few display characters?

**Comment by cnjinhao** [comment]
具体情况不清楚，多出来的线程都是操作系统创建的。debug模式下线程数量比release模式的多，还可能有其他程序的线程，比如杀毒软件
