### ISSUE TITLE
fatal error while installing nana library

### ISSUE THREAD

**Issue by Dragosp33** [cnjinhao/nana#580]
So i tried quite a few times installing the nana c++ library, even with different versions of code::blocks (v20.3 first, now 17.12) and different versions of nana (1.7.4 first, 1.7.0 now) and i still can't build the nana.cbp file. 
I did all the installation steps, but when i build the project i get this error:

||=== Build: Debug in nana (compiler: GNU GCC Compiler) ===|
..\..\include\nana\filesystem\filesystem.hpp|122|fatal error: experimental/filesystem: No such file or directory|
..\..\include\nana\filesystem\filesystem.hpp|122|fatal error: experimental/filesystem: No such file or directory|
..\..\include\nana\gui\detail\..\..\filesystem\filesystem.hpp|122|fatal error: experimental/filesystem: No such file or directory|
..\..\include\nana\filesystem\filesystem.hpp|122|fatal error: experimental/filesystem: No such file or directory|
..\..\include\nana\filesystem\filesystem.hpp|122|fatal error: experimental/filesystem: No such file or directory|
..\..\include\nana\filesystem\filesystem.hpp|122|fatal error: experimental/filesystem: No such file or directory|
..\..\include\nana\filesystem\filesystem.hpp|122|fatal error: experimental/filesystem: No such file or directory|
||=== Build finished: 7 error(s), 0 warning(s) (0 minute(s), 1 second(s)) ===|

:-? i really can't understand what i'm doing wrong

**Comment by cnjinhao** [comment]
These errors occur if you use the compiler which comes with CB. Please read the `Using MSYS2` section in this [guide](https://github.com/cnjinhao/nana/wiki/Troubleshooting-MinGW) to fix these errors.

**Comment by Dragosp33** [comment]
Thank you, i appreciate the fast reply! It now works 👍
