### ISSUE TITLE
A bit large executable (Windows)

### ISSUE THREAD

**Issue by Nan1t** [cnjinhao/nana#588]
Hello! First, i want to say thank you for the simple and lightweight GUI library. You guys are great!

In the [documentation](https://github.com/qPCR4vir/nana-docs/wiki#what-is-nana-c-library-octocat-) says than basic statically linked in release mode nana progran will be around 1-3 MB. My demo program compiled in release mode is around 5.8 MB. Is this normal for newest version of nana? It's not that important, but i'd like to keep the size of the application as small as possible.

Main.cpp file: https://pastebin.com/itd4BEeU
CMakeLists.txt: https://pastebin.com/HfH9WDzF

I've compiled nana for Windows, using TDM-GCC-64 in release mode and final library was 7.5 MB (if it matters).

**Comment by qPCR4vir** [comment]
Unfortunately optimizing for size with TDM-GCC-64 or mingw in general is not easy. Out of the box you will see 40-80 MB executables. What you have is already OK. For smaller sizes you will need to make sure all debug info is really eliminated, add stripers, etc. etc. And this will change for each compiler distro. In my experience I develop using mingw (and CLion) which I can install in any PC (no need to be admin), but when I really want to release a very small executable with no dependence on any dll I just recompile with MSVCpp. 
Anyway if you go and optimize using your current compiler, please tell me how you got the best result !

**Comment by Nan1t** [comment]
Okay, thanks for the detailed answer. After little research, i realized that this is really quite difficult to do, it is easier to use a dynamic linking if the size becomes too large. Anyway, if i find a way, i'll tell you.
