### ISSUE TITLE
(nana 1.8)textbox input cursor position is not right on some text

### ISSUE THREAD

**Issue by yinkaisheng** [cnjinhao/nana#589]
![nana](https://user-images.githubusercontent.com/5846696/102888924-a3ddc200-4494-11eb-81a7-bb9bf1f91591.gif)

**Comment by cnjinhao** [comment]
I input the same text in a textbox, the cursor position is right. IMO there are invisible characters in the text that cause the problem, would you please copy the text in a file and send it to me.

**Comment by yinkaisheng** [comment]
the following json text can produce the bug:
{
    "che.audio.set_file_as_playout_volume": 100
}
![nana_text](https://user-images.githubusercontent.com/5846696/103502658-db813c80-4e8c-11eb-9ecb-04f24ec7b2cf.gif)

**Comment by cnjinhao** [comment]
Thank you a lot for providing information of this bug!
Fixed
