### ISSUE TITLE
How to change text size and the type of font of nana::textbox

### ISSUE THREAD

**Issue by pvzzombs** [cnjinhao/nana#593]
**Hello to the Nana C++ GUI Creators 😀**.  I am very happy to use your c++ GUI library. This is the easiest gui library I have used.

• How do I change the **text size** and **the type of font** of a `nana::textbox`?

I want to make the `nana::textbox` text bigger since I feel it to be so small when I read the texts in the textbox? Any methods that will help me? Thanks to all!

**Comment by cnjinhao** [comment]
```
textbox.typeface(paint::font_info{"font_name", 10.0/*pt*/, 700/*bold*/, true, true, true});
```

**Comment by netzeng** [comment]
textbox.typeface(paint::font_info{"Segoe UI", 10.0/*pt*/, 700/*bold*/, true, true, true});
