### ISSUE TITLE
Is it possible to change the color of or remove this line in listbox?

### ISSUE THREAD

**Issue by ventsin** [cnjinhao/nana#599]
I'm always poking around to see how nana handles small color details.
![image](https://user-images.githubusercontent.com/11967147/104724892-18acc080-5710-11eb-9080-bdb447f1a104.png)

This white(0xEBF4F9) line is drawn at line 4064 of listbox.cpp in the `master` branch and at line 4061 in the `develop-1.8` branch.
Without modifying the library, is it possible to change the color of this line, or otherwise remove it?

As you can see it becomes eye-piercing when combined with darker colors.

Also is there a plan to add the small detail colors of widgets to their schemes? Recently I had to use a custom background for the button widget because the four corners have a single pixel drawn in the default nana background color.

**Comment by cnjinhao** [comment]
Thanks for your feedback! The color of the line in listbox now is updated automatically to match the background color when the background color is changed. The colors of corners of the button is rendered to match the background color of its parent window.

**Comment by ventsin** [comment]
Thanks a ton, it looks great!
