### ISSUE TITLE
Nana GCC compile error

### ISSUE THREAD

**Issue by Farrukh2019** [cnjinhao/nana#600]
paint\image.cpp was not compiling at line 144

			`std::ifstream file{ p, std::ios::binary };`	
Changed p to p.string() fixed the problem and code compiled.
			`std::ifstream file{ p.string(), std::ios::binary };`

**Comment by Farrukh2019** [comment]
Kindly check if this correct change , update project.

**Comment by cnjinhao** [comment]
What's the version of GCC are you using?

**Comment by Farrukh2019** [comment]
gcc (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0

**Comment by cnjinhao** [comment]
`8.1` is not recommended, please refer to this https://github.com/cnjinhao/nana/wiki/Troubleshooting-MinGW for detail.

**Comment by Farrukh2019** [comment]
thanks @cnjinhao its very helpful information.
