### ISSUE TITLE
textbox scrolling doesn't scroll to top/bottom properly

### ISSUE THREAD

**Issue by ashbob999** [cnjinhao/nana#603]
Using the [textbox with line numbers](https://github.com/qPCR4vir/nana-demo/blob/master/Examples/textbox_line_number.cpp) example, so that the issue is easier to see.
When we add enough lines to make the scroll bar appear, and you scroll to the top of the textbox it does not scroll right to the top but scrolls to 1 line before. You then have to scroll down, then up to get to the first line.
This also happens when you scroll to the bottom line.

After testing it only happens when the line count is even.

Attached are 2 videos showing what I mean
[Odd Lines](https://user-images.githubusercontent.com/32575256/106309133-99fc6b00-6259-11eb-8daa-df1bb20d10af.mp4)
[Even lines](https://user-images.githubusercontent.com/32575256/106309151-9d8ff200-6259-11eb-8714-f7d34280d867.mp4)

**Comment by cnjinhao** [comment]
Fixed! Thank you a lot for reporting this bug.

**Comment by ashbob999** [comment]
Thanks, works smoothly and as intended now.
