### ISSUE TITLE
nana::progress won't go borderless, and other things

### ISSUE THREAD

**Issue by ventsin** [cnjinhao/nana#604]
Hello again, first I'd like to report a bug on `nana::progress`.
![image](https://user-images.githubusercontent.com/11967147/106492392-a15c8800-6496-11eb-9c93-05bf57e2ef64.png)

All progress bars in this image are set to alternate between their `borderless()` states on click, and I've confirmed that the event is working properly.
Yet they always have the border around them.
Ideally the `borderless()` behavior would be fixed, but it would also be interesting if the border color could be manipulated through the scheme.

Lastly, I'd also like to make a suggestion regarding the scheme of this widget.
Currently, the scheme has four members: `foreground`, `background`, `gradient_fgcolor` and `gradient_bgcolor`.
The names, in my opinion, are a bit inconsistent and maybe unclear. The background and foreground are also parts of the gradient, but have no such indication. I assume these members are difficult to change since they seem to be a part of the base widget. So maybe the others could be changed to be a bit clearer when testing:
`gradient_fgcolor` -> `bottom_foreground` or `lower_foreground`
`gradient_bgcolor` -> `bottom_background` or `lower_background`
Do you think this change would make sense?

**Comment by cnjinhao** [comment]
Thanks for your feedback! Would you like to contribute a PR?
