### ISSUE TITLE
build failed 

### ISSUE THREAD

**Issue by hamedmohammadi** [cnjinhao/nana#61]
why i can not find ft2builder but libfreetype2 and libfreetype2-dev are installed and their links are exists in /usr/include/freetype2/ft2build.h

**Comment by hamedmohammadi** [comment]
➜  try-nana  bii build
INFO: Processing changes...
Building: "cmake" --build . 
[ 14%] Built target zlib_zlib
[ 27%] Built target glenn_png
[ 28%] Building CXX object qiangwu_nana/CMakeFiles/qiangwu_nana.dir/source/deploy.cpp.o
In file included from /home/hamed/Desktop/r&d/try-nana/deps/qiangwu/nana/include/nana/detail/linux_X11/platform_spec.hpp:36:0,
                 from /home/hamed/Desktop/r&d/try-nana/deps/qiangwu/nana/source/deploy.cpp:23:
/usr/include/X11/Xft/Xft.h:39:22: fatal error: ft2build.h: No such file or directory
 #include <ft2build.h>
                      ^
compilation terminated.
make[2]: *** [qiangwu_nana/CMakeFiles/qiangwu_nana.dir/source/deploy.cpp.o] Error 1
make[1]: *** [qiangwu_nana/CMakeFiles/qiangwu_nana.dir/all] Error 2
make: *** [all] Error 2
ERROR: Build failed

**Comment by cnjinhao** [comment]
This issue deponds on what distribution of Linux, Try to google "/usr/include/X11/Xft/Xft.h:39:22: fatal error: ft2build.h: No such file or directory", you may find the answer.

**Comment by hamedmohammadi** [comment]
issue was from ubuntu and i report that tnx for your help
