### ISSUE TITLE
你这个看起来还可以啊，可以让华为进来集成到鸿蒙吗？

### ISSUE THREAD

**Issue by lanmanck** [cnjinhao/nana#633]
国货当自强哦

**Comment by alex3236** [comment]
**Github Issues is not the place for you to joke around. Please behave yourself.**

**Comment by lanmanck** [comment]
> **Github Issues is not the place for you to joke around. Please behave yourself.**

hui shuo ji ju ying wen jiu niu bi le. wu ke lan shi jian hai mei ba ni zhi cai shi ba?
