### ISSUE TITLE
Submenu in a menu bar does not work.

### ISSUE THREAD

**Issue by beru** [cnjinhao/nana#65]
Hi, I'd like to use submenus in a menu bar but so far I can't make it work.
I use below code to check the issue. Could you please take a look at it?

```c++
#include <nana/gui.hpp>
#include <nana/gui/widgets/menubar.hpp>

int main()
{
	using namespace nana;

	form fm(API::make_center(500, 300));
	fm.caption(L"submenu test");
	
	menubar mb(fm);
	mb.push_back(L"&File");
	mb.push_back(L"&View");

	auto& menu_view = mb.at(1);
	menu_view.append(L"Test 0");
	menu_view.append(L"Test 1");
	menu_view.create_sub_menu(1)->append(L"aa");
	
	// from http://nanapro.org/en-us/help/widgets/menu.htm
	menu mobj;
	mobj.append(STR("Item 0"));
	mobj.append(STR("Item 1"));
		mobj.create_sub_menu(1)->append(STR("A sub menu item"));
	mobj.renderer(mobj.renderer());
	mobj.item_pixels(30);

	fm.events().click(menu_popuper(mobj));

	fm.show();
	exec();
}
```

**Comment by cnjinhao** [comment]
Thank you for reporting this issue, it also causes a crash error. When the submenu is popped up, move the cursor to the "Item 0", the submenu is being closed, at the same time, the program crashs.
A fix has been checked into the hotfix branch.

**Comment by beru** [comment]
Thank you for the fix. I confirmed that a submenu in a menubar works now.
Other subtle issues I noticed are as follows.

- Left clicking a submenu item in a menu does not immediately open its submenu.
- Behavior of opening a submenu by cursor keys is weird now.
  - Pressing left key opens a submenu but pressing right key does not open a submenu.
- Right clicking a menu works but should it work?

**Comment by cnjinhao** [comment]
Hi, a fix for the menu bahavioral issues has checked into the hotfix branch. Look forward to your feedback.

**Comment by beru** [comment]
Thank you for the fix.
I confirmed that three subtle issues (in my prev post) are fixed now.
