### ISSUE TITLE
Direct Support for PNG/JPEG

### ISSUE THREAD

**Issue by Adityamishra018** [cnjinhao/nana#654]
I am using Cmake + MinGW on windows 10 and i got the library setup very easily for myself... It was all nice and fun till i realized there is no support for images and i have to rebuild entire thing again adding certain files to directories that I got from sourceforge and in the end I couldn't get it to work even after building everything and linking everything (-lnana -ljpeg -lpng -lzlib) there was still a lot of linking errors...

Either update docs or just provide direct support for this kind of essential functions

**Comment by ErrorFlynn** [comment]
I had no problem adding JPEG support, take a look at this thread: http://nanapro.org/en-us/forum/index.php?u=/topic/1368/ggjpg
I haven't tried adding PNG support, but I assume it's a similar process.

**Comment by Adityamishra018** [comment]
yes right that worked, the link that you have in the documentation section
provides us with binaries that would only work in MSVC.
update the docs, nice library 👍
