### ISSUE TITLE
Compilatation error on vs2015

### ISSUE THREAD

**Issue by Waty** [cnjinhao/nana#69]
When compiling the development branch using the project in `build\vc2015` and VS2015 Enterprise, the compiler gives the following error:

    c:\users\waty\source\repos\nana\source\gui\element.cpp(267): error C2662: 'nana::rectangle &nana::rectangle::pare_off(int)': cannot convert 'this' pointer from 'const nana::rectangle' to 'nana::rectangle &'

The error disapears when you change 
```c++
graph.rectangle(::nana::rectangle{ r }.pare_off(1), false, bgcolor);
```

to
```c++
graph.rectangle(::nana::rectangle(r).pare_off(1), false, bgcolor);
```

**Comment by cnjinhao** [comment]
Thank you for reporting this issue. I tried it using VS2015 Community RC(14.0.22823), but the issue wasn't reproduced.

**Comment by qPCR4vir** [comment]
Hi,
I'm testing now with VS2015 Community RTM (Version 14.0.23107) and I confirm the problem. I "fixed" it taking a copy of the rectangle and not a reference, becouse we make a copy anyway.

		class border_depressed
			: public border_interface
		{
			bool draw(graph_reference graph, const ::nana::color& bgcolor, const ::nana::color& fgcolor, ::nana::rectangle r, element_state estate, unsigned weight)
			{
				graph.rectangle(r, false, static_cast<color_rgb>((element_state::focus_hovered == estate || element_state::focus_normal == estate) ? 0x0595E2 : 0x999A9E));
				graph.rectangle(r.pare_off(1), false, bgcolor);
				return true;
			}
		};

**Comment by cnjinhao** [comment]
A fix has been checked into the develop branch.
