### ISSUE TITLE
DPI scale text issue with menu_drawer

### ISSUE THREAD

**Issue by edgarbernal5** [cnjinhao/nana#692]
Hi!
I've found an issue with menu_drawer that is not drawing text correctly upon switching forms from different DPI scales. Here is an example when opens a form in a 4K monitor, looks good:

![Menu 4k](https://github.com/cnjinhao/nana/assets/1410581/68fbf59b-1ae3-4e7f-9f02-5b3570825e60)

but when change to a HD monitor, it looks like this:

![Menu hd](https://github.com/cnjinhao/nana/assets/1410581/47b6641a-2105-4132-b427-c6cda35beba4)

Text renderer from menu_bar seems to work as expected, pretty sure it is the same renderer for items in menu_drawer. Don't know what is happening. Make sure that start_dpi_awareness() is been called at startup.

Thanks again!

**Comment by qPCR4vir** [comment]
Your #690 + #695  solved this for you?

**Comment by qPCR4vir** [comment]
There are many others and serous issues with DPI scaling. We are investigating solutions. See  #690 , make DPI experimental: #699, etc. 
Please see Discussions: #698, #702 , #701
