### ISSUE TITLE
Standard Layout system

### ISSUE THREAD

**Issue by adeolaibigbemi** [cnjinhao/nana#696]
Hi Guys,
Does nana has any standard layout system aside placing elements using cordinates.

I can't really find any standard documentations and tutorials also.

**Comment by qPCR4vir** [comment]
Yes, It is call place.
Nana C++ Library. Reference for users.: Home. Reference documentation. {for nana users, hotfix-1.7.2, 2019-12-04} https://qpcr4vir.github.io/nana-doxy/html/index.html
And the github wiki

**Comment by qPCR4vir** [comment]
Nana C++ Library. Reference for users.: nana::place Class Reference https://qpcr4vir.github.io/nana-doxy/html/dc/de3/classnana_1_1place.html

**Comment by qPCR4vir** [comment]
Using place for layouts · qPCR4vir/nana-docs Wiki · GitHub https://github.com/qPCR4vir/nana-docs/wiki/Using-place-for-layouts

**Comment by adeolaibigbemi** [comment]
Thanks @qPCR4vir
