### ISSUE TITLE
Does it support FreeBSD?

### ISSUE THREAD

**Issue by ghost** [cnjinhao/nana#706]
And which branch should I clone? Thank you.

**Comment by thearchivalone** [comment]
Master branch builds fine for me on FreeBSD 14.0. Just run the following (as long as you have the proper dependencies installed).

```
cmake -G Ninja . -B builder
cmake --build builder --parallel $(nproc)
```

**Comment by ghost** [comment]
The makefile build/makefile/makefile works with gmake, too. I'm using it.
