### ISSUE TITLE
cmake thread default for MinGW out of date

### ISSUE THREAD

**Issue by htzh** [cnjinhao/nana#76]
NANA_THREAD_NOT_SUPPORTED is hard coded in [CMakeLists.txt](https://github.com/cnjinhao/nana/blob/master/CMakeLists.txt#L58) to ON. I think it should be OFF by default esp. for non-gui users of cmake. Better yet this could be automatically tested. I followed the example given in this [SO post](http://stackoverflow.com/questions/14933172/how-can-i-add-a-minimum-compiler-version-requisite) and wrote a test for this:
```
option(NANA_THREAD_NOT_SUPPORTED "Use this flag if MinGW version is older than 4.8.1" OFF)
if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
  if(CMAKE_CXX_COMPILER_VERSION VERSION_LESS "4.8.1")
    option(NANA_THREAD_NOT_SUPPORTED "Use this flag if MinGW version is older than 4.8.1" ON)
  endif()
endif()
```

**Comment by cnjinhao** [comment]
Thank you, the commits have been merged into hotfix branch.
