### ISSUE TITLE
Inverted vertical slider

### ISSUE THREAD

**Issue by BenjaminNavarro** [cnjinhao/nana#82]
When a vertical slider is used, it seems to be inverted (0 at the top and vmax at the bottom).

I suppose it's a bug. I looked at the code but I didn't find a way to fix this.

Thanks to look at this

**Comment by cnjinhao** [comment]
Thank you for reporting this issue, a fix has been checked into develop branch.

**Comment by BenjaminNavarro** [comment]
Thanks, I tested it and it works well!
