### ISSUE TITLE
Doesn't build with clang/libc++

### ISSUE THREAD

**Issue by Exaeta** [cnjinhao/nana#83]
The program wont build using libc++ and clang on linux. I have problems with using libstdc++ on linux because of missing functions and errors when compiling it with clang.

**Comment by kirbyfan64** [comment]
What exactly were the errors?

**Comment by Exaeta** [comment]
`
rnicholl@rnicholl-Inspiron-5720 ~/nana/build/makefile $ make
clang++-3.6 -stdlib=libc++ -std=c++11 -DNANA_LINUX -g -c ../../source/charset.cpp -o ../../source/charset.o -I../../include -I/usr/include/freetype2 -Wall
../../source/charset.cpp:228:14: warning: enumeration value 'utf8' not handled in switch [-Wswitch]
                                                switch(encoding)
                                                       ^
../../source/charset.cpp:242:14: warning: enumeration value 'utf16' not handled in switch [-Wswitch]
                                                switch(encoding)
                                                       ^
../../source/charset.cpp:256:14: warning: enumeration value 'utf32' not handled in switch [-Wswitch]
                                                switch(encoding)
                                                       ^
3 warnings generated.
clang++-3.6 -stdlib=libc++ -std=c++11 -DNANA_LINUX -g -c ../../source/datetime.cpp -o ../../source/datetime.o -I../../include -I/usr/include/freetype2 -Wall
clang++-3.6 -stdlib=libc++ -std=c++11 -DNANA_LINUX -g -c ../../source/deploy.cpp -o ../../source/deploy.o -I../../include -I/usr/include/freetype2 -Wall
../../source/deploy.cpp:23:11: error: expected "FILENAME" or <FILENAME>
        #include PLATFORM_SPEC_HPP
                 ^
1 error generated.
make: *** [../../source/deploy.o] Error 1
`

**Comment by cnjinhao** [comment]
It seems that the makefile was generated by cmake, but I have no idea about why the definition of PLATFORM_SPEC_HPP is missing. Please re-extract the files from the zip file, and find makefile in "build/makefile" folder, open it, modify "GCC=g++" to "GCC=clang++", save the modification and make.
