### ISSUE TITLE
examples compiled with develop branch

### ISSUE THREAD

**Issue by qPCR4vir** [cnjinhao/nana#84]
Hi,
congratulation, I compiled all the 50 examples with VS2015 in Windows 7 Pro 64x using debug Win32 and static linked cpp run time:
(I returned some configuration to the project)

Commit: e46c5e46d766be6e10ed10bc00aed23012dbf8da [e46c5e4]
Parents: 09b314b94c
Author: Jinhao <cnjinhao@hotmail.com>
Date: Donnerstag, 22. Oktober 2015 18:56:10
Labels: HEAD, nana_jinhao/develop, cnjinhao/develop, develop
fix leak of memory for class animation 

and with 0 errors and 0 warnings.

Now I will run each and test and will write here the results.

**Comment by qPCR4vir** [comment]
a_group_impl    --> don't show anything ??
animate-bmp    --> OK
audio_player_simple   ---> OK
audio_player    --> OK
background-effects  ---> OK! Work perfect now, but compared with a release compiled 2015-06-17 the
                                       bottoms blink black by windows resizing. 
calculator   --> Ok, but compared with a release compiled 2015-06-17 the bottoms blink black by   
                       windows resizing. I will test with release aging.

**Comment by qPCR4vir** [comment]
categ   --> OK
clicked  -->OK. Compared with a release compiled 2015-06-17 it now respond only to the left click and
                       double click (respond twist). The old version responded with all three left, center and 
                       right bottoms and double click with each.

**Comment by qPCR4vir** [comment]
decore  --> OK
drag-button --> OK
draw --> it has one rote line more ?

**Comment by qPCR4vir** [comment]
example.button --> OK. The bottom widgets respond only to the left mouse bottom -ok.
example_combox  --> OK.  The combox widgets respond to all mouse bottom - ok?.

**Comment by qPCR4vir** [comment]
example_listbox  --> OK. The listbox widgets respond to all mouse bottom - ok?.
example_menu  --> OK. Both the new and the old version show the menu clicking the bottom widget with any mouse bottom. The menu item widgets respond only to the left mouse bottom -ok.

**Comment by qPCR4vir** [comment]
file_explorer  --> Works !! Thank to @k1988 
https://github.com/qPCR4vir/nana-demo/pull/3

**Comment by qPCR4vir** [comment]
filebox-txt --> OK

**Comment by qPCR4vir** [comment]
FreeMe --> OK.
group --> Only shows the most external group  :-(

**Comment by qPCR4vir** [comment]
HelloWord --> OK
HelloWord-Quit --> OK
inputbox --> OK. The spinbox widgets respond to all mouse bottom - ok?.

**Comment by qPCR4vir** [comment]
label_listener --> OK. The label widgets respond only to the left mouse bottom -ok. 
lambda_event.Cpp11 --> OK. The window widgets respond only to the left mouse bottom -ok. 
listbox_inline  --> OK
listbox_Resolver --> OK
loader_1, 2 --> OK
mbox --> OK
menu_debug --> OK
menu_popuper --> Ok

**Comment by qPCR4vir** [comment]
modal_form --> OK
MontiHall --> OK
notepad --> OK
place_login --> OK, but the bottoms and textbox blink black by windows resizing.

**Comment by qPCR4vir** [comment]
screen --> OK
stretch_image --> OK
threading --> OK
thread-pool --> OK
various_events --> OK

**Comment by qPCR4vir** [comment]
widget_show --> work, but not show the last fields: the label and the category widget.
The checkbox widgets respond only to the left mouse bottom -ok, and get focus with any
The bottom with image show a big image, not stretched.

**Comment by qPCR4vir** [comment]
window-dragger --> OK
windows-subclassing --> OK

**Comment by qPCR4vir** [comment]
in 1.1.3 it was OK

**Comment by cnjinhao** [comment]
Thank you for testing the latest code. I will check these errors.

**Comment by qPCR4vir** [comment]
uff... good news ! 
The problem with the example "group" was solved: the introduction of the new keywords "left" and "right" broked the example's code. 
I changed my name field to left_field and all is OK. I will retest and rewrite the comments here.

**Comment by qPCR4vir** [comment]
dock --> OK   !!!!    Added this example too. It run great !

**Comment by qPCR4vir** [comment]
OK !!!!!
All is OK. Only small inconsistencies...

Congratulations !!!
