### ISSUE TITLE
textbox: Linux/X11+Unicode strange caracters on shift, ctrl, arrows, etc

### ISSUE THREAD

**Issue by leobackes** [cnjinhao/nana#87]
When using the textbox on Linux, nana inserts squares in the text when pressing arrow keys, shift, ctrl, capslock, insert, home, etc...
Shift also causes some other issues, as entering shift+1 ( !, the exclamation) twice erases a portion of the text, as if the text got selected then replaced.

**Comment by cnjinhao** [comment]
Thank you for reporting this issue, I will check it
