### ISSUE TITLE
high ram usage 

### ISSUE THREAD

**Issue by Pr0curo** [cnjinhao/nana#88]
Hi,

when i run this simple program:
```
#include <nana/gui.hpp>
int main()
{
	nana::form f;
	f.show();
	nana::exec();
	return 0;
}
```
it starts windowed and takes 2MB of ram, very much for a simple form.
When i maximize the form, it suddenly takes up to 18MB of ram.

If I add widgets, it suddenly uses even more than that, and i mean not just some more bytes, but again Megabytes more.

This happens in Debug and Release mode, and is independent from the used compiler (tried vc2015 and mingw 5.1) at least on Windows 10. I'm not able to test on other platforms currently.

in my opinion the ram usage is way to high.

is this known and accepted or is somebody working on it?

can we do something to get the ram usage lower?

best regards, jan

**Comment by kirbyfan64** [comment]
Did you compare it to the RAM usage of other GUI libraries, such as Gtk+ or Qt?

**Comment by Pr0curo** [comment]
To be fair, I did not compare it to other GUI libraries, because what rang the bell was that the ram usage is the higher the larger the window size gets. That at least seems not intuitive to.

**Comment by cnjinhao** [comment]
It depends on the display resolution, Nana allocates display buffers for every non-lite_widget widget, if widgets are large, it takes more ram. The benefit of this strategy is being able to gain good efficiency.
This strategy will be optimized for reducing ram usage in the future.

**Comment by Pr0curo** [comment]
Thanks for the information. I'm looking foreward for the optimisations, but its definetly not critical. 
Best regards, Jan
