### ISSUE TITLE
the click event lost mouse and keyboard info 

### ISSUE THREAD

**Issue by hhggit** [cnjinhao/nana#89]
I don't think changing the `click` event from `basic_event<arg_mouse>` to `basic_event<arg_click>` is a good idea. It causes losing many useful infomations and making the `click` and `dbl_click` acting  quite differently. 
 Perhap inheriting  `arg_click` from `arg_mouse` is more suitable.

>ps:why the **Alt** key disappeared from `nana`?

````cpp
	struct arg_mouse
		: public event_arg
	{
		event_code evt_code; ///< 
		::nana::window window_handle;  ///< A handle to the event window
		::nana::point pos;   ///< cursor position in the event window
		::nana::mouse button;	///< indicates a button which triggers the event

		bool left_button;    ///< mouse left button is pressed?
		bool mid_button;     ///< mouse middle button is pressed?
		bool right_button;   ///< mouse right button is pressed?
		bool shift;          ///< keyboard Shift is pressed?
		bool ctrl;           ///< keyboard Ctrl is pressed?
	};

	struct arg_click : public event_arg
	{
		::nana::window window_handle;	///< A handle to the event window
		bool by_mouse;					///< Determines whether the event is emitted by clicking mouse button
	};

    basic_event<arg_click> click;		///< the window is clicked, but occurs after mouse_down and            before mouse_up
    basic_event<arg_mouse> dbl_click;	///< the window is double clicked

**Comment by cnjinhao** [comment]
Thanks for your feedback, a fix will be shown up in the next release. I encourage you continue offering constructive feedback.

**Comment by cnjinhao** [comment]
A ptr mouse_args added to arg_click that refers to arg_mouse for mouse info. If the arg_click is not emitted by mouse click, the mouse_args is null.
The alt member also added to arg_mouse.
