### ISSUE TITLE
Compile error with API::enum_widgets

### ISSUE THREAD

**Issue by beru** [cnjinhao/nana#90]
Compile error appears when I try to build a program that uses API::enum_widgets.

Usage is like this.
```cpp
API::enum_widgets(fm, false, [&](::nana::widget& widget){
	if (widget.handle() == mb.handle()) {
		return;
	}
	if (bShowPreview) {
		widget.hide();
	}else {
		widget.show();
	}
});
```

It seems the cause is with this commit, Revision: 1b5aed2e5f0341b1baea73bdaf2848543640e153
File : include/nana/gui/programming_interface.hpp
In nana::detail::enum_widgets_function::_m_enum_fn(), new implementation supplies two argments to _m_enum_call method.
After removing 2nd argment nullptr, the compile error is no more.
https://github.com/cnjinhao/nana/blob/1b5aed2e5f0341b1baea73bdaf2848543640e153/include/nana/gui/programming_interface.hpp#L116

**Comment by cnjinhao** [comment]
Thank you for reporting this issue and providing useful information
