### ISSUE TITLE
v1.2.1

### ISSUE THREAD

**Issue by qPCR4vir** [cnjinhao/nana#95]
Hi,
could you tag the last commit with a new sub-sub-version number?

**Comment by cnjinhao** [comment]
Sorry, I don't understand exactly what you mean. I always tag the last commit for every release.

**Comment by qPCR4vir** [comment]
I mean that if you add a simple Tag in git, GitHub automatically create a simplified "release" in 
https://github.com/cnjinhao/nana/releases

like I did in my fork:
https://github.com/qPCR4vir/nana/releases

I think it is a very simple way to say people that a simple but possible important fix was committed. just because the last fixes could help people trying to compile now. (one can also create "releases" in GitHub, but with a litter more effort)

**Comment by cnjinhao** [comment]
OK, I will tag for important fixes. The compile errors of 1.2 only occur on the package from sourceforge, but code on git is OK.

**Comment by qPCR4vir** [comment]
Thanks!
