### ISSUE TITLE
Missing file test.cpp

### ISSUE THREAD

**Issue by redagito** [cnjinhao/nana#99]
I want to use Nana as a git submodule for a project.

My project structure is as follows
> source/ ->  project source files
> external/ -> git submodules, nana is located here
> CMakeLists.txt

After attempting an out of source build with cmake, I get the following error
> CMake Error at external/nana/CMakeLists.txt:146 (add_executable):
> Cannot find source file:
> test.cpp

which seems to be caused by the cmake line
> add_subdirectory(external/nana)

OS: Ubuntu 14.04 LTS, 64 Bit
CMake: 3.2.2
Nana branch: Master
[CMakeLists.txt](https://github.com/cnjinhao/nana/files/92004/CMakeLists.txt)

**Comment by cnjinhao** [comment]
Hi, you can remove lines 146-148, thanks for your feedback.

**Comment by nabijaczleweli** [comment]
No, they can't. That's the whole *point* of `git submodule`. You should remove the reference to the nonexistant file `test.cpp` from `CMakeLists.txt`.
